const fs = require('fs');

function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

const roleEffects = {
  Tank: [
    'Equip: Increases your chance to block attacks with a shield by 2%.',
    'Equip: Increases defense rating by 8.',
    'Equip: When struck in melee, inflicts 10 Fire damage to the attacker.',
    'Equip: Increases threat generated by all attacks by 4%.',
    'Chance on hit: Grants a protective shield absorbing 350 damage for 8 sec.'
  ],
  PhysicalDPS: [
    'Equip: Improves your chance to get a critical strike by 1%.',
    'Equip: Improves your chance to hit by 1%.',
    'Equip: Increases attack power by 20.',
    'Chance on hit: Wounds the target for 65 Physical damage.',
    'Chance on hit: Increases melee attack speed by 5% for 8 sec.'
  ],
  SpellDPS: [
    'Equip: Increases damage and healing done by magical spells and effects by up to 14.',
    'Equip: Improves your chance to get a critical strike with spells by 1%.',
    'Equip: Improves your chance to hit with spells by 1%.',
    'Chance on hit: Blasts the target for 85 Nature damage.',
    'Chance on hit: Restores 75 mana over 6 sec.'
  ],
  Healer: [
    'Equip: Increases healing done by spells and effects by up to 24.',
    'Equip: Restores 3 mana per 5 sec.',
    'Equip: Increases the critical effect of your holy and nature spells by 1%.',
    'Equip: Your direct heals have a 3% chance to restore 150 mana.'
  ],
  General: [
    'Equip: Increases your resistance to all schools of magic by 5.',
    'Use: Increases movement speed by 20% for 6 sec. (3 Min Cooldown)',
    'Equip: Increases your armor by 75.'
  ]
};

const slotNames = {
  Head: ['Helm', 'Crown', 'Circlet', 'Cowl', 'Mask', 'Greathelm'],
  Shoulder: ['Spaulders', 'Mantle', 'Pauldrons', 'Epaulets', 'Amice'],
  Chest: ['Breastplate', 'Robes', 'Vest', 'Harness', 'Tunic', 'Hauberk'],
  Wrist: ['Bracers', 'Wristguards', 'Bindings', 'Cuffs', 'Vambraces'],
  Hands: ['Gauntlets', 'Gloves', 'Handguards', 'Grips', 'Mitts'],
  Waist: ['Belt', 'Girdle', 'Sash', 'Waistguard', 'Cord'],
  Legs: ['Legguards', 'Pants', 'Kilt', 'Greaves', 'Leggings'],
  Feet: ['Sabatons', 'Boots', 'Treads', 'Footpads', 'Slippers'],
  Finger: ['Band', 'Signet', 'Loop', 'Ring', 'Seal'],
  Trinket: ['Talisman', 'Charm', 'Medallion', 'Brooch', 'Relic'],
  Neck: ['Amulet', 'Pendant', 'Necklace', 'Choker', 'Collar'],
  Weapon: ['Greatsword', 'Blade', 'Staff', 'Gavel', 'Axe', 'Dagger', 'Bow'],
  Shield: ['Shield', 'Bulwark', 'Defender', 'Aegis', 'Buckler']
};

const prefixes = ['Venerable', 'Noble', 'Shimmering', 'Blood-Forged', 'Ancient', 'Runed', 'Shadow', 'Holy', 'Tempered', 'Savage', 'Stalwart', 'Crystalline'];
const suffixes = ['of the Vanguard', 'of the Unseen', 'of the Just', 'of the Archmage', 'of Ancient Valor', 'of the Forgotten', 'of the Sun', 'of Might', 'of the Deep', 'of the Champion'];

const specProfiles = {
  PlateTank: { role: 'Tank', armor: 'Plate', validWeapons: ['Sword', 'Mace', 'Axe'], primary: ['Stamina', 'Strength'], secondary: ['Defense', 'Dodge', 'Parry'] },
  PlateDPS: { role: 'PhysicalDPS', armor: 'Plate', validWeapons: ['Sword', 'Mace', 'Axe'], primary: ['Strength', 'Stamina'], secondary: ['Agility', 'Attack Power', 'Hit', 'Crit'] },
  PlateHealer: { role: 'Healer', armor: 'Plate', validWeapons: ['Mace', 'Sword'], primary: ['Intellect', 'Stamina'], secondary: ['Healing Power', 'MP5', 'Spirit'] },
  MailDPS: { role: 'PhysicalDPS', armor: 'Mail', validWeapons: ['Axe', 'Mace', 'Bow'], primary: ['Agility', 'Stamina'], secondary: ['Attack Power', 'Intellect', 'Crit', 'Hit'] },
  MailCaster: { role: 'SpellDPS', armor: 'Mail', validWeapons: ['Mace', 'Dagger'], primary: ['Intellect', 'Stamina'], secondary: ['Spell Damage', 'Spell Crit', 'Spell Hit'] },
  MailHealer: { role: 'Healer', armor: 'Mail', validWeapons: ['Mace'], primary: ['Intellect', 'Stamina'], secondary: ['Healing Power', 'MP5', 'Spirit'] },
  LeatherTank: { role: 'Tank', armor: 'Leather', validWeapons: ['Staff', 'Mace'], primary: ['Stamina', 'Agility'], secondary: ['Dodge', 'Armor', 'Strength'] },
  LeatherDPS: { role: 'PhysicalDPS', armor: 'Leather', validWeapons: ['Dagger', 'Sword', 'Mace'], primary: ['Agility', 'Stamina'], secondary: ['Strength', 'Attack Power', 'Hit', 'Crit'] },
  LeatherCaster: { role: 'SpellDPS', armor: 'Leather', validWeapons: ['Staff', 'Mace'], primary: ['Intellect', 'Stamina'], secondary: ['Spell Damage', 'Spell Crit', 'Spirit'] },
  LeatherHealer: { role: 'Healer', armor: 'Leather', validWeapons: ['Staff', 'Mace'], primary: ['Intellect', 'Spirit', 'Stamina'], secondary: ['Healing Power', 'MP5'] },
  ClothCaster: { role: 'SpellDPS', armor: 'Cloth', validWeapons: ['Staff', 'Dagger'], primary: ['Intellect', 'Stamina'], secondary: ['Spell Damage', 'Spell Crit', 'Spell Hit'] },
  ClothHealer: { role: 'Healer', armor: 'Cloth', validWeapons: ['Staff', 'Mace'], primary: ['Intellect', 'Spirit', 'Stamina'], secondary: ['Healing Power', 'MP5'] }
};

const loreThemes = {
  EmeraldNightmare: {
    prefixes: ['Dream-Scarred', 'Nightmare-Forged', 'Bough-Woven', 'Slumbering', 'Emerald', 'Dream-Watcher\'s'],
    suffixes: ['of the Waking Dream', 'of Ysera\'s Rest', 'of the Deep Slumber', 'of the Sacred Grove', 'of the Green Dragonflight']
  },
  GrimBatolRaid: {
    prefixes: ['Dragonmaw', 'Red Scale', 'Mountain-Forged', 'Searing', 'Wildhammer-Bane', 'Brood-Guard\'s'],
    suffixes: ['of the Mountain King', 'of the Red Flight', 'of the Dragon Queen', 'of the Great Anvil', 'of Ironforge']
  },
  CrownOfTheDamned: {
    prefixes: ['Necrotic', 'Plague-Warded', 'Scourge-Bane', 'Dusk-Bound', 'Frost-Forged'],
    suffixes: ['of Lordaeron', 'of the Ziggurat', 'of the Argent Vanguard', 'of the Holy Light', 'of Stratholme']
  },
  KarazhanRaid: {
    prefixes: ['Astral', 'Medivh\'s', 'Ethereal', 'Rift-Touched', 'Timeless', 'Guardian\'s'],
    suffixes: ['of the Ivory Tower', 'of the Astral Rift', 'of the Master\'s Archive', 'of Karazhan', 'of Netherwind']
  },
  DragonIslesRaid: {
    prefixes: ['Ancient', 'Proto-Drake', 'Titan-Carved', 'Obsidian', 'Primal', 'Ley-Infused'],
    suffixes: ['of the Dragon Isles', 'of the Proto-Aspects', 'of the Shifting Sands', 'of the Titans', 'of the Black Empire']
  }
};

const epicFlavorTexts = [
  "Crafted with immaculate precision by the master artisans of Azeroth.",
  "Forged in the heart of an ancient dwarven caldera.",
  "It hums with a deep, tranquil resonance.",
  "An heirloom passed down through generations of frontier champions.",
  "Light glints brilliantly along its balanced edges.",
  "Imbued with the stoic resilience of the old world.",
  "A testament to the craftsmanship of the Alliance and Horde.",
  "Worn by those who stood unbroken against the storm."
];

function generateLoot(count, levelStr = '60', theme = null, bosses = []) {
  let reqLevel = 60;
  let iLvl = 60;

  if (levelStr.includes('Tier 1.5')) { iLvl = 70; }
  else if (levelStr.includes('Tier 2.5')) { iLvl = 81; }
  else if (levelStr.includes('Tier 2')) { iLvl = 76; }
  else if (levelStr.includes('Tier 3.5')) { iLvl = 92; }
  else if (levelStr.includes('Tier 3')) { iLvl = 88; }
  else if (levelStr.includes('-')) {
    reqLevel = parseInt(levelStr.split('-')[1], 10);
    iLvl = reqLevel;
  } else {
    reqLevel = parseInt(levelStr, 10);
    iLvl = reqLevel;
  }

  const loot = [];
  let epicChance = (iLvl >= 70 || levelStr.includes('Tier')) ? 1.0 : (reqLevel >= 55 ? 0.20 : 0.05);

  for (let i = 0; i < count; i++) {
    const isEpic = Math.random() < epicChance;
    const rarity = isEpic ? 'Epic' : 'Rare';
    
    const specKeys = Object.keys(specProfiles);
    const specName = getRandom(specKeys);
    const spec = specProfiles[specName];
    
    const isWeapon = Math.random() > 0.8;
    const isJewelry = Math.random() > 0.7 && !isWeapon;
    const isShield = (spec.role === 'Tank' || spec.role === 'Healer') && Math.random() > 0.8;
    
    let type = '';
    let slot = '';
    let noun = '';

    if (isWeapon) {
      type = getRandom(spec.validWeapons);
      slot = (type === 'Staff' || type === 'Bow') ? 'Two-Hand' : getRandom(['Main Hand', 'One-Hand']);
      noun = getRandom(slotNames.Weapon);
    } else if (isShield) {
      type = 'Shield';
      slot = 'Off Hand';
      noun = getRandom(slotNames.Shield);
    } else if (isJewelry) {
      type = getRandom(['Ring', 'Trinket', 'Necklace']);
      slot = type === 'Ring' ? 'Finger' : (type === 'Necklace' ? 'Neck' : 'Trinket');
      noun = getRandom(slotNames[slot]);
    } else {
      type = spec.armor;
      slot = getRandom(['Head', 'Shoulder', 'Chest', 'Wrist', 'Hands', 'Waist', 'Legs', 'Feet']);
      noun = getRandom(slotNames[slot]);
    }

    let pList = prefixes;
    let sList = suffixes;
    if (theme && loreThemes[theme]) {
      pList = loreThemes[theme].prefixes;
      sList = loreThemes[theme].suffixes;
    }
    const name = `${getRandom(pList)} ${noun} ${getRandom(sList)}`;

    const stats = [];
    if (type !== 'Trinket') {
      const p1 = getRandom(spec.primary);
      const p2 = getRandom(spec.primary);
      
      // Scaled budget per Vanilla 1.12 curves
      let baseStatScale = Math.max(3, Math.floor(iLvl / 4));
      if (reqLevel <= 30) baseStatScale = Math.floor(iLvl / 5);
      
      const val1 = Math.max(3, baseStatScale + Math.floor(Math.random() * 3));
      const val2 = Math.max(2, Math.floor(baseStatScale * 0.75) + Math.floor(Math.random() * 2));
      
      stats.push(`+${val1} ${p1}`);
      if (p1 !== p2) stats.push(`+${val2} ${p2}`);
      
      const s1 = getRandom(spec.secondary);
      if (s1.includes('Crit') || s1.includes('Hit') || s1.includes('Dodge') || s1.includes('Parry')) {
        // Only grant hit/crit on higher level pieces (>= level 45 or epics)
        if (iLvl >= 45 || isEpic) {
          stats.push(`Equip: Improves your ${s1.toLowerCase()} by 1%.`);
        } else {
          stats.push(`+${Math.max(2, Math.floor(iLvl / 8))} ${p1}`);
        }
      } else if (s1.includes('Defense')) {
        stats.push(`Equip: Increases defense rating by ${Math.max(2, Math.floor(iLvl / 8))}.`);
      } else if (s1.includes('Power') || s1.includes('Damage')) {
        const pwrVal = Math.max(4, Math.floor(iLvl / 2.2));
        stats.push(`Equip: Increases ${s1.toLowerCase()} by up to ${pwrVal}.`);
      } else if (s1.includes('MP5')) {
        stats.push(`Equip: Restores ${Math.max(2, Math.floor(iLvl / 16))} mana per 5 sec.`);
      } else {
        stats.push(`+${Math.max(2, Math.floor(iLvl / 6))} ${s1}`);
      }
    }

    let effect = '';
    // Only give procs/effects when appropriate
    if (isEpic || (reqLevel >= 45 && Math.random() > 0.6)) {
      effect = getRandom(roleEffects[spec.role] || roleEffects.General);
    }

    const flavorText = isEpic && Math.random() > 0.4 ? getRandom(epicFlavorTexts) : '';
    const source = bosses.length > 0 ? `Dropped by: ${getRandom(bosses)}` : 'Dungeon Encounter';

    loot.push({
      name,
      rarity,
      bindType: 'Binds when picked up',
      slot,
      type,
      stats,
      effect,
      flavorText,
      source,
      requiresLevel: reqLevel,
      sellPrice: `${Math.floor(Math.max(1, (iLvl / 12) * (isEpic ? 1.5 : 1)))}g ${Math.floor(Math.random() * 85 + 10)}s`
    });
  }
  return loot;
}

const dungeons = [
  {
    id: 'StormwindVault',
    name: 'Stormwind Vaults',
    loreHistory: 'Hidden deep beneath the canals of Stormwind, this maximum-security prison houses the kingdom\'s most dangerous defected nobles, rogue sorcerers, and Defias leaders.',
    strategyGuide: 'Crowd control is vital. The tight subterranean corridors mean pulling multiple packs is fatal. Utilize corner pulls to break line of sight on Defias marksmen.',
    trashMobs: ['Corrupt Noble Guard', 'Vault Warden', 'Defias Infiltrator', 'Bound Voidwalker'],
    associatedQuests: ['The King\'s Justice (Dungeon)', 'Missing Diplomat: The Interrogation', 'A Noble\'s Treachery'],
    speedrunStrats: 'A Rogue with high Lockpicking can open the sewer sluice gate, bypassing the outer cellblocks directly to Dextren Ward.',
    environmentalHazards: 'Triggering alarm bells summons guard reinforcements until a player channels on the bell lever for 5 seconds.',
    secrets: ['A hidden stone tunnel behind a cracked cell wall leads back to the Stockades.', 'Pickpocketing the Head Jailer yields the Vault Sewer Key.'],
    wings: [
      { name: 'The Upper Brig', level: '25-30 (5 Man)', desc: 'The medium security holding cells.', bosses: ['Warden Thelwater', 'Targorr the Dread'], loot: generateLoot(10, '25-30') },
      { name: 'The Deep Cellblocks', level: '45-50 (5 Man)', desc: 'Where the kingdom\'s true enemies are locked away.', bosses: ['High Cultist Zenn', 'Dextren Ward'], loot: generateLoot(15, '45-50') },
      { name: 'The Interrogation Levels', level: '55-60 (5 Man)', desc: 'Dark interrogation vaults beneath the canal bedrock.', bosses: ['Interrogator Vishas', 'The Flesh-Shaper'], loot: generateLoot(25, '55-60') }
    ]
  },
  {
    id: 'KarazhanCrypts',
    name: 'Karazhan Crypts',
    loreHistory: 'The dark, forgotten underbelly of Medivh\'s tower in Deadwind Pass. These crypts hold the restless spirits of those consumed by the tower\'s volatile spatial anomalies.',
    strategyGuide: 'Shadow Resistance and dispels are vital. Dispel "Suffocating Dread" promptly and avoid the central well vortex in the Slumbering Graves.',
    trashMobs: ['Drowned Noble', 'Sin-Eater', 'Crypt Stalker', 'Restless Spirit'],
    associatedQuests: ['Echoes of the Guardian', 'The Upside-Down Sinners', 'Cleansing the Crypts'],
    speedrunStrats: 'Warlocks can use Eye of Kilrogg to scout portcullis lever switches and coordinate fast group gate openings.',
    environmentalHazards: 'Unlit chambers require players to carry physical torches or ignite braziers to avoid being ambushed in darkness.',
    secrets: ['An ancient library grimoire grants the party +10 Shadow Resistance for the duration of the run.', 'A neutral ghost merchant offers unique tailoring patterns.'],
    wings: [
      { name: 'The Well of the Forgotten', level: '58-60 (5 Man)', desc: 'The submerged ossuary vaults.', bosses: ['The Caretaker', 'Amalgam of the Damned'], loot: generateLoot(25, '58-60') },
      { name: 'The Upside-Down Sinners', level: '60 (5 Man)', desc: 'The iconic submerged horror chambers.', bosses: ['The Drowning Terror', 'Master of the Sinners'], loot: generateLoot(30, '60') },
      { name: 'The Reliquary of Secrets', level: '60 (5 Man)', desc: 'Forbidden arcane vaults beneath Deadwind.', bosses: ['The Animated Grimoire', 'The Void-Sealer'], loot: generateLoot(30, '60') }
    ]
  },
  {
    id: 'TimbermawHold',
    name: 'Timbermaw Hold (Burrows)',
    loreHistory: 'Once a sanctuary for uncorrupted furbolgs in northern Kalimdor, demonic corruption from Felwood has seeped into the lower burrows, driving the elder chieftains mad.',
    strategyGuide: 'Cleanse corrupted totems in boss chambers before engaging, or the chieftains gain a stacking berserk enrage.',
    trashMobs: ['Fel-Crazed Furbolg', 'Corrupted Ancient', 'Legion Vanguard', 'Shadow-Weaver'],
    associatedQuests: ['Purging the Hold', 'The Chieftain\'s Fall', 'A Debt Repaid to Timbermaw'],
    speedrunStrats: 'Having Honored standing with Timbermaw Hold allows peaceful passage through the upper tunnels directly to the lower barrows.',
    environmentalHazards: 'Puddles of fel sludge apply a stacking nature damage aura to players standing in them.',
    secrets: ['A hidden path behind an underground waterfall leads to a neutral shaman offering unique nature resistance enchants.'],
    wings: [
      { name: 'The Corrupted Warrens', level: '48-52 (5 Man)', desc: 'Besieged furbolg tunnels.', bosses: ['Chieftain Bloodmaw', 'The Rotting Ancient'], loot: generateLoot(15, '48-52') },
      { name: 'The Fel-Scar Deeps', level: '55-58 (5 Man)', desc: 'Demonic incursion chamber.', bosses: ['Xandros the Fel-Lord', 'The Summoning Portal'], loot: generateLoot(20, '55-58') },
      { name: 'The Ancestral Hollow', level: '60 (5 Man)', desc: 'Defiled sacred burial grounds.', bosses: ['The First Chieftain', 'The Defiler'], loot: generateLoot(30, '60') }
    ]
  },
  {
    id: 'UldumVaults',
    name: 'The Vaults of Uldum',
    loreHistory: 'An ancient Titan research biosphere buried beneath the sands of southern Kalimdor. It houses the Engine of Origination and safeguarding custodians.',
    strategyGuide: 'Interrupt Earthen Constructs during "Stone Barrier" casting, and coordinate dispel timing on Titan Disruption debuffs.',
    trashMobs: ['Earthen Custodian', 'Anubisath Sentinel', 'Tol\'vir Spellweaver'],
    associatedQuests: ['The Secrets of the Makers', 'Disarming the Engine', 'Brann\'s Expedition'],
    speedrunStrats: 'Solving the constellation puzzle console in under 2 minutes opens a shortcut directly to the final inner vault.',
    environmentalHazards: 'Titan security beams sweep across the obsidian corridors; touching them activates defensive sentinels.',
    secrets: ['An ancient titan databank disc reveals deep historical lore about the ordering of Kalimdor.'],
    wings: [
      { name: 'The Maker\'s Terrace', level: '55-58 (5 Man)', desc: 'The titan entrance biosphere.', bosses: ['High-Executor Norgannon', 'Matrix-Lord'], loot: generateLoot(20, '55-58') },
      { name: 'The Obsidian Quarry', level: '58-60 (5 Man)', desc: 'Construct manufacturing chambers.', bosses: ['The Sculptor', 'The Hive-Mind Incursor'], loot: generateLoot(25, '58-60') },
      { name: 'The Engine of Origination', level: '60 (5 Man)', desc: 'The core titan re-origination matrix.', bosses: ['General Rajaxx\'s Vanguard', 'Avatar of the Makers'], loot: generateLoot(35, '60') }
    ]
  },
  {
    id: 'GrimBatol',
    name: 'Grim Batol Tunnels',
    loreHistory: 'The ancient mountain fortress of the Wildhammer dwarves, later occupied by the Dragonmaw Clan to enslave the Red Dragonflight.',
    strategyGuide: 'Kite Molten Elementals away from Dragonmaw handlers; manage fire resistance on forge encounters.',
    trashMobs: ['Dragonmaw Slaver', 'Twilight Corruptor', 'Dark Iron Saboteur', 'Enslaved Whelp'],
    associatedQuests: ['The Legacy of the Wildhammer', 'Freeing the Brood', 'Twilight\'s Hammer Cult'],
    speedrunStrats: 'Engineers can repair a broken minecart to ride through the lower ore tunnels, skipping several trash packs.',
    environmentalHazards: 'Searing magma vents periodically erupt, forcing careful positioning.',
    secrets: ['A secret Wildhammer rune chest requires two players to step on coordinated floor runes.'],
    wings: [
      { name: 'The Dragonmaw Gates', level: '52-55 (5 Man)', desc: 'The fortified mountain gates.', bosses: ['The Siege Master', 'Dragonmaw Proto-Drake'], loot: generateLoot(15, '52-55') },
      { name: 'The Hatcheries', level: '55-58 (5 Man)', desc: 'Red dragonflight breeding caverns.', bosses: ['The Broodmother', 'The Corrupted Whelp-Master'], loot: generateLoot(20, '55-58') },
      { name: 'The Deep Forge', level: '60 (5 Man)', desc: 'Ancient Wildhammer master forges.', bosses: ['The Grand Smith', 'The Anvil of Doom'], loot: generateLoot(30, '60') }
    ]
  },
  {
    id: 'HyjalBarrowDens',
    name: 'The Barrow Dens (Hyjal)',
    loreHistory: 'The sacred hibernation chambers of the druids in Mount Hyjal where the Emerald Nightmare has begun seeping through Nordrassil\'s roots.',
    strategyGuide: 'Dispel "Slumbering Poison" before it puts healers or tanks to sleep for extended durations.',
    trashMobs: ['Nightmare Terror', 'Corrupted Druid', 'Root-Bound Horror', 'Satyr Infiltrator'],
    associatedQuests: ['Waking the Dreamer', 'The Nightmare\'s Grasp', 'Cleansing the Roots'],
    speedrunStrats: 'Druids in the party can use Hibernate on elite Nightmare Terrors to bypass difficult choke pulls.',
    environmentalHazards: 'Pockets of nightmare mist drain mana and cause minor vision distortion.',
    secrets: ['Awakening an ancient sleeping druid grants the party a 1-hour spirit blessing.'],
    wings: [
      { name: 'The Slumbering Halls', level: '58-60 (5 Man)', desc: 'Corrupted sleeping chambers.', bosses: ['The Nightmare Stalker', 'The Waking Terror'], loot: generateLoot(25, '58-60') },
      { name: 'The Roots of Nordrassil', level: '60 (5 Man)', desc: 'Deep roots of the World Tree.', bosses: ['Archimonde\'s Echo', 'The Root-Tender'], loot: generateLoot(30, '60') }
    ]
  },
  {
    id: 'Mazthoril',
    name: 'Mazthoril Deeps',
    loreHistory: 'A cavern system in Winterspring used by the Blue Dragonflight to protect ancient arcane artifacts and volatile leyline energy.',
    strategyGuide: 'High magic burst. Dampen Magic, grounding totems, and spell interrupts on "Arcane Volley" are crucial.',
    trashMobs: ['Arcane Anomaly', 'Blue Dragonkin', 'Spell-Thief', 'Crystalline Golem'],
    associatedQuests: ['The Blue Flight\'s Secret', 'Retrieving the Arcanum', 'Haleh\'s Request'],
    speedrunStrats: 'Spell reflection on Arcane Anomalies causes their burst to shatter nearby construct packs.',
    environmentalHazards: 'Wild magic zones randomly apply minor spell pushback.',
    secrets: ['A locked arcane chest contains a rare enchanting formula decodeable by Mages.'],
    wings: [
      { name: 'The Arcane Vaults', level: '55-60 (5 Man)', desc: 'Blue Dragonflight archive vaults.', bosses: ['The Archivist', 'Haleh\'s Betrayer'], loot: generateLoot(25, '55-60') }
    ]
  },
  {
    id: 'GilneasCity',
    name: 'Gilneas City (Instanced Dungeon)',
    loreHistory: 'The besieged capital city of Gilneas during the worgen outbreak and Forsaken naval blockade.',
    strategyGuide: 'Fight in street choke points and alleyways to prevent fast-moving worgen packs from surrounding the party.',
    trashMobs: ['Feral Worgen', 'Gilnean Royal Guard', 'Crazed Citizen', 'Bloodfang Lurker'],
    associatedQuests: ['The Fall of Gilneas', 'Lord Godfrey\'s Treason', 'Evacuating the Uninfected'],
    speedrunStrats: 'A Rogue can grapple across the cathedral rooftops to drop ladders for party skips.',
    environmentalHazards: 'Burning timbers randomly collapse, causing localized fire zones.',
    secrets: ['Rescuing trapped civilians awards a unique cosmetic Gilnean Tabard.'],
    wings: [
      { name: 'The Greymane District', level: '45-50 (5 Man)', desc: 'The burning city avenues.', bosses: ['Lord Godfrey', 'The Royal Guard'], loot: generateLoot(20, '45-50') }
    ]
  },
  {
    id: 'GnomereganDeeps',
    name: 'Gnomeregan Deeps',
    loreHistory: 'The lowest, most irradiated industrial levels of Gnomeregan occupied by mutated troggs and rogue defense mechs.',
    strategyGuide: 'Cleanse radiation debuffs regularly and utilize environmental decontamination showers.',
    trashMobs: ['Irradiated Trogg', 'Sludge Monstrosity', 'Malfunctioning Cleaner Bot'],
    associatedQuests: ['The Ultimate Cure', 'Thermaplugg\'s Final Echo', 'Data Retrieval'],
    speedrunStrats: 'Using Goblin Jumper Cables on a disabled service lift drops the party straight to the lower vat floor.',
    environmentalHazards: 'Radiation vents periodically expel toxic gas puffs.',
    secrets: ['A rare engineering schematic drops from a hidden stealth gnome engineer in the rafters.'],
    wings: [
      { name: 'The Irradiation Vats', level: '35-45 (5 Man)', desc: 'Toxic sludge and reactor vats.', bosses: ['Viscous Fallout', 'Mekgineer Thermaplugg (Echo)'], loot: generateLoot(20, '35-45') }
    ]
  },
  {
    id: 'ScarletCitadel',
    name: 'The Scarlet Citadel',
    loreHistory: 'The supreme fanatic stronghold of the Scarlet Crusade located in Tyr\'s Hand in Eastern Plaguelands.',
    strategyGuide: 'Chain-cast interrupts on Crusade high clerics to prevent group heals and Holy Novas.',
    trashMobs: ['Scarlet Inquisitor', 'Crusade Commander', 'Holy Zealot', 'Crimson Hound'],
    associatedQuests: ['The Grand Inquisitor', 'Purging the Fanatics', 'The Ashbringer\'s Legacy'],
    speedrunStrats: 'Priests Mind Controlling an Inquisitor can trigger the courtyard gate release mechanism.',
    environmentalHazards: 'Holy ballista fire targets open courtyard areas.',
    secrets: ['A hidden reliquary triggers a lore interaction with Highlord Mograine\'s spectral memory.'],
    wings: [
      { name: 'The Inquisition', level: '50-55 (5 Man)', desc: 'Tyr\'s Hand torture chambers.', bosses: ['Grand Inquisitor Isillien', 'Scarlet Executioner'], loot: generateLoot(20, '50-55') }
    ]
  }
];

const raids = [
  {
    id: 'EmeraldNightmare',
    name: 'The Emerald Nightmare',
    tier: 'Tier 1.5 (10-Man Mini-Raid & 20-Man)',
    desc: 'Entered through the four great dream portals in Ashenvale, Feralas, Duskwood, and the Hinterlands. Tuned for 10-man and 20-man raid teams on a 3-day lockout.',
    loreHistory: 'The four great trees of Azeroth have succumbed to the Emerald Nightmare. Ysera\'s green dragon lieutenants are twisted into corrupted shadows.',
    strategyGuide: 'Manage the Dream Torment mechanic with coordinated dispels, split the raid during multi-portal incursions, and rotate defensive cooldowns during Eranikus\'s Corrupted Breath.',
    trashMobs: ['Nightmare Drake', 'Corrupted Keeper', 'Shadow-Bough Treant', 'Dream-Eater'],
    associatedQuests: ['The Waking Nightmare (Raid)', 'Tears of the Dreamer'],
    speedrunStrats: 'Defeating the dragon lieutenants in rapid succession summons Eranikus for bonus crest turn-ins.',
    environmentalHazards: 'Nightmare Fog shifts across the arena, silencing casters caught in the mist.',
    secrets: ['Collecting Dream Shards grants the raid a temporary nature resistance world buff.'],
    bosses: ['Lethon', 'Emeriss', 'Taerar', 'Ysondre', 'Corrupted Eranikus'],
    loot: generateLoot(45, 'Tier 1.5', 'EmeraldNightmare')
  },
  {
    id: 'GrimBatolRaid',
    name: 'Grim Batol: Mountain of the Dragonmaw',
    tier: 'Tier 2 (40-Man Pinnacle Raid)',
    desc: 'The heart of the mountain where the Dragonmaw Clan enslaves the Red Dragonflight. The premier 40-man pinnacle raid tier on a weekly Tuesday lockout.',
    loreHistory: 'Using the Demon Soul, the orcs have broken the will of Alexstrasza. The 40-man raid navigates the deep forges to destroy the dark artifact and free the Life-Binder.',
    strategyGuide: 'Egg Destruction mechanics demand strict target switches. Manage tank hand-offs during Searing Flurry and position the raid to avoid Alexstrasza\'s captive breath cones.',
    trashMobs: ['Dragonmaw Handler', 'Enslaved Red Drake', 'Twilight Warlock', 'Blackrock Mercenary'],
    associatedQuests: ['The Demon Soul (Raid)', 'Freeing the Queen'],
    speedrunStrats: 'Freeing captive red drakes allows them to assist in clearing elite Dragonmaw defense lines.',
    environmentalHazards: 'Molten Slag rises from the forge floors, requiring coordinated upstairs repositioning.',
    secrets: ['Freeing all captive drakes without casualties triggers a bonus Life-Binder\'s Blessing phase.'],
    bosses: ['Warchief Nek\'rosh', 'The Forgemaster', 'The Demon Soul', 'The Crimson Behemoth'],
    loot: generateLoot(70, 'Tier 2', 'GrimBatolRaid')
  },
  {
    id: 'CrownOfTheDamned',
    name: 'Crown of the Damned (Stratholme Necropolis)',
    tier: 'Tier 2.5 (20-Man Intermediate Raid)',
    desc: 'The massive floating ziggurat hovering above Stratholme. Tuned for 20 players on a 3-day horizontal progression lockout.',
    loreHistory: 'Kel\'Thuzad\'s secondary command ziggurat directing the Scourge\'s northern plague campaigns across Lordaeron.',
    strategyGuide: 'The Phylactery Hunt mechanic forces the off-tanks to contain elite adds while scouts retrieve the phylactery to make the final boss vulnerable.',
    trashMobs: ['Undying Necromancer', 'Flesh Titan', 'Banshee Wailer', 'Death Knight Captain'],
    associatedQuests: ['The Crown Falls (Raid)', 'Retrieving the Phylactery'],
    speedrunStrats: 'Paladins chaining Holy Wrath completely control the Undead Gauntlet corridor.',
    environmentalHazards: 'Frostwyrm Breath freezes players unless warmed by nearby holy fire braziers.',
    secrets: ['Clearing the necropolis triggers Argent Dawn celebrations and temporary vendor discounts in Light\'s Hope.'],
    bosses: ['Highlord Mograine (Echo)', 'The Blood Council', 'Kel\'Thuzad\'s Phylactery-Guard'],
    loot: generateLoot(45, 'Tier 2.5', 'CrownOfTheDamned')
  },
  {
    id: 'KarazhanRaid',
    name: 'Karazhan (The Upper Spire)',
    tier: 'Tier 3 (40-Man Pinnacle Raid)',
    desc: 'The unreleased Vanilla version of Medivh\'s tower. Tuned for 40 players on a weekly Tuesday pinnacle lockout.',
    loreHistory: 'Medivh\'s tower transcends time and space. The upper levels hold spatial rifts where the Burning Legion, anomalous entities, and ghostly lords contend.',
    strategyGuide: 'Coordinate interrupts during Aran\'s Flame Wreath (DO NOT MOVE), execute position swaps on Moroes\'s dinner guests, and manage tank transitions on Prince Malchezaar.',
    trashMobs: ['Spectral Patron', 'Phantom Guardsman', 'Demonic Invader', 'Ethereal Thief'],
    associatedQuests: ['The Master\'s Key (Raid)', 'Closing the Rift'],
    speedrunStrats: 'Invisibility Potions allow organized 40-man teams to skip non-essential trash corridors.',
    environmentalHazards: 'Spatial rift turbulence causes minor gravity shifts on the upper library terraces.',
    secrets: ['Clearing the raid in under 90 minutes summons Medivh\'s Echo for bonus legendary crest drops.'],
    bosses: ['Attumen the Huntsman', 'Moroes', 'The Curator', 'Shade of Aran', 'Prince Malchezaar', 'Medivh\'s Echo'],
    loot: generateLoot(80, 'Tier 3', 'KarazhanRaid')
  },
  {
    id: 'DragonIslesRaid',
    name: 'Temple of the Dragon Isles',
    tier: 'Tier 3.5 (40-Man Pinnacle Raid)',
    desc: 'The mythical pre-Titan island temple north of Lordaeron. The absolute pinnacle 40-man raid challenge in Classic+.',
    loreHistory: 'An impossibly ancient pre-Titan temple where the Old Gods first sought to corrupt the proto-dragon broods.',
    strategyGuide: 'Demands absolute raid coordination: Ley-Line beam alignment to remove boss immunities, strict tank swap rotations on Proto-Behemoths, and tight enrage DPS checks.',
    trashMobs: ['Faceless Corruptor', 'Devolved Proto-Drake', 'Tentacle Horror', 'Mind-Flayer'],
    associatedQuests: ['The Final Nightmare (Raid)', 'Whispers in the Dark'],
    speedrunStrats: 'Time Dilation zones temporarily accelerate movement and casting for well-positioned raid groups.',
    environmentalHazards: 'Void rifts collapse floor sections, demanding adaptive raid positioning.',
    secrets: ['Extremely rare Proto-Drake ground mount drops from the final Old God Avatar.'],
    bosses: ['The Aspect Council', 'The Faceless General', 'Avatar of the Old God'],
    loot: generateLoot(80, 'Tier 3.5', 'DragonIslesRaid')
  }
];

[...dungeons, ...raids].forEach(instance => {
  if (instance.wings) {
    instance.wings.forEach(wing => {
      if (wing.loot && wing.bosses && wing.bosses.length > 0) {
        wing.loot.forEach(item => {
          if (!item.source) item.source = `Dropped by: ${wing.bosses[Math.floor(Math.random() * wing.bosses.length)]}`;
        });
      }
    });
  } else if (instance.loot && instance.bosses && instance.bosses.length > 0) {
    instance.loot.forEach(item => {
      if (!item.source) item.source = `Dropped by: ${instance.bosses[Math.floor(Math.random() * instance.bosses.length)]}`;
    });
  }
});

const tsFile = `export const PVE_CATS = {
  DUNGEONS: 'The New Dungeons (Winged Hubs)',
  RAIDS: 'Dedicated Raid Tiers (10 / 20 / 40 Man Formats)'
};

export const pveData = {
  [PVE_CATS.DUNGEONS]: ${JSON.stringify(dungeons, null, 2)},
  [PVE_CATS.RAIDS]: ${JSON.stringify(raids, null, 2)}
};
`;

fs.writeFileSync('./src/data/dungeons.ts', tsFile);
console.log('Successfully generated dungeons.ts with authentic 1.12 stat budgets and dedicated raid tier formats.');
