const fs = require('fs');

function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

const roleEffects = {
  Tank: [
    'Equip: Increases your chance to block attacks with a shield by 2%.',
    'Equip: Your attacks have a chance to sunder the target\'s armor.',
    'Equip: Increases your defense rating by 15.',
    'Use: Absorbs 500 magic damage for 10 sec.',
    'Equip: When struck in melee, inflicts 15 Fire damage to the attacker.',
    'Equip: Increases threat generated by all attacks by 5%.',
    'Chance on hit: Grants a shield absorbing 1500 damage for 8 sec.'
  ],
  PhysicalDPS: [
    'Equip: +1% Critical Strike.',
    'Equip: +1% Hit chance.',
    'Equip: +20 Attack Power.',
    'Equip: Your attacks have a chance to sunder the target\'s armor.',
    'Chance on hit: Drains 50 life from the target and gives it to the wielder.',
    'Equip: Armor Penetration increased by 30.',
    'Chance on hit: Increases melee haste by 10% for 10 sec.'
  ],
  SpellDPS: [
    'Equip: Increases spell damage by up to 15.',
    'Equip: +1% Spell Critical Strike.',
    'Equip: +1% Spell Hit chance.',
    'Chance on hit: Blasts the target for 150 Nature damage.',
    'Use: Encases the caster in a block of ice, absorbing 2000 damage but rooting them for 5 sec.',
    'Equip: Reduces the cast time of your next spell by 0.5 sec after a critical strike.',
    'Chance on hit: Restores 100 mana and increases Spell Power by 50 for 10 sec.'
  ],
  Healer: [
    'Equip: Increases healing done by up to 25.',
    'Equip: Restores 4 mana per 5 seconds.',
    'Equip: Increases the critical effect of your holy spells by 2%.',
    'Use: Instantly heals the target for 500, but silences you for 3 sec.',
    'Equip: Your healing spells have a 2% chance to restore 300 mana.',
    'Equip: Your direct heals grant the target a 50 damage absorption shield.',
    'Use: Restores 1500 mana over 10 seconds. (5 Min Cooldown)'
  ],
  General: [
    'Use: Transforms the caster into a spectral wolf, increasing movement speed by 40% for 10 sec.',
    'Chance on hit: Summons a skeletal servant to fight by your side for 1 minute.',
    'Equip: Increases your resistance to all schools of magic by 10.',
    'Use: Teleports the caster 15 yards forward.',
    'Chance on hit: Blinds the target, disorienting them for 3 sec.'
  ]
};

const slotNames = {
  Head: ['Helm', 'Crown', 'Circlet', 'Cowl', 'Mask'],
  Shoulder: ['Spaulders', 'Mantle', 'Pauldrons', 'Epaulets', 'Amice'],
  Chest: ['Breastplate', 'Robes', 'Vest', 'Harness', 'Tunic'],
  Wrist: ['Bracers', 'Wristguards', 'Bindings', 'Cuffs', 'Vambraces'],
  Hands: ['Gauntlets', 'Gloves', 'Handguards', 'Grips', 'Mitts'],
  Waist: ['Belt', 'Girdle', 'Sash', 'Waistguard', 'Cord'],
  Legs: ['Legguards', 'Pants', 'Kilt', 'Greaves', 'Leggings'],
  Feet: ['Sabatons', 'Boots', 'Treads', 'Footpads', 'Slippers'],
  Finger: ['Band', 'Signet', 'Loop', 'Ring', 'Seal'],
  Trinket: ['Talisman', 'Charm', 'Medallion', 'Brooch', 'Relic'],
  Neck: ['Amulet', 'Pendant', 'Necklace', 'Choker', 'Collar'],
  Weapon: ['Greatsword', 'Blade', 'Staff', 'Gavel', 'Axe', 'Dagger', 'Bow'],
  Shield: ['Shield', 'Bulwark', 'Defender', 'Aegis', 'Buckler']
};

const prefixes = ['Venerable', 'Corrupted', 'Shimmering', 'Blood-Forged', 'Ancient', 'Void-Touched', 'Shadow', 'Holy', 'Ethereal', 'Savage'];
const suffixes = ['of the Crimson King', 'of the Unseen', 'of Eternal Slumber', 'of the Archmage', 'of Shattered Souls', 'of the Forgotten', 'of the Void', 'of Bloodletting', 'of the Deep', 'of the Betrayer'];

const specProfiles = {
  PlateTank: { role: 'Tank', armor: 'Plate', validWeapons: ['Sword', 'Mace', 'Axe'], primary: ['Stamina', 'Strength'], secondary: ['Defense', 'Dodge', 'Parry', 'Agility'] },
  PlateDPS: { role: 'PhysicalDPS', armor: 'Plate', validWeapons: ['Sword', 'Mace', 'Axe'], primary: ['Strength', 'Stamina'], secondary: ['Agility', 'Attack Power', 'Hit', 'Crit'] },
  PlateHealer: { role: 'Healer', armor: 'Plate', validWeapons: ['Mace', 'Sword'], primary: ['Intellect', 'Stamina'], secondary: ['Healing Power', 'MP5', 'Spell Crit'] },
  MailDPS: { role: 'PhysicalDPS', armor: 'Mail', validWeapons: ['Axe', 'Mace', 'Bow'], primary: ['Agility', 'Stamina'], secondary: ['Attack Power', 'Intellect', 'Crit', 'Hit'] },
  MailCaster: { role: 'SpellDPS', armor: 'Mail', validWeapons: ['Mace', 'Dagger'], primary: ['Intellect', 'Stamina'], secondary: ['Spell Damage', 'Spell Crit', 'Spell Hit'] },
  MailHealer: { role: 'Healer', armor: 'Mail', validWeapons: ['Mace'], primary: ['Intellect', 'Stamina'], secondary: ['Healing Power', 'MP5', 'Spell Crit'] },
  LeatherTank: { role: 'Tank', armor: 'Leather', validWeapons: ['Staff', 'Mace'], primary: ['Stamina', 'Agility'], secondary: ['Dodge', 'Armor', 'Strength', 'Defense'] },
  LeatherDPS: { role: 'PhysicalDPS', armor: 'Leather', validWeapons: ['Dagger', 'Sword', 'Mace'], primary: ['Agility', 'Stamina'], secondary: ['Strength', 'Attack Power', 'Hit', 'Crit'] },
  LeatherCaster: { role: 'SpellDPS', armor: 'Leather', validWeapons: ['Staff', 'Mace'], primary: ['Intellect', 'Stamina'], secondary: ['Spell Damage', 'Spell Crit', 'Spirit', 'MP5'] },
  LeatherHealer: { role: 'Healer', armor: 'Leather', validWeapons: ['Staff', 'Mace'], primary: ['Intellect', 'Spirit', 'Stamina'], secondary: ['Healing Power', 'MP5'] },
  ClothCaster: { role: 'SpellDPS', armor: 'Cloth', validWeapons: ['Staff', 'Dagger'], primary: ['Intellect', 'Stamina'], secondary: ['Spell Damage', 'Spell Crit', 'Spell Hit', 'Spirit'] },
  ClothHealer: { role: 'Healer', armor: 'Cloth', validWeapons: ['Staff', 'Mace'], primary: ['Intellect', 'Spirit', 'Stamina'], secondary: ['Healing Power', 'MP5'] }
};


const loreThemes = {
  EmeraldNightmare: {
    prefixes: ['Dream-Scarred', 'Nightmare-Forged', 'Corrupted', 'Slumbering', 'Emerald'],
    suffixes: ['of the Waking Dream', 'of Ysera\'s Fall', 'of the Deep Slumber', 'of the Nightmare']
  },
  GrimBatolRaid: {
    prefixes: ['Dragonmaw', 'Red Scale', 'Enslaved', 'Mountain-Forged', 'Searing'],
    suffixes: ['of the Demon Soul', 'of the Red Flight', 'of the Queen\'s Captivity', 'of the Forge']
  },
  CrownOfTheDamned: {
    prefixes: ['Necrotic', 'Plague-Ridden', 'Scourge-Forged', 'Cursed', 'Death-Bound'],
    suffixes: ['of the Lich King', 'of the Ziggurat', 'of the Phylactery', 'of Naxxramas']
  },
  KarazhanRaid: {
    prefixes: ['Astral', 'Medivh\'s', 'Ethereal', 'Rift-Touched', 'Timeless'],
    suffixes: ['of the Guardian\'s Fall', 'of the Rift', 'of the Ivory Tower', 'of the Nether']
  },
  DragonIslesRaid: {
    prefixes: ['Faceless', 'Tentacled', 'Void-Touched', 'Maddening', 'Whispering'],
    suffixes: ['of the Black Empire', 'of the Insane', 'of the Old Gods', 'of the Deep Void']
  }
};

const epicFlavorTexts = [
  "The blade sings with the blood of a thousand forgotten souls.",
  "Forged in the heart of a dying star.",
  "It throbs with a dark, rhythmic pulse.",
  "Heirs to the throne of Lordaeron wept upon its creation.",
  "Light bends strangely around its edges.",
  "A faint whispering can be heard when held to the ear.",
  "Imbued with the furious essence of the Firelands.",
  "Legend says it was once wielded by a titan watcher."
];

function generateLoot(count, levelStr = '60', theme = null, bosses = []) {
  let reqLevel = 60;
  let iLvl = 60;
  let tierLevel = 0;

  if (levelStr.includes('Tier 1.5')) { iLvl = 70; tierLevel = 1; }
  else if (levelStr.includes('Tier 2.5')) { iLvl = 81; tierLevel = 3; }
  else if (levelStr.includes('Tier 2')) { iLvl = 76; tierLevel = 2; }
  else if (levelStr.includes('Tier 3.5')) { iLvl = 92; tierLevel = 5; }
  else if (levelStr.includes('Tier 3')) { iLvl = 86; tierLevel = 4; }
  else if (levelStr.includes('-')) {
    reqLevel = parseInt(levelStr.split('-')[1], 10);
    iLvl = reqLevel;
  } else {
    reqLevel = parseInt(levelStr, 10);
    iLvl = reqLevel;
  }

  const loot = [];
  
  let epicChance = 0.05;
  if (iLvl >= 70 || levelStr.includes('Tier')) {
    epicChance = 1.0;
  } else if (reqLevel >= 55) {
    epicChance = 0.15;
  }

  for (let i = 0; i < count; i++) {
    const isEpic = Math.random() < epicChance;
    const rarity = isEpic ? 'Epic' : 'Rare';
    
    const specKeys = Object.keys(specProfiles);
    const specName = getRandom(specKeys);
    const spec = specProfiles[specName];
    
    const isWeapon = Math.random() > 0.8;
    const isJewelry = Math.random() > 0.7 && !isWeapon;
    const isShield = (spec.role === 'Tank' || spec.role === 'Healer') && Math.random() > 0.8;
    
    let type = '';
    let slot = '';
    let noun = '';

    if (isWeapon) {
      type = getRandom(spec.validWeapons);
      if (type === 'Staff' || type === 'Bow') {
        slot = 'Two-Hand';
      } else {
        slot = getRandom(['Main Hand', 'One-Hand']);
      }
      noun = getRandom(slotNames.Weapon);
    } else if (isShield) {
      type = 'Shield';
      slot = 'Off Hand';
      noun = getRandom(slotNames.Shield);
    } else if (isJewelry) {
      type = getRandom(['Ring', 'Trinket', 'Necklace']);
      if (type === 'Ring') slot = 'Finger';
      else if (type === 'Necklace') slot = 'Neck';
      else slot = 'Trinket';
      noun = getRandom(slotNames[slot]);
    } else {
      type = spec.armor;
      slot = getRandom(['Head', 'Shoulder', 'Chest', 'Wrist', 'Hands', 'Waist', 'Legs', 'Feet']);
      noun = getRandom(slotNames[slot]);
    }

    
    let pList = prefixes;
    let sList = suffixes;
    if (theme && loreThemes[theme]) {
      pList = loreThemes[theme].prefixes;
      sList = loreThemes[theme].suffixes;
    }
    const name = `${getRandom(pList)} ${noun} ${getRandom(sList)}`;


    const stats = [];
    if (type !== 'Trinket') {
      const mainStat = getRandom(spec.primary);
      const statBudget = Math.floor(iLvl * 0.5) + (isEpic ? 10 : 0);
      stats.push(`+${Math.floor(statBudget * 0.6)} ${mainStat}`);
      
      let secondaryChance = 0.4;
      if (tierLevel >= 2) secondaryChance = 1.0; 
      
      if (Math.random() < secondaryChance) {
        const secStat = getRandom(spec.secondary);
        stats.push(`+${Math.floor(statBudget * 0.4)} ${secStat}`);
      }

      if (tierLevel >= 4 || (tierLevel >= 2 && Math.random() < 0.4)) {
        const secStat2 = getRandom(spec.secondary);
        if (!stats.some(s => s.includes(secStat2))) {
           stats.push(`+${Math.floor(statBudget * 0.25)} ${secStat2}`);
        }
      }
    }

    let effect = '';
    
    let baseProcChance = isEpic ? 0.20 : 0.05;
    let procChance = baseProcChance + (tierLevel * 0.15);
    
    if (type === 'Trinket' || Math.random() < procChance) {
      if (Math.random() > 0.3 && roleEffects[spec.role]) {
        effect = getRandom(roleEffects[spec.role]);
      } else {
        effect = getRandom(roleEffects.General);
      }
    }

    let flavorText = undefined;
    if (isEpic && Math.random() > 0.5) {
      flavorText = getRandom(epicFlavorTexts);
    }
    
    let source = undefined;
    if (bosses && bosses.length > 0) {
      const boss = getRandom(bosses);
      source = `Dropped by: ${boss.name || boss}`;
    }

    loot.push({
      name,
      rarity,
      bindType: 'Binds when picked up',
      slot,
      type,
      stats,
      effect,
      flavorText,
      source,
      requiresLevel: reqLevel,
      sellPrice: `${Math.floor(Math.max(0, (iLvl / 10) * (isEpic ? 1.5 : 1) - 1 + Math.random() * 2))}g ${Math.floor(Math.random() * 99)}s`
    });
  }
  return loot;
}

const dungeons = [
  {
    id: 'StormwindVault',
    name: 'Stormwind Vaults',
    loreHistory: 'Hidden deep beneath the canals of Stormwind, this maximum-security prison houses the most dangerous criminals, defected nobles, and dark magic practitioners the kingdom has ever captured.',
    strategyGuide: 'Crowd control is mandatory. The tight corridors mean pulling multiple packs is fatal. Utilize corner pulls to break line of sight on the Defias marksmen.',
    trashMobs: ['Corrupt Noble Guard', 'Vault Warden', 'Defias Infiltrator', 'Bound Voidwalker'],
    associatedQuests: ['The King\'s Justice (Dungeon)', 'Missing Diplomat: The Interrogation', 'A Noble\'s Treachery'],
    speedrunStrats: 'A Rogue can pick the lock to the old sewer grates, bypassing the entire first wing and going straight to Dextren Ward.',
    environmentalHazards: 'Triggering the alarm bells will cause infinite waves of guards to spawn until a player channels on the bell for 10 seconds to disable it.',
    secrets: ['A hidden tunnel behind a loose brick leads back to the Stockades.', 'Pickpocketing the Head Jailer yields the "Sewer Key".'],
    wings: [
      { name: 'The Upper Brig', level: '25-30', desc: 'The holding cells.', bosses: ['Warden Thelwater', 'Targorr the Dread'], loot: generateLoot(10, '25-30') },
      { name: 'The Deep Cellblocks', level: '45-50', desc: 'Where the true enemies are kept.', bosses: ['High Cultist Zenn', 'Dextren Ward'], loot: generateLoot(15, '45-50') },
      { name: 'The Interrogation Levels', level: '55-60', desc: 'A descent into madness.', bosses: ['Interrogator Vishas', 'The Flesh-Shaper'], loot: generateLoot(25, '55-60') }
    ]
  },
  {
    id: 'KarazhanCrypts',
    name: 'Karazhan Crypts',
    loreHistory: 'The dark, forgotten underbelly of Medivh\'s tower. These crypts hold the restless souls of those who died during the tower\'s chaotic construction and the subsequent magical fallout.',
    strategyGuide: 'Shadow and Frost resistance are incredibly valuable here. Healers must dispel the "Suffocating Dread" debuff immediately.',
    trashMobs: ['Drowned Noble', 'Sin-Eater', 'Crypt Stalker', 'Restless Spirit'],
    associatedQuests: ['Echoes of the Guardian', 'The Upside-Down Sinners', 'Cleansing the Crypts'],
    speedrunStrats: 'Warlocks can use Eye of Kilrogg to trigger the portcullis switches remotely, saving minutes of walking.',
    environmentalHazards: 'In the Upside-Down Sinners wing, the water level slowly rises during boss encounters, threatening to drown the entire party.',
    secrets: ['A hidden tome grants the party a permanent +10 Shadow Resistance buff for the dungeon.', 'A neutral ghost vendor sells unique tailoring patterns.'],
    wings: [
      { name: 'The Well of the Forgotten', level: '58-60', desc: 'Mass graves.', bosses: ['The Caretaker', 'Amalgam of the Damned'], loot: generateLoot(25, '58-60') },
      { name: 'The Upside-Down Sinners', level: '60', desc: 'Underwater terror.', bosses: ['The Drowning Terror', 'Master of the Sinners'], loot: generateLoot(30, '60') },
      { name: 'The Reliquary of Secrets', level: '60', desc: 'Forbidden artifacts.', bosses: ['The Animated Grimoire', 'The Void-Sealer'], loot: generateLoot(30, '60') }
    ]
  },
  {
    id: 'TimbermawHold',
    name: 'Timbermaw Hold',
    loreHistory: 'Once a sanctuary for the uncorrupted Timbermaw furbolgs, deep elements of the Legion\'s taint have seeped into the lower burrows, driving the chieftains mad.',
    strategyGuide: 'Cleanse the corrupted totems scattered around the boss rooms before pulling, or the bosses will enrage at 30% health.',
    trashMobs: ['Fel-crazed Furbolg', 'Corrupted Ancient', 'Legion Vanguard', 'Shadow-weaver'],
    associatedQuests: ['Purging the Hold', 'The Chieftain\'s Fall', 'A Debt Repaid'],
    speedrunStrats: 'Having Exalted reputation with Timbermaw Hold allows you to skip the first two bosses entirely by speaking to a friendly NPC.',
    environmentalHazards: 'Puddles of fel-sludge slow movement speed and apply a stacking nature damage DoT.',
    secrets: ['A hidden path behind a waterfall leads to a neutral vendor selling unique enchantments for Nature Resistance.'],
    wings: [
      { name: 'The Corrupted Warrens', level: '48-52', desc: 'Besieged hold.', bosses: ['Chieftain Bloodmaw', 'The Rotting Ancient'], loot: generateLoot(15, '48-52') },
      { name: 'The Fel-Scar', level: '55-58', desc: 'Demonic incursion.', bosses: ['Xandros the Fel-Lord', 'The Summoning Portal'], loot: generateLoot(20, '55-58') },
      { name: 'The Ancestral Hollow', level: '60', desc: 'Defiled burial grounds.', bosses: ['The First Chieftain', 'The Defiler'], loot: generateLoot(30, '60') }
    ]
  },
  {
    id: 'UldumVaults',
    name: 'The Vaults of Uldum',
    loreHistory: 'An ancient Titan research facility buried beneath the sands of Tanaris. It houses the Engine of Origination, a device capable of resetting all life on Azeroth.',
    strategyGuide: 'Physical damage dealers must interrupt the Earthen Constructs\' "Stone Skin" cast, or they become completely immune to physical attacks.',
    trashMobs: ['Earthen Custodian', 'Anubisath Sentinel', 'Tol\'vir Spellweaver'],
    associatedQuests: ['The Secrets of the Makers', 'Disarming the Engine', 'Brann\'s Expedition'],
    speedrunStrats: 'Bypassing the primary security grid by solving the constellation puzzle in under 2 minutes opens a shortcut directly to the final boss.',
    environmentalHazards: 'Lasers sweep the corridors. Touching them instantly kills the player and alerts nearby trash.',
    secrets: ['An archaeology puzzle in the Maker\'s Terrace rewards a unique epic mount.', 'Hidden Titan discs reveal lore about the Old Gods.'],
    wings: [
      { name: 'The Maker\'s Terrace', level: '55-58', desc: 'Titan facility.', bosses: ['High-Executor Norgannon', 'Matrix-Lord'], loot: generateLoot(20, '55-58') },
      { name: 'The Obsidian Quarry', level: '58-60', desc: 'Construct manufacturing.', bosses: ['The Sculptor', 'The Hive-Mind Incursor'], loot: generateLoot(25, '58-60') },
      { name: 'The Engine of Origination', level: '60', desc: 'The core.', bosses: ['General Rajaxx\'s Vanguard', 'Avatar of the Makers'], loot: generateLoot(40, '60') }
    ]
  },
  {
    id: 'GrimBatol',
    name: 'Grim Batol Tunnels',
    loreHistory: 'The ancient mountain fortress of the Wildhammer dwarves, later claimed by the Dragonmaw Orcs to enslave the Red Dragonflight. Now, Twilight Cultists and Dark Irons fight for control.',
    strategyGuide: 'Kite the Molten Elementals away from the Twilight Cultists; if they merge, they form an unstoppable boss-level mob.',
    trashMobs: ['Dragonmaw Slaver', 'Twilight Corruptor', 'Dark Iron Saboteur', 'Enslaved Whelp'],
    associatedQuests: ['The Legacy of the Wildhammer', 'Freeing the Brood', 'Twilight\'s Hammer Cult'],
    speedrunStrats: 'Engineers can repair a broken minecart to ride it past the entire second wing\'s trash packs.',
    environmentalHazards: 'Searing magma vents periodically erupt, dealing massive fire damage and launching players into the air.',
    secrets: ['A secret Wildhammer stash requires all 5 players to stand on pressure plates simultaneously.'],
    wings: [
      { name: 'The Dragonmaw Gates', level: '52-55', desc: 'Fortified entrance.', bosses: ['The Siege Master', 'Dragonmaw Proto-Drake'], loot: generateLoot(15, '52-55') },
      { name: 'The Hatcheries', level: '55-58', desc: 'Red Dragonflight breeding.', bosses: ['The Broodmother', 'The Corrupted Whelp-Master'], loot: generateLoot(20, '55-58') },
      { name: 'The Deep Forge', level: '60', desc: 'Wildhammer forges.', bosses: ['The Grand Smith', 'The Anvil of Doom'], loot: generateLoot(30, '60') }
    ]
  },
  {
    id: 'HyjalBarrowDens',
    name: 'The Barrow Dens',
    loreHistory: 'The sacred underground hibernation chambers of the druids in Mount Hyjal. The Emerald Nightmare has begun seeping through the roots of Nordrassil, corrupting the sleeping druids.',
    strategyGuide: 'Dispel "Slumbering Poison" immediately. If it expires, the player is put to sleep for 30 seconds and cannot be woken by damage.',
    trashMobs: ['Nightmare Terror', 'Corrupted Druid', 'Root-Bound Horror', 'Satyr Infiltrator'],
    associatedQuests: ['Waking the Dreamer', 'The Nightmare\'s Grasp', 'Cleansing the Roots'],
    speedrunStrats: 'Druids in the party can use Hibernate on the elite Nightmare Terrors to easily bypass the hardest trash packs.',
    environmentalHazards: 'Pockets of Nightmare gas disorient players and slowly drain mana.',
    secrets: ['Awakening a specific druid grants the party the "Blessing of Cenarius", increasing all stats by 5%.'],
    wings: [
      { name: 'The Slumbering Halls', level: '58-60', desc: 'Nightmare.', bosses: ['The Nightmare Stalker', 'The Waking Terror'], loot: generateLoot(25, '58-60') },
      { name: 'The Roots of Nordrassil', level: '60', desc: 'Deep caverns.', bosses: ['Archimonde\'s Echo', 'The Root-Tender'], loot: generateLoot(30, '60') }
    ]
  },
  {
    id: 'Mazthoril',
    name: 'Mazthoril Deeps',
    loreHistory: 'A sprawling cavern system in Winterspring used by the Blue Dragonflight to horde and protect arcane artifacts and dangerous magic.',
    strategyGuide: 'Magic damage is incredibly high here. Mages with Dampen Magic are extremely useful. Interrupt the "Arcane Volley" at all costs.',
    trashMobs: ['Arcane Anomaly', 'Blue Dragonkin', 'Spell-Thief', 'Crystalline Golem'],
    associatedQuests: ['The Blue Flight\'s Secret', 'Retrieving the Arcanum', 'Haleh\'s Request'],
    speedrunStrats: 'Reflecting the Arcane Anomalies\' spells back at them causes them to instantly shatter.',
    environmentalHazards: 'Wild magic zones randomly silence or disarm players standing in them.',
    secrets: ['A locked arcane chest contains a rare enchant recipe, but requires a Mage to decode the runes.'],
    wings: [
      { name: 'The Arcane Vaults', level: '55-60', desc: 'Blue Dragonflight archive.', bosses: ['The Archivist', 'Haleh\'s Betrayer'], loot: generateLoot(25, '55-60') }
    ]
  },
  {
    id: 'GilneasCity',
    name: 'Gilneas City (Instanced)',
    loreHistory: 'The capital city of Gilneas is in flames. A massive worgen outbreak has overrun the streets, and Lord Godfrey has initiated a brutal martial law lockdown.',
    strategyGuide: 'The streets are packed with fast-moving Worgen. Use the city\'s cannons to break through barricades and thin out the hordes.',
    trashMobs: ['Feral Worgen', 'Gilnean Royal Guard', 'Crazed Citizen', 'Bloodfang Lurker'],
    associatedQuests: ['The Fall of Gilneas', 'Lord Godfrey\'s Treason', 'Evacuating the Uninfected'],
    speedrunStrats: 'A rogue can stealth through the rooftops, dropping rope ladders down for the rest of the party to skip the street fighting.',
    environmentalHazards: 'Burning buildings randomly collapse, causing massive AoE fire damage.',
    secrets: ['Saving a hidden group of civilians rewards a unique Gilnean tabard.'],
    wings: [
      { name: 'The Greymane District', level: '45-50', desc: 'Burning capital.', bosses: ['Lord Godfrey', 'The Royal Guard'], loot: generateLoot(20, '45-50') }
    ]
  },
  {
    id: 'GnomereganDeeps',
    name: 'Gnomeregan Deeps',
    loreHistory: 'The lowest, most irradiated levels of the fallen gnome capital. The troggs here have mutated into horrific, glowing monstrosities.',
    strategyGuide: 'Radiation poisoning requires constant cleansing. Do not step in the green sludge.',
    trashMobs: ['Irradiated Trogg', 'Sludge Monstrosity', 'Malfunctioning Cleaner Bot'],
    associatedQuests: ['The Ultimate Cure', 'Thermaplugg\'s Final Echo', 'Data Retrieval'],
    speedrunStrats: 'Using a Goblin Jumper Cable on a broken elevator immediately drops the party to the final boss room.',
    environmentalHazards: 'Radiation vents periodically expel toxic gas. Players must use decontamination showers scattered throughout the instance.',
    secrets: ['A rare engineering schematic drops from a hidden, un-targetable gnome ninja if you reveal him with a flare.'],
    wings: [
      { name: 'The Irradiation Vats', level: '35-45', desc: 'Pure toxic sludge.', bosses: ['Viscous Fallout', 'Mekgineer Thermaplugg (Echo)'], loot: generateLoot(20, '35-45') }
    ]
  },
  {
    id: 'ScarletCitadel',
    name: 'The Scarlet Citadel',
    loreHistory: 'The ultimate fanatic stronghold located in Tyr\'s Hand. The highest ranking members of the Scarlet Crusade coordinate their holy war from within these heavily fortified walls.',
    strategyGuide: 'The Crusade healers must be CC\'d or killed instantly. They will chain-heal each other and cast massive holy novas.',
    trashMobs: ['Scarlet Inquisitor', 'Crusade Commander', 'Holy Zealot', 'Crimson Hound'],
    associatedQuests: ['The Grand Inquisitor', 'Purging the Fanatics', 'The Ashbringer\'s Legacy'],
    speedrunStrats: 'Mind Controlling a Scarlet Inquisitor allows you to use their "Open Gates" spell, bypassing the massive courtyard fight.',
    environmentalHazards: 'Holy fire rains from the parapets during the outdoor sections. Players must move between covered corridors.',
    secrets: ['Finding the true Ashbringer\'s hidden reliquary triggers an entirely unique roleplay event with Highlord Mograine\'s ghost.'],
    wings: [
      { name: 'The Inquisition', level: '50-55', desc: 'Tyr\'s Hand torture chambers.', bosses: ['Grand Inquisitor Isillien', 'Scarlet Executioner'], loot: generateLoot(20, '50-55') }
    ]
  }
];

const raids = [
  {
    id: 'EmeraldNightmare',
    name: 'The Emerald Nightmare',
    tier: 'Tier 1.5 (20 Man)',
    desc: 'Entered through the four great portals in Ashenvale, Feralas, Duskwood, and the Hinterlands. A sprawling, non-linear raid.',
    loreHistory: 'The four great trees of Azeroth have fully succumbed to the Nightmare. Ysera\'s greatest lieutenants have been twisted into horrific shadows of their former selves.',
    strategyGuide: 'A non-linear raid where the raid must frequently split into 2 or 4 groups to tackle Dream Portals simultaneously. The Sanity Mechanic requires constant monitoring; if a player drops to 0 sanity, they become permanently hostile.',
    trashMobs: ['Nightmare Drake', 'Corrupted Keeper', 'Shadow-Bough Treant', 'Dream-Eater'],
    associatedQuests: ['The Waking Nightmare (Raid)', 'Tears of the Dreamer'],
    speedrunStrats: 'Defeating all four dragons within 45 minutes triggers a secret hard-mode encounter against Eranikus.',
    environmentalHazards: 'The Nightmare Fog constantly shifts. Silencing casters caught within it.',
    secrets: ['Collecting the hidden Dream Fragments grants the raid the Waking Buff, a 24-hour world buff called "Clarity of the Dream".'],
    bosses: ['Lethon', 'Emeriss', 'Taerar', 'Ysondre', 'Corrupted Ysera'],
    loot: generateLoot(50, 'Tier 1.5', 'EmeraldNightmare')
  },
  {
    id: 'GrimBatolRaid',
    name: 'Grim Batol',
    tier: 'Tier 2 (40 Man)',
    desc: 'The heart of the mountain where the Dragonmaw Clan enslaves the Red Dragonflight.',
    loreHistory: 'Using the Demon Soul, the orcs have broken the will of Alexstrasza. The raid must navigate the mountain to destroy the artifact and free the Life-Binder.',
    strategyGuide: 'The Red Dragonflight is enslaved; killing dragons destroys their loot and reduces your end-of-raid rewards. The raid must navigate Egg Destruction mechanics, destroying twilight eggs before they hatch.',
    trashMobs: ['Dragonmaw Handler', 'Enslaved Red Drake', 'Twilight Warlock', 'Blackrock Mercenary'],
    associatedQuests: ['The Demon Soul (Raid)', 'Freeing the Queen'],
    speedrunStrats: 'During the Drake Riding phase, players can mount Red Drakes to siege the fortress and skip massive trash packs.',
    environmentalHazards: 'Molten Slag constantly rises from the forge, forcing the raid to move upstairs throughout the encounters.',
    secrets: ['Alexstrasza\'s Intervention is a secret NPC assist phase that triggers if no red drakes are killed, granting the raid massive haste.'],
    bosses: ['Warchief Nek\'rosh', 'The Forgemaster', 'The Demon Soul', 'The Crimson Behemoth'],
    loot: generateLoot(80, 'Tier 2', 'GrimBatolRaid')
  },
  {
    id: 'CrownOfTheDamned',
    name: 'Crown of the Damned (Stratholme Necropolis)',
    tier: 'Tier 2.5 (20 Man)',
    desc: 'The massive floating ziggurat hovering above Stratholme.',
    loreHistory: 'Before Naxxramas arrived, Kel\'Thuzad tested his aerial necropolises. This is the command center of the Scourge\'s Lordaeron operations.',
    strategyGuide: 'The Phylactery Hunt mechanic forces the raid to locate the hidden phylactery in a random room each week to permanently kill the final boss. Mind Control mechanics require the off-tank to react instantly when the main tank is taken.',
    trashMobs: ['Undying Necromancer', 'Flesh Titan', 'Banshee Wailer', 'Death Knight Captain'],
    associatedQuests: ['The Crown Falls (Raid)', 'Retrieving the Phylactery'],
    speedrunStrats: 'Paladins using Holy Wrath can completely lock down the undead Gauntlet, saving over 10 minutes.',
    environmentalHazards: 'Frostwyrm Breath acts as a raid-wide freeze that must be thawed by standing near active fire braziers.',
    secrets: ['Clearing the raid triggers minor Scourge Invasions in capital cities for the next 2 hours.', 'Bone Storm is a brutal melee-punishing mechanic requiring exact positioning.'],
    bosses: ['Highlord Mograine', 'The Blood Council', 'Kel\'Thuzad\'s Phylactery-Guard'],
    loot: generateLoot(50, 'Tier 2.5', 'CrownOfTheDamned')
  },
  {
    id: 'KarazhanRaid',
    name: 'Karazhan (Upper Tower)',
    tier: 'Tier 3 (40 Man)',
    desc: 'The unreleased Vanilla version of Karazhan, balanced for 40 players.',
    loreHistory: 'Medivh\'s tower transcends time and space. The upper levels are caught in a dimensional rift where the Burning Legion and anomalous entities fight for control.',
    strategyGuide: 'The Chess Event 2.0 requires players to literally inhabit the pieces, completely replacing their hotbars with unique movesets. The Library Puzzle requires navigating a labyrinth where reading the wrong book spawns an elite.',
    trashMobs: ['Spectral Patron', 'Phantom Guardsman', 'Demonic Invader', 'Ethereal Thief'],
    associatedQuests: ['The Master\'s Key (Raid)', 'Closing the Rift'],
    speedrunStrats: 'Invisibility potions are mandatory to skip the massive pack of Demonic Invaders before Prince Malchezaar.',
    environmentalHazards: 'The Inverted Castle phase causes gravity to flip, requiring the raid to fight on the ceiling while dodging falling debris.',
    secrets: ['Clearing the raid in under 90 minutes spawns Medivh\'s Echo, a secret hard-mode boss.', 'Opera Event Scaling introduces 3 brand new plays including the Arthas & Jaina tragedy.'],
    bosses: ['Attumen', 'Moroes', 'The Curator', 'Shade of Aran', 'Prince Malchezaar', 'Medivh\'s Echo'],
    loot: generateLoot(100, 'Tier 3', 'KarazhanRaid')
  },
  {
    id: 'DragonIslesRaid',
    name: 'Temple of the Old Gods (Dragon Isles)',
    tier: 'Tier 3.5 (40 Man)',
    desc: 'The absolute pinnacle of Vanilla progression, located on the mythical Dragon Isles.',
    loreHistory: 'A forgotten island where the Old Gods first corrupted the proto-dragons. The architecture is impossibly ancient, pre-dating the Titans.',
    strategyGuide: 'Requires a fully coordinated 40-man raid to complete the World Tree Defense, holding off waves of elemental invaders. Ley-Line Alignment puzzles require players to physically connect beams of light to remove boss immunities.',
    trashMobs: ['Faceless Corruptor', 'Devolved Proto-Drake', 'Tentacle Horror', 'Mind-Flayer'],
    associatedQuests: ['The Final Nightmare (Raid)', 'Whispers in the Dark'],
    speedrunStrats: 'Time Dilation is a Bronze dragon mechanic that drastically slows player movement and cast speed; coordinate heroism effectively here.',
    environmentalHazards: 'The geometry of the temple physically shifts and changes layout every week, making memorization impossible.',
    secrets: ['Ultra-rare Proto-Dragon Mounts can drop from the final boss.'],
    bosses: ['The Aspect Council', 'The Faceless General', 'Avatar of the Old God'],
    loot: generateLoot(100, 'Tier 3.5', 'DragonIslesRaid')
  }
];

[...dungeons, ...raids].forEach(instance => {
  if (instance.wings) {
    instance.wings.forEach(wing => {
      if (wing.loot && wing.bosses && wing.bosses.length > 0) {
        wing.loot.forEach(item => {
          if (!item.source) item.source = `Dropped by: ${wing.bosses[Math.floor(Math.random() * wing.bosses.length)]}`;
        });
      }
    });
  } else if (instance.loot && instance.bosses && instance.bosses.length > 0) {
    instance.loot.forEach(item => {
      if (!item.source) item.source = `Dropped by: ${instance.bosses[Math.floor(Math.random() * instance.bosses.length)]}`;
    });
  }
});

const tsFile = `export const PVE_CATS = {
  DUNGEONS: 'The New Dungeons (Winged Hubs)',
  RAIDS: 'Parallel Raid Tiers'
};

export const pveData = {
  [PVE_CATS.DUNGEONS]: ${JSON.stringify(dungeons, null, 2)},
  [PVE_CATS.RAIDS]: ${JSON.stringify(raids, null, 2)}
};
`;

fs.writeFileSync('./src/data/dungeons.ts', tsFile);
console.log('Successfully wrote 30 dungeons and massive loot tables to dungeons.ts');
