const fs = require('fs');

const classChangelogs = {
  paladin: `export const CHANGELOG = [
  "General Changes",
  "Design Philosophy: Paladin talents have been heavily reorganized to bring WotLK-level cohesion and specialized utility to the Vanilla baseline. Active abilities have been shifted downwards, ensuring powerful defining traits are unlocked sooner.",
  "Retribution",
  "Identity: Evolves from a passive auto-attacker into a relentless, momentum-driven crusader with an active rotation and potent burst damage capability.",
  "Core Foundation: Improved Blessing of Might, Benediction, Improved Judgement grouped in Tier 1.",
  "Cross-Pollination: Deflection, Improved Retribution Aura, Two-Handed Weapon Specialization organized in Tier 2.",
  "Seal of Command: Moved down to serve as the defining 11-point anchor.",
  "Pursuit of Justice: Provides a solid passive mobility option in Tier 3.",
  "Vengeance: Buffed and compressed to 3 points in Tier 4 to supercharge critical strike scaling.",
  "Repentance: Positioned as the 21-point anchor, providing essential crowd control.",
  "The Active Engine: Judgements of the Wise, Sanctity Aura, Fanaticism organized in Tier 5 to provide crucial mana sustain and damage pacing.",
  "Crusader Strike: Added as the 31-point capstone, providing a fast standard melee strike to weave between auto-attacks.",
  "Holy",
  "Identity: Cements its role as the premier single-target, high-armor triage healer by shifting core throughput talents lower and introducing vital WotLK mechanics.",
  "Core Foundation: Divine Intellect, Spiritual Focus, Improved Seal of Righteousness grouped in Tier 1.",
  "Cross-Pollination: Healing Light, Unyielding Faith, Illumination organized in Tier 2.",
  "Divine Favor: Moved down as the reliable 11-point anchor.",
  "Sanctified Light: Provides a passive boost to Holy Light critical strike chance in Tier 3.",
  "Output & Scaling: Holy Power, Light's Grace fill out Tier 4 to reduce cast times and boost output.",
  "Holy Shock: Positioned as the 21-point anchor, providing crucial instant-cast healing or damage.",
  "The Active Engine: Infusion of Light, Purifying Power organized in Tier 5 for reactive gameplay options.",
  "Beacon of Light: Added as the ultimate 31-point capstone, allowing massive multi-target triage.",
  "Protection",
  "Identity: Transforms from a niche off-tank into an impenetrable, spell-reflecting fortress with vastly improved threat generation and active defensive layers.",
  "Core Foundation: Redoubt, Devotion, Toughness grouped in Tier 1.",
  "Cross-Pollination: Anticipation, Guardian's Favor, Shield Specialization organized in Tier 2.",
  "Blessing of Kings: Moved down to serve as the 11-point anchor, bringing vital raid utility.",
  "Threat & Mitigation: Improved Righteous Fury, Reckoning organized in Tier 3.",
  "Scaling: One-Handed Weapon Specialization, Sacred Duty fill out Tier 4.",
  "Holy Shield: Positioned as the 21-point anchor.",
  "The Active Engine: Ardent Defender, Combat Expertise organized in Tier 5 for profound late-fight survival.",
  "Avenger's Shield: Added as the 31-point capstone to solve initial pull mechanics and provide burst threat."
];`,

  druid: `export const CHANGELOG = [
  "General Changes",
  "Design Philosophy: A comprehensive modernization bringing TBC/WotLK coherence to the Druid toolkits. Omen of Clarity and Nature's Grasp have been made baseline abilities.",
  "Balance",
  "Identity: Transforms into an astrally-empowered, crit-scaling caster capable of robust multi-dotting and devastating eclipse phases.",
  "Core Foundation: Improved Wrath, Starlight Wrath, Nature's Grasp improved in Tier 1.",
  "Cross-Pollination: Control of Nature, Improved Moonfire, Brambles organized in Tier 2.",
  "Insect Swarm: Moved down to serve as the defining 11-point anchor.",
  "Reach & Cost: Nature's Reach, Moonglow organized in Tier 3.",
  "Vengeance: Compressed to 3 points in Tier 4 to supercharge spell critical strike scaling.",
  "Moonkin Form: Positioned as the 21-point anchor, providing the necessary armor and aura.",
  "The Active Engine: Lunar Guidance, Dreamstate organized in Tier 5 for massive mana sustain and spell power scaling.",
  "Sustain: Balance of Power, Improved Faerie Fire organized in Tier 6.",
  "Starfall: Added as the 31-point capstone, providing a spectacular cooldown for burst damage.",
  "Feral Combat",
  "Identity: Becomes a highly fluid shapeshifter with distinct Cat auto-attack engines and Bear mitigation tools unlocked early in the tree.",
  "Core Foundation: Ferocity, Feral Aggression, Thick Hide grouped in Tier 1.",
  "Cross-Pollination: Feral Swiftness, Brutal Impact, Sharpened Claws organized in Tier 2.",
  "Feral Charge: Moved down to serve as the 11-point anchor.",
  "Output & Mitigation: Predatory Strikes, Blood Frenzy, Primal Fury organized in Tier 3.",
  "Savage Fury: Provides a powerful damage modifier for core abilities in Tier 4.",
  "Faerie Fire (Feral): Positioned as the 21-point anchor.",
  "The Active Engine: Heart of the Wild, Survival of the Fittest organized in Tier 5 for immense statistical scaling.",
  "Sustain: Leader of the Pack, Improved Mangle organized in Tier 6.",
  "Mangle: Added as the 31-point capstone, replacing Claw and drastically smoothing the rotation.",
  "Restoration",
  "Identity: Solidifies as the ultimate reactive, heal-over-time master by compressing throughput talents and introducing lifebloom mechanics.",
  "Core Foundation: Improved Mark of the Wild, Furor, Naturalist grouped in Tier 1.",
  "Cross-Pollination: Nature's Focus, Natural Shapeshifter, Subtlety organized in Tier 2.",
  "Nature's Swiftness: Moved down to serve as the 11-point anchor.",
  "Output: Gift of Nature, Improved Rejuvenation organized in Tier 3.",
  "Nature's Bounty: Provides critical strike benefits for Regrowth and Nourish in Tier 4.",
  "Swiftmend: Positioned as the 21-point anchor.",
  "The Active Engine: Living Spirit, Empowered Rejuvenation organized in Tier 5 for profound HoT synergy.",
  "Sustain: Natural Perfection, Empowered Touch organized in Tier 6.",
  "Tree of Life: Added as the 31-point capstone, boosting group healing and armor."
];`,

  warrior: `export const CHANGELOG = [
  "General Changes",
  "Design Philosophy: Warrior talent trees have been heavily compressed and modernized, bringing WotLK-tier fluidity to the Vanilla baseline. Point bloat has been slashed across all specs.",
  "Arms",
  "Identity: Master of tactical positioning, huge two-handed weapon bursts, and bleeds, now featuring greatly compressed weapon specializations.",
  "Core Foundation: Improved Rend, Tactical Mastery (moved to tier 1), Improved Charge grouped in Tier 1.",
  "Cross-Pollination: Iron Will, Improved Thunder Clap, Improved Overpower, Improved Heroic Strike organized in Tier 2.",
  "Sweeping Strikes: Moved down to serve as the 11-point anchor.",
  "Output: Deep Wounds, Impale, Two-Handed Weapon Specialization organized in Tier 3.",
  "Master of Arms: Consolidates all four previous weapon specializations into a single 5-point node in Tier 4.",
  "Mortal Strike: Positioned aggressively as the 21-point anchor.",
  "The Active Engine: Second Wind, Blood Frenzy organized in Tier 5 for PvP survival and physical damage scaling.",
  "Burst Mechanics: Sudden Death, Juggernaut organized in Tier 6.",
  "Bladestorm: Added as the 31-point capstone, providing massive AoE threat and immune-spin capability.",
  "Fury",
  "Identity: A bloodthirsty, dual-wielding berserker that scales furiously with critical strikes, given much better inherent sustain.",
  "Core Foundation: Booming Voice, Cruelty, Improved Demoralizing Shout grouped in Tier 1.",
  "Cross-Pollination: Unbridled Wrath, Improved Cleave, Piercing Howl, Blood Craze organized in Tier 2.",
  "Death Wish: Moved down to serve as the 11-point anchor.",
  "Output: Improved Execute, Enrage organized in Tier 3.",
  "Flurry: Kept as the defining Tier 4 output modifier.",
  "Bloodthirst: Positioned as the 21-point anchor.",
  "The Active Engine: Dual Wield Specialization, Precision organized in Tier 5.",
  "Burst Mechanics: Furious Attacks, Bloodsurge organized in Tier 6.",
  "Rampage: Added as the 31-point capstone mini-cooldown.",
  "Protection",
  "Identity: Transitions from a slow, rage-starved tank into an impenetrable wall of steel equipped with excellent mobility and passive reflection.",
  "Core Foundation: Improved Bloodrage, Shield Specialization, Improved Thunder Clap grouped in Tier 1.",
  "Cross-Pollination: Improved Revenge, Toughness, Last Stand organized in Tier 2.",
  "Concussion Blow: Moved down to serve as the 11-point anchor.",
  "Output: Shield Mastery, One-Handed Weapon Specialization, Improved Disarm organized in Tier 3.",
  "Defiance: Provides massive baseline threat modifiers in Tier 4.",
  "Shield Slam: Positioned as the 21-point anchor.",
  "The Active Engine: Focused Rage, Vitality organized in Tier 5 for sweeping stat bonuses.",
  "Mobility & Reaction: Warbringer, Devastate organized in Tier 6.",
  "Shockwave: Added as the 31-point capstone for massive AoE control and threat."
];`,

  mage: `export const CHANGELOG = [
  "General Changes",
  "Design Philosophy: Evocation and Arcane Brilliance are now baseline. Spec trees have been streamlined, giving each school distinct output triggers and defensive tools without massive point bloat.",
  "Arcane",
  "Identity: A high-risk, mana-hungry glass cannon capable of extreme burst windows and high utility.",
  "Core Foundation: Arcane Subtlety, Arcane Focus, Improved Arcane Missiles grouped in Tier 1.",
  "Cross-Pollination: Wand Specialization, Magic Absorption, Arcane Concentration organized in Tier 2.",
  "Presence of Mind: Moved down to serve as the 11-point anchor.",
  "Output: Arcane Impact, Arcane Resilience, Improved Counterspell organized in Tier 3.",
  "Clearcasting: Arcane Meditation, Improved Mana Shield fill out Tier 4.",
  "Arcane Power: Positioned as the 21-point anchor.",
  "The Active Engine: Spell Power, Mind Mastery organized in Tier 5 for huge intellect scaling.",
  "Sustain & Burst: Arcane Potency, Prismatic Cloak organized in Tier 6.",
  "Arcane Barrage: Added as the 31-point capstone for instant mobility damage.",
  "Fire",
  "Identity: A rampant, crit-oriented pyromancer relying on DoT stacking and enormous explosive procs.",
  "Core Foundation: Improved Fireball, Impact, Ignite grouped in Tier 1.",
  "Cross-Pollination: Flame Throwing, Improved Fire Blast, Incineration organized in Tier 2.",
  "Pyroblast: Moved down to serve as the 11-point anchor.",
  "Output: Burning Soul, Master of Elements, Playing with Fire organized in Tier 3.",
  "Critical Mass: Provides massive baseline crit chance in Tier 4.",
  "Blast Wave: Positioned as the 21-point anchor.",
  "The Active Engine: Fire Power, Pyromaniac organized in Tier 5.",
  "Reaction: Combustion (now an active cooldown), Molten Fury organized in Tier 6.",
  "Dragon's Breath: Added as the 31-point capstone for heavy frontal burst control.",
  "Frost",
  "Identity: The absolute master of kiting, control, and shatter-combos, provided with a more reliable Water Elemental.",
  "Core Foundation: Frost Warding, Improved Frostbolt, Elemental Precision grouped in Tier 1.",
  "Cross-Pollination: Ice Shards, Frostbite, Improved Frost Nova organized in Tier 2.",
  "Cold Snap: Moved down to serve as the 11-point anchor.",
  "Output: Piercing Ice, Icy Veins, Blizzard Mastery organized in Tier 3.",
  "Shatter: Extracted and isolated in Tier 4 to guarantee its power is accessible.",
  "Ice Block: Positioned as the 21-point anchor.",
  "The Active Engine: Frost Channeling, Winter's Chill organized in Tier 5.",
  "Reaction: Brain Freeze, Empowered Frostbolt organized in Tier 6.",
  "Summon Water Elemental: Added as the 31-point capstone."
];`,

  hunter: `export const CHANGELOG = [
  "General Changes",
  "Design Philosophy: Traps can be used in combat naturally. Pets scale with player stats innately. The trees push deep synergies, enabling the elusive 'melee hunter' and making pets significantly more dangerous.",
  "Beast Mastery",
  "Identity: A feral tactician coordinating massive burst damage alongside a drastically empowered companion.",
  "Core Foundation: Improved Aspect of the Hawk, Endurance Training, Focused Fire grouped in Tier 1.",
  "Cross-Pollination: Thick Hide, Improved Revive Pet, Pathfinding organized in Tier 2.",
  "Bestial Swiftness: Moved down to act as the 11-point anchor.",
  "Output: Unleashed Fury, Improved Mend Pet, Ferocity organized in Tier 3.",
  "Intimidation: Acts as the definitive Tier 4 control talent.",
  "Bestial Wrath: Positioned as the 21-point anchor.",
  "The Active Engine: Frenzy, Animal Handler organized in Tier 5.",
  "Mastery: Serpent's Swiftness, The Beast Within organized in Tier 6.",
  "Beast Mastery: Added as the 31-point capstone, enabling exotic tames and bonus pet talent points.",
  "Marksmanship",
  "Identity: A deadly, methodical sniper excelling at extreme ranges, sustained physical damage, and heavy burst combinations.",
  "Core Foundation: Improved Concussive Shot, Lethal Shots, Improved Hunter's Mark grouped in Tier 1.",
  "Cross-Pollination: Efficiency, Go for the Throat, Improved Arcane Shot organized in Tier 2.",
  "Aimed Shot: Moved down to serve as the 11-point anchor.",
  "Output: Rapid Killing, Mortal Shots, Concussive Barrage organized in Tier 3.",
  "Scatter Shot: Acts as the definitive Tier 4 control talent.",
  "Trueshot Aura: Positioned as the 21-point anchor.",
  "The Active Engine: Ranged Weapon Specialization, Careful Aim organized in Tier 5.",
  "Mastery: Master Marksman, Combat Experience organized in Tier 6.",
  "Chimera Shot: Added as the 31-point capstone.",
  "Survival",
  "Identity: A rugged skirmisher and trapper, heavily favoring Agility scaling, high-explosive traps, and potent melee strike capabilities.",
  "Core Foundation: Monster Slaying, Humanoid Slaying, Deflection, Savage Strikes grouped in Tier 1.",
  "Cross-Pollination: Entrapment, Survivalist, Improved Wing Clip organized in Tier 2.",
  "Deterrence: Moved down to serve as the 11-point anchor.",
  "Output: Trap Mastery, Surefooted, Improved Feign Death organized in Tier 3.",
  "Killer Instinct: Acts as the definitive Tier 4 combat modifier.",
  "Wyvern Sting: Positioned as the 21-point anchor.",
  "The Active Engine: Lightning Reflexes, Resourcefulness organized in Tier 5.",
  "Mastery: Expose Weakness, Master Tactical organized in Tier 6.",
  "Explosive Shot: Added as the 31-point capstone."
];`,

warlock: `export const CHANGELOG: string[] = [
  "General Changes",
  "Design Philosophy: Amplify Curse and Curse of Exhaustion are now baseline. Warlock trees have been rigorously structured, giving each specialization a clear thematic identity and a capstone capable of altering their playstyle.",
  "Affliction",
  "Identity: The master of agonizing rot and self-healing. Plays heavily around maximizing drain effects and multi-target decay.",
  "Core Foundation: Improved Corruption, Suppression, Improved Life Tap grouped in Tier 1.",
  "Cross-Pollination: Nightfall, Fel Concentration, Grim Reach, Soul Siphon organized in Tier 2.",
  "Siphon Life: Positioned as the 11-point anchor, defining the drain-tanking theme.",
  "Output: Empowered Corruption, Shadow Embrace organized in Tier 3.",
  "Scaling: Shadow Mastery, Master of Curses fill out Tier 4.",
  "Dark Pact: Positioned as the 21-point anchor.",
  "The Active Engine: Contagion, Eradication organized in Tier 5.",
  "Sustain & Mastery: Pandemic, Malediction organized in Tier 6.",
  "Unstable Affliction: Added as the 31-point capstone.",
  "Demonology",
  "Identity: A master summoner who synergizes with their demonic pets, leveraging heavy stamina, spell power sharing, and profound physical mitigation.",
  "Core Foundation: Demonic Embrace, Improved Imp, Improved Healthstone grouped in Tier 1.",
  "Cross-Pollination: Fel Domination, Health Funnel, Improved Voidwalker, Demonic Intellect organized in Tier 2.",
  "Soul Link: Moved aggressively down to the 11-point anchor, defining the spec early.",
  "Output: Unholy Power, Master Demonologist organized in Tier 3.",
  "Defenses: Demonic Aegis, Fel Synergy organized in Tier 4.",
  "Demonic Sacrifice: Positioned as the 21-point anchor.",
  "The Active Engine: Demonic Knowledge, Mana Feed organized in Tier 5.",
  "Sustain & Mastery: Master Conjuror, Demonic Tactics, Demonic Pact organized in Tier 6.",
  "Summon Felguard: Added as the 31-point capstone.",
  "Destruction",
  "Identity: A chaotic, explosive spellcaster specializing in rapid immolation, heavy critical strikes, and devastating fire stuns.",
  "Core Foundation: Improved Shadow Bolt, Cataclysm, Bane grouped in Tier 1.",
  "Cross-Pollination: Devastation, Intensity, Aftermath organized in Tier 2.",
  "Shadowburn: Positioned as the 11-point anchor.",
  "Output: Improved Immolate, Destructive Reach organized in Tier 3.",
  "Defenses: Pyroclasm, Nether Protection organized in Tier 4.",
  "Conflagrate: Positioned as the 21-point anchor.",
  "The Active Engine: Backlash, Improved Firestone organized in Tier 5.",
  "Sustain & Mastery: Soul Leech, Shadow and Flame (Including Ruin) organized in Tier 6.",
  "Shadowfury: Added as the 31-point capstone."
];`,

  shaman: `export const CHANGELOG = [
  "General Changes",
  "Design Philosophy: Totemic Mastery is baseline. The Hybrid Tax has been eliminated. The trees have been injected with distinct elemental combos, powerful new tier anchors, and definitive active capstone abilities.",
  "Elemental",
  "Identity: A devastating storm-caller commanding massive ranged burst potential and unprecedented group-wide offensive utility.",
  "Core Foundation: Convection, Concussion, Call of Flame grouped in Tier 1.",
  "Cross-Pollination: Earth's Grasp, Elemental Warding, Elemental Focus organized in Tier 2.",
  "Elemental Fury: Positioned as the critical 11-point anchor.",
  "Output: Improved Fire Totems, Eye of the Storm, Storm Reach organized in Tier 3.",
  "Control: Storm, Earth, and Fire, Lightning Mastery established in Tier 4.",
  "Elemental Mastery: Positioned as the 21-point anchor.",
  "The Active Engine: Totemic Surge, Lightning Overload organized in Tier 5.",
  "Totem of Wrath: Added as the 31-point capstone, providing unmatched group offensive buffs.",
  "Enhancement",
  "Identity: A ruthless, dual-wielding battlemage weaving elemental shocks between massive melee strikes.",
  "Core Foundation: Ancestral Knowledge, Shield Specialization, Thundering Strikes grouped in Tier 1.",
  "Cross-Pollination: Improved Ghost Wolf, Improved Lightning Shield, Enhancing Totems organized in Tier 2.",
  "Ancestral Mastery: Positioned as the 11-point anchor, enabling Dual Wielding.",
  "Output: Flurry, Toughness, Elemental Weapons organized in Tier 3.",
  "Utility: Anticipation, Unleashed Rage established in Tier 4.",
  "Stormstrike: Positioned as the 21-point anchor (Reduced to 1 point, 8s cd).",
  "The Active Engine: Mental Quickness, Weapon Mastery organized in Tier 5.",
  "Burst Mechanics: Shamanistic Focus, Static Shock organized in Tier 6.",
  "Feral Spirit: Added as the 31-point capstone, summoning massive Spirit Wolves for burst and utility.",
  "Restoration",
  "Identity: The unrivaled king of multi-target throughput and massive regenerative tides.",
  "Core Foundation: Improved Healing Wave, Tidal Focus, Improved Reincarnation grouped in Tier 1.",
  "Cross-Pollination: Ancestral Healing, Totemic Focus, Nature's Guidance organized in Tier 2.",
  "Nature's Swiftness: Moved down to the 11-point anchor.",
  "Output: Healing Grace, Tidal Mastery, Healing Way organized in Tier 3.",
  "Sustain: Restorative Totems, Purification established in Tier 4.",
  "Mana Tide Totem: Positioned as the 21-point anchor.",
  "The Active Engine: Nature's Blessing, Ancestral Awakening organized in Tier 5.",
  "Mechanics: Earth Shield, Improved Chain Heal organized in Tier 6.",
  "Riptide: Added as the 31-point capstone, offering massive instant triage and HoT capability."
];`
};

for (const [cls, changelogStr] of Object.entries(classChangelogs)) {
  const file = '/app/applet/src/data/' + cls + '.ts';
  let content = fs.readFileSync(file, 'utf8');
  content = content.replace(/export const CHANGELOG[^]*?\];/, changelogStr);
  fs.writeFileSync(file, content);
}
