// Auto-generated by generatePvP.cjs (POLISHED HANDCRAFTED CLASSIC+ EDITION)

export const PVP_MODES = {
  BATTLEGROUNDS: 'New Battlegrounds',
  WORLD_PVP: 'World PvP & Banner Wars',
  ARENA: 'The Gurubashi Arena Brawls',
  HONOR_SYSTEM: 'Honor & Progression Systems'
};

export interface PvPItem {
  id: string;
  name: string;
  size: string;
  type: string;
  description: string;
  mechanics: string[];
  lore: string;
  mapLayout: string;
  powerUps: string[];
  factionHistory: string;
  topMetaComps: string[];
  achievements: string[];
  associatedReputations: string[];
  uniqueRewards: any[];
}

export const pvpData: Record<string, PvPItem[]> = {
  "New Battlegrounds": [
    {
      "id": "AzsharaCrater",
      "name": "Azshara Crater",
      "size": "25v25",
      "type": "Strategic Siege & Territory Control",
      "description": "The legendary unreleased Vanilla battleground restored to its full glory. Set in the craggy mountains above Azshara, the Alliance and Horde fight for dominance over three vital strategic passes and resource nodes.",
      "mechanics": [
        "Strategic Strongholds: Capture and defend the Northern Timber Pass, Central Caldera, and Southern Mine to drain enemy reinforcements.",
        "Timbermaw Neutral Mercenaries: Secure friendly standing with neutral furbolg shamans to summon powerful storm totems to support frontline pushes.",
        "Fortress Gate Sabotage: Gather localized lumber and iron resources to construct battering rams and breach the fortified inner sanctum."
      ],
      "lore": "The Horde seeks to secure vital lumber and stone to fuel their war efforts in Durotar, while the Alliance strives to fortify the high bluffs to shield their naval shipping lanes in the Great Sea below.",
      "mapLayout": "Rugged caldera terrain with rocky ridges, dense pine forests, and fortified cliffside choke points.",
      "powerUps": [
        "Speed Boots (+100% ground movement speed for 10 sec)",
        "Berserking (+30% damage dealt, +20% damage taken for 20 sec)",
        "Restorative Draught (Restores 20% health and mana over 10 sec)"
      ],
      "factionHistory": "A contested borderland where old treaties between the Night Elves and the Orcs have completely broken down into open warfare.",
      "topMetaComps": [
        "Warrior / Paladin / Priest / Mage / Hunter",
        "Warrior / Shaman / Warlock / Rogue / Druid"
      ],
      "achievements": [
        "Conqueror of the Crater",
        "Master of the Timbermaw Pass"
      ],
      "associatedReputations": [
        "Silverwing Sentinels / Warsong Outriders",
        "Timbermaw Hold"
      ],
      "uniqueRewards": [
        {
          "name": "Vicious Blade of Azshara",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Main Hand",
          "type": "Axe",
          "stats": [
            "+18 Strength",
            "+14 Agility",
            "+16 Stamina",
            "Equip: Improves your chance to get a critical strike by 1%."
          ],
          "effect": "Chance on hit: Wounds the target for 120 Nature damage and slows movement speed by 30% for 5 sec.",
          "requiresLevel": 60
        },
        {
          "name": "Collar of the Crater Commander",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Neck",
          "type": "Necklace",
          "stats": [
            "+20 Stamina",
            "+12 Strength",
            "Equip: Increases your hit rating by 1%."
          ],
          "effect": "",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "GillijimIsle",
      "name": "Gillijim's Isle",
      "size": "15v15",
      "type": "Coastal Warfare & Galleon Siege",
      "description": "Set on the restored Alpha island off the coast of Stranglethorn. Teams battle across the sandy shores and jagged cliffs to seize control of coastal cannon batteries.",
      "mechanics": [
        "Coastal Shore Batteries: Control heavy shore artillery to bombard enemy defensive fortifications and coastal docks.",
        "Rowboat Infiltration: Utilize small rowboats to launch surprise flanking attacks behind enemy beachheads.",
        "Cursed Pirate Caches: Contested chests on the reef spawn temporary combat buffs at the risk of open-water exposure."
      ],
      "lore": "The Bloodsail Buccaneers and Steamwheedle Cartel employ Alliance and Horde champions as privateers to seize the island's hidden pirate coves.",
      "mapLayout": "Tropical white-sand beaches, crumbling stone ramparts, and tidal reefs.",
      "powerUps": [
        "Rum-Fueled Courage (Immune to fear for 8 sec, movement is slightly staggered)",
        "Speed Boots (+100% speed)"
      ],
      "factionHistory": "An uncharted tropical sanctuary where high-seas law rules supreme.",
      "topMetaComps": [
        "Rogue / Mage / Priest / Warrior / Druid"
      ],
      "achievements": [
        "Privateer of the Southern Seas",
        "Master Bombardier"
      ],
      "associatedReputations": [
        "Booty Bay (Steamwheedle Cartel)"
      ],
      "uniqueRewards": [
        {
          "name": "Privateer's Cutlass",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "One-Hand",
          "type": "Sword",
          "stats": [
            "+15 Agility",
            "+12 Stamina",
            "Equip: Increases attack power by 26."
          ],
          "effect": "Chance on hit: Delivers a rapid second strike.",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "HyjalFront",
      "name": "The Hyjal Front",
      "size": "40v40",
      "type": "Asymmetrical Mountain Siege",
      "description": "A massive 40v40 siege battle taking place on the steep slopes leading to the World Tree Nordrassil.",
      "mechanics": [
        "Ascent & Defense: One faction assaults up the mountain barriers while the other reinforces fortified timber gates. Objectives swap per match round.",
        "Horn of Cenarius: Defenders can sound the ancient horn to awaken Ancient Treants to defend the upper choke points.",
        "Demolition Charges: Attackers carry heavy alchemical charges to shatter fortified wooden barricades."
      ],
      "lore": "The Night Elves and Alliance defend the sacred slopes against Horde warbands seeking ancient infused lumber and leylines.",
      "mapLayout": "Vertical alpine slopes, scorched roots, and defensive timber redoubts.",
      "powerUps": [
        "Blessing of the Ancients (+15% nature damage & healing)",
        "Berserking (+30% damage dealt)"
      ],
      "factionHistory": "The sacred battlefield where the races of Azeroth made their legendary stand during the Third War.",
      "topMetaComps": [
        "Full 40-man organized warbands"
      ],
      "achievements": [
        "Hero of the Sacred Summit",
        "Gatebreaker of Nordrassil"
      ],
      "associatedReputations": [
        "Cenarion Circle"
      ],
      "uniqueRewards": [
        {
          "name": "Nordrassil Battle Standard",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Trinket",
          "type": "Trinket",
          "stats": [
            "+20 Stamina",
            "Equip: Increases spell and melee critical strike by 1%."
          ],
          "effect": "Use: Plants a standard increasing party health by 300 for 2 min.",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "StromgardeSiege",
      "name": "Stromgarde Siege",
      "size": "20v20",
      "type": "Urban Warfare & Stronghold Control",
      "description": "The ruined stone avenues and ramparts of Stromgarde in Arathi Highlands turned into a gritty urban battleground.",
      "mechanics": [
        "Vertical Ramparts: Control the castle walls and towers to gain line of sight and elevation advantages over street corridors.",
        "Keep Keymaster: Slay the central Syndicate warlord to acquire the Keep Key, opening the inner gate for bonus tactical points.",
        "Supply Stashes: Secure munitions caches in the merchant quarter to empower NPC guards."
      ],
      "lore": "Danath Trollbane's loyalists clash with Forsaken expansion forces seeking to seize the gateway to the Arathi Highlands.",
      "mapLayout": "Paved stone streets, ruined cathedral plazas, sewers, and fortified stone battlements.",
      "powerUps": [
        "Syndicate Adrenaline (+25% haste for 15 sec)"
      ],
      "factionHistory": "The ancestral capital of the human kingdom of Stromgarde.",
      "topMetaComps": [
        "Warrior / Priest / Warlock / Mage / Rogue"
      ],
      "achievements": [
        "Liberator of Stromgarde",
        "Urban Warlord"
      ],
      "associatedReputations": [
        "League of Arathor / The Defilers"
      ],
      "uniqueRewards": [
        {
          "name": "Trollbane Greatshield",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Off Hand",
          "type": "Shield",
          "stats": [
            "2540 Armor",
            "45 Block",
            "+22 Stamina",
            "+15 Strength",
            "Equip: Increases defense rating by 10."
          ],
          "effect": "",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "AlteracValleyRevamp",
      "name": "Alterac Valley 1.12 Classic Revamp",
      "size": "40v40",
      "type": "Epic Long-Form War",
      "description": "Restores the legendary long-form Alterac Valley battleground with formidable NPC defenses, summoning rituals, and Korrak the Bloodrager.",
      "mechanics": [
        "Summoning Bosses: Ivus the Forest Lord and Lokholar the Ice Lord require massive coordinated blood/crystal turn-ins to march down the battlefield.",
        "Supply Runs & Armor Scraps: Upgrading NPC guards and archers through turn-ins creates impenetrable defensive choke points.",
        "Korrak the Bloodrager: The fearsome troll warlord returns to Snowfall Graveyard with bespoke quest rewards."
      ],
      "lore": "The Stormpike Guard and Frostwolf Clan wage an unyielding war of attrition in the snowy passes of Alterac.",
      "mapLayout": "Massive alpine valley spanning bunkers, towers, frozen lakes, and mountainous graveyards.",
      "powerUps": [
        "Warmaster's Roar (+10% attack and cast speed)"
      ],
      "factionHistory": "An eternal territorial struggle rooted in sovereign dwarven excavation and ancestral orcish home grounds.",
      "topMetaComps": [
        "Full 40-man guild raid rosters"
      ],
      "achievements": [
        "Frostwolf Champion / Stormpike Legend"
      ],
      "associatedReputations": [
        "Stormpike Guard / Frostwolf Clan"
      ],
      "uniqueRewards": [
        {
          "name": "Don Julio's Band (Classic+)",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Finger",
          "type": "Ring",
          "stats": [
            "+11 Stamina",
            "Equip: +1% Critical Strike.",
            "Equip: +1% Hit chance.",
            "Equip: +16 Attack Power."
          ],
          "effect": "",
          "requiresLevel": 60
        }
      ]
    }
  ],
  "World PvP & Banner Wars": [
    {
      "id": "BannerWars",
      "name": "The Banner War System",
      "size": "Zone-Wide World PvP",
      "type": "Dynamic Open-World Objectives",
      "description": "Dynamic territorial skirmishes across contested classic zones (Hillsbrad Foothills, Ashenvale, Stranglethorn Vale, and Blackrock Mountain).",
      "mechanics": [
        "Supply Caravans: Unannounced, un-instanced military caravans march through contested zones. Successfully defending or ambushing a caravan awards faction zone-wide buffs for 2 hours.",
        "Bounty Hunting: Slaying excessive numbers of opposing players flags you on the local zone map, offering honor bounties to opposing hunters.",
        "Contested Watchtowers: Open-world flags that award localized honor and minor gathering bonuses when held."
      ],
      "lore": "The cold war between the Alliance and Horde continuously flares up wherever military supplies and territory are contested.",
      "mapLayout": "Contested open-world regions of the Eastern Kingdoms and Kalimdor.",
      "powerUps": [
        "Zone Victor Morale (+5% rested XP and +5% reputation gains in the zone)"
      ],
      "factionHistory": "The legendary open-world battles of Southshore vs. Tarren Mill and the Crossroads realized with structured rewards.",
      "topMetaComps": [
        "World PvP roaming groups and defense parties"
      ],
      "achievements": [
        "Hero of Southshore",
        "Defender of the Crossroads"
      ],
      "associatedReputations": [
        "Alliance / Horde Military Command"
      ],
      "uniqueRewards": [
        {
          "name": "Banner of the Contested Vanguard",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Back",
          "type": "Cloth",
          "stats": [
            "+18 Stamina",
            "+12 Strength",
            "+12 Agility"
          ],
          "effect": "Use: Increases movement speed by 15% for 10 sec. (5 Min Cooldown)",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "CrimsonAtoll",
      "name": "The Crimson Atoll Bloodbath",
      "size": "Free-For-All",
      "type": "Scheduled Island Chaos",
      "description": "A lawless island reef off the coast of Stranglethorn Vale that erupts into a free-for-all bloodbath every 3 hours.",
      "mechanics": [
        "No Factions / Free-For-All: All nameplates turn red. Trust no one outside your immediate vision.",
        "Blood Tokens: Slaying combatants yields Blood Tokens redeemable in Booty Bay for prestigious cosmetic heraldry and recipes.",
        "The Blood Fog: The island perimeter slowly shrinks over 30 minutes, forcing combatants into a brutal final clash."
      ],
      "lore": "An ancient troll altar soaked in dark voodoo calls upon bloodthirsty mercenaries from across the world.",
      "mapLayout": "Submerged coral reefs, jungle grottos, and a central bloodstone arena.",
      "powerUps": [
        "Bloodrage (+20% damage, -10% armor)"
      ],
      "factionHistory": "A lawless pirate reef where gold and blood rule.",
      "topMetaComps": [
        "Solo survivalists and stealth ambushers"
      ],
      "achievements": [
        "Survivor of the Crimson Atoll"
      ],
      "associatedReputations": [
        "Booty Bay Smugglers"
      ],
      "uniqueRewards": [
        {
          "name": "Trollbone Dagger of the Atoll",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "One-Hand",
          "type": "Dagger",
          "stats": [
            "+16 Agility",
            "+10 Stamina",
            "Equip: +1% Critical Strike."
          ],
          "effect": "Chance on hit: Inflicts deep bleed for 150 damage over 6 sec.",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "SilithusSand",
      "name": "Silithus Geyser & Silicate Warfare",
      "size": "Zone Event",
      "type": "Open-World Resource Race",
      "description": "Overhauls the Silithus open-world PvP event to grant substantial Cenarion Circle reputation and high-tier military tokens.",
      "mechanics": [
        "Silicate Dust Extraction: Channel on erupting geysers to gather silicate dust and escort it back to your faction camp.",
        "Cenarion Hold Recognition: Successfully turning in dust grants Cenarion Circle reputation and unlocks localized flight master buffs.",
        "Hive Ambushers: Elite silithid bugs ambush extractors, creating multi-front chaos."
      ],
      "lore": "The Cenarion Circle urgently requires silicate dust to prepare mystical wards against the slumbering Qiraji.",
      "mapLayout": "Dune expanses, colossal hive burrows, and twilight camps.",
      "powerUps": [
        "Silicate Ward (+20 Shadow Resistance)"
      ],
      "factionHistory": "The prelude to the Ahn'Qiraj war effort.",
      "topMetaComps": [
        "Escort pairs and skirmish defensive squads"
      ],
      "achievements": [
        "Sandrunner of Silithus"
      ],
      "associatedReputations": [
        "Cenarion Circle"
      ],
      "uniqueRewards": [
        {
          "name": "Cenarion Scout Band",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Finger",
          "type": "Ring",
          "stats": [
            "+15 Stamina",
            "+10 Agility",
            "+10 Strength"
          ],
          "effect": "",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "ContestedNodes",
      "name": "Contested Rich Thorium Nodes",
      "size": "Open World",
      "type": "High-Stakes Resource Extraction",
      "description": "Special high-yield mineral and lotus deposits in high-level zones that temporarily flag the gatherer for PvP upon initiation.",
      "mechanics": [
        "PvP Flag: Mining or picking a contested node flags your character for PvP for 5 minutes regardless of realm rules.",
        "Double Yield: Awards double raw ore and guaranteed rare gems or Black Lotus petals."
      ],
      "lore": "Some of Azeroth's richest treasures are worth fighting and dying for.",
      "mapLayout": "Volcanic crevices of Un'Goro, Silithus, and Winterspring.",
      "powerUps": [
        "Prospector's Fortune"
      ],
      "factionHistory": "Greed drives miners and herbalists into bloody skirmishes across the wilderness.",
      "topMetaComps": [
        "Gatherers with escort partners"
      ],
      "achievements": [
        "Blood-Forged Prospector"
      ],
      "associatedReputations": [
        "Neutral Gathering Guilds"
      ],
      "uniqueRewards": [
        {
          "name": "Prospector's Sturdy Belt",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Waist",
          "type": "Mail",
          "stats": [
            "+18 Stamina",
            "+14 Strength",
            "+12 Intellect"
          ],
          "effect": "",
          "requiresLevel": 60
        }
      ]
    }
  ],
  "The Gurubashi Arena Brawls": [
    {
      "id": "GurubashiBrawl",
      "name": "The Gurubashi Arena Brawl",
      "size": "10v10",
      "type": "Chaos Deathmatch & Trap Hazards",
      "description": "Arena in Classic+ is not small-scale esport pillar-humping; it is a chaotic 10v10 gladiatorial bloodsport inside the Gurubashi pit.",
      "mechanics": [
        "One Life Per Round: Best of 5 rounds. The last team standing claims the round.",
        "Arena Hazards: Spike pits, swinging pendulum axes, and wild beasts periodically released into the sand.",
        "Crowd Favor: Dealing massive burst damage or scoring killing blows earns the crowd's favor, tossing healing potions or explosive bombs into the pit."
      ],
      "lore": "The Steamwheedle Cartel broadcasts gladiatorial deathmatches for the entertainment and wagering of all Azeroth.",
      "mapLayout": "Sunken stone arena pit surrounded by spectator stands and spike gates.",
      "powerUps": [
        "Gladiator's Brew (+15% damage for 10 sec)"
      ],
      "factionHistory": "The ancient gladiatorial tradition of the jungle trolls.",
      "topMetaComps": [
        "Balanced 10-man melee and caster death squads"
      ],
      "achievements": [
        "Grand Gladiator of Gurubashi"
      ],
      "associatedReputations": [
        "Steamwheedle Cartel"
      ],
      "uniqueRewards": [
        {
          "name": "Gladiator's Sand-Crusted Girdle",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Waist",
          "type": "Plate",
          "stats": [
            "+24 Strength",
            "+18 Stamina",
            "Equip: Increases critical strike chance by 1%."
          ],
          "effect": "",
          "requiresLevel": 60
        }
      ]
    }
  ],
  "Honor & Progression Systems": [
    {
      "id": "HonorForHealing",
      "name": "Combat Honor for Healing",
      "size": "Global PvP",
      "type": "Reward Parity",
      "description": "Dedicated battlefield healers receive full scoreboard credit and direct bonus Honor contribution based on effective healing performed in combat.",
      "mechanics": [
        "Combat Support Contribution: Healing allies who are actively engaged in PvP combat contributes directly to your personal honor calculation and scoreboard ranking.",
        "Prevents healers from being penalized in rank progression compared to solo killing-blow classes."
      ],
      "lore": "Battlefield medics are as vital to victory as the warriors holding the front lines.",
      "mapLayout": "All Battlegrounds and World PvP zones.",
      "powerUps": [
        "Medic's Resolve"
      ],
      "factionHistory": "Honoring the holy and spiritual champions of the Alliance and Horde.",
      "topMetaComps": [
        "Holy Paladins, Restoration Shamans, Holy/Disc Priests, Resto Druids"
      ],
      "achievements": [
        "Field Medic Legend"
      ],
      "associatedReputations": [
        "Military High Command"
      ],
      "uniqueRewards": [
        {
          "name": "Field Medic's Signet of Grace",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Finger",
          "type": "Ring",
          "stats": [
            "+14 Stamina",
            "+12 Intellect",
            "Equip: Increases healing done by spells by up to 33.",
            "Equip: Restores 5 mana per 5 sec."
          ],
          "effect": "",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "Rank11Mounts",
      "name": "Rank 11 Armored War Mounts",
      "size": "Global PvP",
      "type": "Prestige Progression",
      "description": "Hitting PvP Rank 11 unlocks faction-specific Armored War Mounts (Armored Kodos, War Raptors, Armored Tigers, and War Rams) with 100% ground speed.",
      "mechanics": [
        "Requires Rank 11 (Commander / Lieutenant General) standing.",
        "Epic 100% movement speed with heavy war bards and faction heraldry."
      ],
      "lore": "Beasts bred and armored solely for the brutal front lines of the faction war.",
      "mapLayout": "Capital City Military Barracks.",
      "powerUps": [
        "War-Bred Stamina"
      ],
      "factionHistory": "The hallmark of elite cavalry across the battlefields of Azeroth.",
      "topMetaComps": [
        "Rank 11+ PvP Combatants"
      ],
      "achievements": [
        "Lieutenant General / Commander"
      ],
      "associatedReputations": [
        "Alliance / Horde Military Command"
      ],
      "uniqueRewards": [
        {
          "name": "Reins of the Armored Black War Tiger",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Mount",
          "type": "Mount",
          "stats": [
            "Requires Level 60",
            "Requires Riding (150)",
            "Increases ground movement speed by 100%."
          ],
          "effect": "",
          "requiresLevel": 60
        }
      ]
    },
    {
      "id": "PremadeMatchmaking",
      "name": "Premade Group Matching Priority",
      "size": "Battleground Queue",
      "type": "Queue Fair Play",
      "description": "Battleground matchmaking strongly prioritizes matching organized premade groups of 5+ players against other premade groups.",
      "mechanics": [
        "Protects solo and small-group pug players from being repeatedly routed by 15-man and 40-man premades.",
        "Fosters high-stakes competitive matches between organized guild PvP warbands."
      ],
      "lore": "Honor is earned against worthy foes, not defenseless stragglers.",
      "mapLayout": "Global Battleground Matchmaking System.",
      "powerUps": [
        "Equal Footing"
      ],
      "factionHistory": "A cornerstone of honorable combat across the Alliance and Horde.",
      "topMetaComps": [
        "Organized Guild Battleground Rosters"
      ],
      "achievements": [
        "Conqueror of Warsong",
        "Battleground Tactician"
      ],
      "associatedReputations": [
        "Alliance / Horde High Command"
      ],
      "uniqueRewards": [
        {
          "name": "Insignia of the Tactical Vanguard",
          "rarity": "Epic",
          "bindType": "Binds when picked up",
          "slot": "Trinket",
          "type": "Trinket",
          "stats": [
            "+20 Stamina"
          ],
          "effect": "Use: Dispels all movement impairing and loss of control effects. (2 Min Cooldown)",
          "requiresLevel": 60
        }
      ]
    }
  ]
};
