import { Talent } from '../types/talents';

export const WARRIOR_ARMS_TALENTS: any = [
  {
    "id": "tactical_mastery",
    "name": "Tactical Mastery",
    "icon": "spell_nature_enchantarmor",
    "maxPoints": 2,
    "row": 0,
    "col": 0,
    "desc": [
      "You retain up to 15 of your Rage points when you change stances.",
      "30"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Tactical Mastery represents the pinnacle of the class.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Tactical Mastery.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Tactical Mastery attack."
  },
  {
    "id": "deflection",
    "name": "Deflection",
    "icon": "ability_parry",
    "maxPoints": 5,
    "row": 0,
    "col": 1,
    "desc": [
      "Increases your Parry chance by 1%.",
      "2%",
      "3%",
      "4%",
      "5%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Deflection.",
    "devCommentary": "We wanted Deflection to define the Arms playstyle at all levels.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Deflection attack."
  },
  {
    "id": "imp_rend",
    "name": "Improved Rend",
    "icon": "ability_gouge",
    "maxPoints": 3,
    "row": 0,
    "col": 2,
    "desc": [
      "Increases the bleed damage done by your Rend ability by 15% and increases its duration by 2 seconds.",
      "25% / 4 seconds",
      "35% / 6 seconds"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Improved Rend between auto-attacks.",
      "Creates a devastating synergy when you weave Improved Rend between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "Initially, Improved Rend was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "The ground shatters as the brutal power of Improved Rend courses through you."
  },
  {
    "id": "imp_charge",
    "name": "Improved Charge",
    "icon": "ability_warrior_charge",
    "maxPoints": 2,
    "row": 1,
    "col": 0,
    "desc": [
      "Increases the amount of rage generated by your Charge ability by 10.",
      "20"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Improved Charge represents the pinnacle of the class.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Improved Charge.",
    "devCommentary": "Initially, Improved Charge was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "The ground shatters as the brutal power of Improved Charge courses through you."
  },
  {
    "id": "imp_overpower",
    "name": "Improved Overpower",
    "icon": "inv_sword_05",
    "maxPoints": 3,
    "row": 1,
    "col": 1,
    "desc": [
      "Increases the critical strike chance of your Overpower ability by 17%.",
      "34%",
      "50%"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Improved Overpower represents the pinnacle of the class.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Creates a devastating synergy when you weave Improved Overpower between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Improved Overpower.",
    "devCommentary": "We wanted Improved Overpower to define the Arms playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Improved Overpower."
  },
  {
    "id": "deep_wounds",
    "name": "Deep Wounds",
    "icon": "ability_backstab",
    "maxPoints": 3,
    "row": 1,
    "col": 2,
    "requires": {
      "id": "imp_rend",
      "points": 3
    },
    "desc": [
      "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 seconds.",
      "40%",
      "60%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Deep Wounds.",
    "devCommentary": "Initially, Deep Wounds was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Deep Wounds temporarily wreathes your character in brutal energy."
  },
  {
    "id": "imp_heroic_strike",
    "name": "Improved Heroic Strike",
    "icon": "ability_rogue_ambush",
    "maxPoints": 2,
    "row": 1,
    "col": 3,
    "desc": [
      "Reduces the cost of your Heroic Strike ability by 1 rage point.",
      "2 rage points"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Improved Heroic Strike between auto-attacks.",
      "Creates a devastating synergy when you weave Improved Heroic Strike between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "We wanted Improved Heroic Strike to define the Arms playstyle at all levels.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Improved Heroic Strike attack."
  },
  {
    "id": "two_handed_ws",
    "name": "Two-Handed Weapon Specialization",
    "icon": "inv_axe_09",
    "maxPoints": 5,
    "row": 2,
    "col": 0,
    "desc": [
      "Increases the damage you deal with two-handed melee weapons by 1%.",
      "2%",
      "3%",
      "4%",
      "5%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Two-Handed Weapon Specialization.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Two-Handed Weapon Specialization."
  },
  {
    "id": "sweeping_strikes",
    "name": "Sweeping Strikes",
    "icon": "ability_rogue_slicedice",
    "maxPoints": 1,
    "row": 2,
    "col": 1,
    "desc": [
      "Your next 5 melee attacks strike an additional nearby opponent. 30 second cooldown."
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Sweeping Strikes represents the pinnacle of the class.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Creates a devastating synergy when you weave Sweeping Strikes between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Sweeping Strikes.",
    "devCommentary": "We wanted Sweeping Strikes to define the Arms playstyle at all levels.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Sweeping Strikes attack."
  },
  {
    "id": "impale",
    "name": "Impale",
    "icon": "ability_searingarrow",
    "maxPoints": 2,
    "row": 2,
    "col": 2,
    "requires": {
      "id": "deep_wounds",
      "points": 3
    },
    "desc": [
      "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.",
      "20%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Impale.",
    "devCommentary": "Initially, Impale was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Impale temporarily wreathes your character in brutal energy."
  },
  {
    "id": "master_of_arms",
    "name": "Master of Arms",
    "icon": "inv_sword_27",
    "maxPoints": 5,
    "row": 3,
    "col": 0,
    "desc": [
      "Grants specialized bonuses based on your equipped melee weapon: Swords (1% chance for extra attack), Axes/Polearms (1% increased critical strike chance), Maces (ignore 3% armor, 1% stun chance).",
      "Swords (2%), Axes/Polearms (2%), Maces (6% armor, 2% stun).",
      "Swords (3%), Axes/Polearms (3%), Maces (9% armor, 3% stun).",
      "Swords (4%), Axes/Polearms (4%), Maces (12% armor, 4% stun).",
      "Swords (5%), Axes/Polearms (5%), Maces (15% armor, 5% stun)."
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Master of Arms represents the pinnacle of the class.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Creates a devastating synergy when you weave Master of Arms between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Master of Arms.",
    "devCommentary": "We wanted Master of Arms to define the Arms playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Master of Arms."
  },
  {
    "id": "trauma",
    "name": "Trauma",
    "icon": "ability_warrior_trauma",
    "maxPoints": 2,
    "row": 3,
    "col": 3,
    "desc": [
      "Your melee critical strikes inflict Trauma on the target for 15 seconds. While active, the critical strike chance of all attacks against the target is increased by 0.5% for every active Bleed effect currently on the target (up to a maximum of 3%).",
      "1.0% / 6%"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Trauma critically hits.",
    "devCommentary": "We wanted Trauma to define the Arms playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Trauma."
  },
  {
    "id": "imp_hamstring",
    "name": "Improved Hamstring",
    "icon": "ability_shockwave",
    "maxPoints": 2,
    "row": 3,
    "col": 2,
    "desc": [
      "Gives your Hamstring ability a 7% chance to immobilize the target for 5 seconds.",
      "15%"
    ],
    "statScaling": "Provides flat scaling independent of your fury rating.",
    "loreOrigins": "A lost secret of the gladiatorial arenas that weaponizes the pure essence of Improved Hamstring.",
    "synergies": [
      "Creates a devastating synergy when you weave Improved Hamstring between auto-attacks.",
      "Acts as a foundational pillar for any brutal oriented build."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Your glove rune now gains an additional 10% effectiveness passively.",
    "devCommentary": "We wanted Improved Hamstring to define the Arms playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Improved Hamstring."
  },
  {
    "id": "mortal_strike",
    "name": "Mortal Strike",
    "icon": "ability_warrior_punishingblow",
    "maxPoints": 1,
    "row": 4,
    "col": 1,
    "requires": {
      "id": "sweeping_strikes",
      "points": 1
    },
    "desc": [
      "A vicious strike that deals weapon damage plus X and wounds the target, reducing the effectiveness of any healing by 50% for 10 seconds. 6 second cooldown."
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Mortal Strike was perfected over centuries.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Your glove rune now gains an additional 10% effectiveness passively.",
    "devCommentary": "We wanted Mortal Strike to define the Arms playstyle at all levels.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Mortal Strike attack."
  },
  {
    "id": "second_wind",
    "name": "Second Wind",
    "icon": "spell_nature_healingway",
    "maxPoints": 2,
    "row": 4,
    "col": 2,
    "desc": [
      "Whenever you are struck by a stun or immobilize effect, you generate 10 rage and 5% of your total health over 10 seconds.",
      "20 rage / 10% health"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Second Wind represents the pinnacle of the class.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Second Wind.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Second Wind."
  },
  {
    "id": "blood_frenzy",
    "name": "Blood Frenzy",
    "icon": "ability_warrior_bloodfrenzy",
    "maxPoints": 2,
    "row": 4,
    "col": 0,
    "desc": [
      "Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 2%.",
      "4%"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Blood Frenzy critically hits.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "The ground shatters as the brutal power of Blood Frenzy courses through you."
  },
  {
    "id": "strength_of_arms",
    "name": "Strength of Arms",
    "icon": "ability_warrior_strengthofarms",
    "maxPoints": 2,
    "row": 5,
    "col": 0,
    "desc": [
      "Increases your Strength and Stamina by 2% and reduces the cooldown of your Overpower by 1 second.",
      "4% / 2 seconds"
    ],
    "statScaling": "Provides flat scaling independent of your fury rating.",
    "loreOrigins": "A lost secret of the gladiatorial arenas that weaponizes the pure essence of Strength of Arms.",
    "synergies": [
      "Creates a devastating synergy when you weave Strength of Arms between auto-attacks.",
      "Acts as a foundational pillar for any brutal oriented build."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Your glove rune now gains an additional 10% effectiveness passively.",
    "devCommentary": "A community favorite that we brought back and modernized for Classic+.",
    "visualEffect": "Your Strength of Arms leaves a lingering trail of fury in your wake."
  },
  {
    "id": "sudden_death",
    "name": "Sudden Death",
    "icon": "ability_warrior_improveddisciplines",
    "maxPoints": 3,
    "row": 5,
    "col": 1,
    "requires": {
      "id": "mortal_strike",
      "points": 1
    },
    "desc": [
      "Your melee hits have a 33% chance to allow the use of Execute regardless of the target's health state. In addition, you keep 10 rage after using Execute.",
      "6%",
      "9%"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Sudden Death represents the pinnacle of the class.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Creates a devastating synergy when you weave Sudden Death between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Sudden Death.",
    "devCommentary": "Initially, Sudden Death was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "The ground shatters as the brutal power of Sudden Death courses through you."
  },
  {
    "id": "juggernaut",
    "name": "Juggernaut",
    "icon": "ability_bullrush",
    "maxPoints": 2,
    "row": 5,
    "col": 2,
    "desc": [
      "You can now use Charge while in combat. Following a Charge, your next Mortal Strike or Slam has an additional 15% critical strike chance.",
      "30%"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Juggernaut represents the pinnacle of the class.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Creates a devastating synergy when you weave Juggernaut between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Juggernaut.",
    "devCommentary": "A community favorite that we brought back and modernized for Classic+.",
    "visualEffect": "Casting Juggernaut temporarily wreathes your character in brutal energy."
  },
  {
    "id": "bladestorm",
    "name": "Bladestorm",
    "icon": "ability_warrior_bladestorm",
    "maxPoints": 1,
    "row": 6,
    "col": 1,
    "requires": {
      "id": "sudden_death",
      "points": 3
    },
    "desc": [
      "Instantly Whirlwind up to 4 nearby targets and for the next 8 seconds you will perform a whirlwind attack every 1 second. While under the effects of Bladestorm, you can move but cannot perform any other abilities except Shouts, and you are immune to all movement impairing and loss of control effects. 1.5 minute cooldown."
    ],
    "statScaling": "Provides flat scaling independent of your fury rating.",
    "loreOrigins": "A lost secret of the gladiatorial arenas that weaponizes the pure essence of Bladestorm.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Arms PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Bladestorm critically hits.",
    "devCommentary": "Initially, Bladestorm was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Bladestorm temporarily wreathes your character in brutal energy."
  }
];

export const WARRIOR_PROTECTION_TALENTS: any = [
  {
    "id": "imp_bloodrage",
    "name": "Improved Bloodrage",
    "icon": "ability_racial_bloodrage",
    "maxPoints": 2,
    "row": 0,
    "col": 0,
    "desc": [
      "Increases the instant Rage generated by your Bloodrage ability by 2.",
      "5"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Acts as a foundational pillar for any brutal oriented build."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Improved Bloodrage.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Improved Bloodrage attack."
  },
  {
    "id": "toughness",
    "name": "Toughness",
    "icon": "spell_holy_devotion",
    "maxPoints": 3,
    "row": 0,
    "col": 1,
    "desc": [
      "Increases your armor value from items by 3%.",
      "6%",
      "10%"
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Toughness was perfected over centuries.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "We wanted Toughness to define the Protection playstyle at all levels.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Toughness attack."
  },
  {
    "id": "shield_spec",
    "name": "Shield Specialization",
    "icon": "inv_shield_06",
    "maxPoints": 5,
    "row": 0,
    "col": 2,
    "desc": [
      "Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.",
      "2% / 40%",
      "3% / 60%",
      "4% / 80%",
      "5% / 100%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Shield Specialization.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Shield Specialization attack."
  },
  {
    "id": "iron_will",
    "name": "Iron Will",
    "icon": "spell_magic_magearmor",
    "maxPoints": 3,
    "row": 1,
    "col": 0,
    "desc": [
      "Increases your chance to resist Stun and Charm effects by 10%.",
      "20%",
      "30%"
    ],
    "statScaling": "Provides flat scaling independent of your fury rating.",
    "loreOrigins": "A lost secret of the gladiatorial arenas that weaponizes the pure essence of Iron Will.",
    "synergies": [
      "Creates a devastating synergy when you weave Iron Will between auto-attacks.",
      "Acts as a foundational pillar for any brutal oriented build."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Your glove rune now gains an additional 10% effectiveness passively.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "Your Iron Will leaves a lingering trail of fury in your wake."
  },
  {
    "id": "imp_sunder_armor",
    "name": "Improved Sunder Armor",
    "icon": "ability_warrior_sunder",
    "maxPoints": 3,
    "row": 1,
    "col": 1,
    "desc": [
      "Reduces the rage cost of your Sunder Armor and Devastate abilities by 1.",
      "2",
      "3"
    ],
    "statScaling": "Provides flat scaling independent of your fury rating.",
    "loreOrigins": "A lost secret of the gladiatorial arenas that weaponizes the pure essence of Improved Sunder Armor.",
    "synergies": [
      "Creates a devastating synergy when you weave Improved Sunder Armor between auto-attacks.",
      "Acts as a foundational pillar for any brutal oriented build."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Your glove rune now gains an additional 10% effectiveness passively.",
    "devCommentary": "A community favorite that we brought back and modernized for Classic+.",
    "visualEffect": "Your Improved Sunder Armor leaves a lingering trail of fury in your wake."
  },
  {
    "id": "shield_mastery",
    "name": "Shield Mastery",
    "icon": "ability_warrior_shieldguard",
    "maxPoints": 3,
    "row": 1,
    "col": 2,
    "requires": {
      "id": "shield_spec",
      "points": 5
    },
    "desc": [
      "Increases your block value by 10% and reduces the cooldown of your Shield Block ability by 1 second.",
      "20% / 2 seconds",
      "30% / 3 seconds"
    ],
    "statScaling": "Provides flat scaling independent of your fury rating.",
    "loreOrigins": "A lost secret of the gladiatorial arenas that weaponizes the pure essence of Shield Mastery.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Shield Mastery critically hits.",
    "devCommentary": "A community favorite that we brought back and modernized for Classic+.",
    "visualEffect": "Casting Shield Mastery temporarily wreathes your character in brutal energy."
  },
  {
    "id": "imp_shield_block",
    "name": "Improved Shield Block",
    "icon": "ability_defend",
    "maxPoints": 2,
    "row": 1,
    "col": 3,
    "requires": {
      "id": "shield_spec",
      "points": 5
    },
    "desc": [
      "Allows your Shield Block ability to block an additional attack and increases its duration by 1 second.",
      "2 seconds"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Improved Shield Block between auto-attacks.",
      "Creates a devastating synergy when you weave Improved Shield Block between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "Your Improved Shield Block leaves a lingering trail of fury in your wake."
  },
  {
    "id": "imp_revenge",
    "name": "Improved Revenge",
    "icon": "ability_warrior_revenge",
    "maxPoints": 2,
    "row": 2,
    "col": 0,
    "desc": [
      "Gives your Revenge ability a 25% chance to stun the target for 3 seconds.",
      "50%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Improved Revenge between auto-attacks.",
      "Creates a devastating synergy when you weave Improved Revenge between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "The ground shatters as the brutal power of Improved Revenge courses through you."
  },
  {
    "id": "last_stand",
    "name": "Last Stand",
    "icon": "spell_holy_ashestoashes",
    "maxPoints": 1,
    "row": 2,
    "col": 1,
    "desc": [
      "When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds. After the effect expires, the hit points are lost. 3 minute cooldown."
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Last Stand represents the pinnacle of the class.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Last Stand.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "The ground shatters as the brutal power of Last Stand courses through you."
  },
  {
    "id": "defiance",
    "name": "Defiance",
    "icon": "ability_warrior_innerrage",
    "maxPoints": 3,
    "row": 2,
    "col": 2,
    "desc": [
      "Increases the threat generated by your attacks by 5% while in Defensive Stance.",
      "10%",
      "15%"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Defiance represents the pinnacle of the class.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Defiance.",
    "devCommentary": "Initially, Defiance was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Defiance temporarily wreathes your character in brutal energy."
  },
  {
    "id": "gag_order",
    "name": "Gag Order",
    "icon": "ability_warrior_shieldbash",
    "maxPoints": 2,
    "row": 2,
    "col": 3,
    "desc": [
      "Gives your Shield Bash and Pummel abilities a 50% chance to silence the target for 3 seconds.",
      "100%"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Gag Order represents the pinnacle of the class.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Gag Order.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "Your Gag Order leaves a lingering trail of fury in your wake."
  },
  {
    "id": "one_handed_ws",
    "name": "One-Handed Weapon Specialization",
    "icon": "inv_sword_20",
    "maxPoints": 5,
    "row": 3,
    "col": 0,
    "desc": [
      "Increases the physical damage you deal when a one-handed melee weapon is equipped by 2%.",
      "4%",
      "6%",
      "8%",
      "10%"
    ],
    "statScaling": "Provides flat scaling independent of your fury rating.",
    "loreOrigins": "A lost secret of the gladiatorial arenas that weaponizes the pure essence of One-Handed Weapon Specialization.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever One-Handed Weapon Specialization critically hits.",
    "devCommentary": "We wanted One-Handed Weapon Specialization to define the Protection playstyle at all levels.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your One-Handed Weapon Specialization attack."
  },
  {
    "id": "imp_shield_wall",
    "name": "Improved Shield Wall",
    "icon": "ability_warrior_shieldwall",
    "maxPoints": 2,
    "row": 3,
    "col": 3,
    "desc": [
      "Reduces the cooldown of your Shield Wall ability by 60 seconds and increases its duration by 2 seconds.",
      "120 seconds / 4 seconds"
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Improved Shield Wall was perfected over centuries.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "We wanted Improved Shield Wall to define the Protection playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Improved Shield Wall."
  },
  {
    "id": "incite",
    "name": "Incite",
    "icon": "ability_warrior_incite",
    "maxPoints": 3,
    "row": 3,
    "col": 2,
    "desc": [
      "Increases the critical strike chance of your Heroic Strike, Cleave, and Thunder Clap abilities by 5%.",
      "10%",
      "15%"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Incite critically hits.",
    "devCommentary": "Initially, Incite was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Incite temporarily wreathes your character in brutal energy."
  },
  {
    "id": "imp_defensive_stance",
    "name": "Improved Defensive Stance",
    "icon": "ability_warrior_defensivestance",
    "maxPoints": 2,
    "row": 4,
    "col": 0,
    "desc": [
      "Reduces all spell damage taken while in Defensive Stance by 3%.",
      "6%"
    ],
    "statScaling": "Provides flat scaling independent of your fury rating.",
    "loreOrigins": "A lost secret of the gladiatorial arenas that weaponizes the pure essence of Improved Defensive Stance.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Improved Defensive Stance critically hits.",
    "devCommentary": "Initially, Improved Defensive Stance was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Improved Defensive Stance temporarily wreathes your character in brutal energy."
  },
  {
    "id": "concussion_blow",
    "name": "Concussion Blow",
    "icon": "ability_thunderbolt",
    "maxPoints": 1,
    "row": 4,
    "col": 1,
    "requires": {
      "id": "last_stand",
      "points": 1
    },
    "desc": [
      "Stuns the opponent for 5 seconds and deals damage based on your attack power. 30 second cooldown."
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Concussion Blow was perfected over centuries.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Your glove rune now gains an additional 10% effectiveness passively.",
    "devCommentary": "We wanted Concussion Blow to define the Protection playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Concussion Blow."
  },
  {
    "id": "vitality",
    "name": "Vitality",
    "icon": "spell_nature_undyingstrength",
    "maxPoints": 3,
    "row": 4,
    "col": 2,
    "desc": [
      "Increases your total Stamina by 2% and your total Strength by 4%.",
      "4% / 8%",
      "6% / 12%"
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Vitality was perfected over centuries.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Your glove rune now gains an additional 10% effectiveness passively.",
    "devCommentary": "Initially, Vitality was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "The ground shatters as the brutal power of Vitality courses through you."
  },
  {
    "id": "damage_shield",
    "name": "Damage Shield",
    "icon": "inv_shield_05",
    "maxPoints": 2,
    "row": 5,
    "col": 0,
    "desc": [
      "Whenever you take damage from or block a melee attack, you cause physical damage equal to 10% of your Block Value.",
      "20%"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Damage Shield critically hits.",
    "devCommentary": "Initially, Damage Shield was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "The ground shatters as the brutal power of Damage Shield courses through you."
  },
  {
    "id": "critical_block",
    "name": "Critical Block",
    "icon": "ability_warrior_criticalblock",
    "maxPoints": 3,
    "row": 5,
    "col": 1,
    "desc": [
      "Your successful blocks have a 20% chance to block double the normal amount.",
      "40%",
      "60%"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Critical Block represents the pinnacle of the class.",
    "synergies": [
      "Acts as a foundational pillar for any brutal oriented build.",
      "Creates a devastating synergy when you weave Critical Block between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Critical Block.",
    "devCommentary": "We wanted Critical Block to define the Protection playstyle at all levels.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Critical Block attack."
  },
  {
    "id": "warbringer",
    "name": "Warbringer",
    "icon": "ability_warrior_warbringer",
    "maxPoints": 1,
    "row": 5,
    "col": 2,
    "desc": [
      "Your Charge, Intercept, and Intervene abilities are now usable while in combat and in any stance."
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Warbringer between auto-attacks.",
      "Creates a devastating synergy when you weave Warbringer between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "We wanted Warbringer to define the Protection playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Warbringer."
  },
  {
    "id": "devastate",
    "name": "Devastate",
    "icon": "inv_sword_11",
    "maxPoints": 1,
    "row": 6,
    "col": 1,
    "requires": {
      "id": "critical_block",
      "points": 3
    },
    "desc": [
      "Sunder the target's armor causing the Sunder Armor effect. In addition, causes 50% of weapon damage plus X for each application of Sunder Armor on the target. The threat generated by this attack is increased by your attack power."
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Devastate was perfected over centuries.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Protection PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "A community favorite that we brought back and modernized for Classic+.",
    "visualEffect": "Casting Devastate temporarily wreathes your character in brutal energy."
  }
];

export const WARRIOR_FURY_TALENTS: any = [
  {
    "id": "unbridled_wrath",
    "name": "Unbridled Wrath",
    "icon": "spell_nature_stoneclawtotem",
    "maxPoints": 3,
    "row": 0,
    "col": 0,
    "desc": [
      "Gives you a 15% chance to generate an additional Rage point when you deal melee damage with a weapon.",
      "30%",
      "45%"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Unbridled Wrath critically hits.",
    "devCommentary": "We wanted Unbridled Wrath to define the Fury playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Unbridled Wrath."
  },
  {
    "id": "cruelty",
    "name": "Cruelty",
    "icon": "ability_rogue_eviscerate",
    "maxPoints": 5,
    "row": 0,
    "col": 1,
    "desc": [
      "Increases your chance to get a critical strike with melee weapons by 0.6%.",
      "1.2%",
      "1.8%",
      "2.4%",
      "3.0%"
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Cruelty represents the pinnacle of the class.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Cruelty.",
    "devCommentary": "We wanted Cruelty to define the Fury playstyle at all levels.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Cruelty attack."
  },
  {
    "id": "imp_battle_shout",
    "name": "Improved Battle Shout",
    "icon": "ability_warrior_battleshout",
    "maxPoints": 2,
    "row": 0,
    "col": 2,
    "desc": [
      "Increases the melee attack power bonus of your Battle Shout by 13%.",
      "25%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Improved Battle Shout between auto-attacks.",
      "Creates a devastating synergy when you weave Improved Battle Shout between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "Initially, Improved Battle Shout was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Improved Battle Shout temporarily wreathes your character in brutal energy."
  },
  {
    "id": "imp_cleave",
    "name": "Improved Cleave",
    "icon": "ability_warrior_cleave",
    "maxPoints": 3,
    "row": 1,
    "col": 0,
    "desc": [
      "Increases the bonus damage done by your Cleave by 40%.",
      "80%",
      "120%"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Reduces the cooldown of your leg rune by 2 seconds whenever Improved Cleave critically hits.",
    "devCommentary": "Initially, Improved Cleave was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "The ground shatters as the brutal power of Improved Cleave courses through you."
  },
  {
    "id": "imp_demoralizing_shout",
    "name": "Improved Demoralizing Shout",
    "icon": "ability_warrior_warcry",
    "maxPoints": 2,
    "row": 1,
    "col": 1,
    "desc": [
      "Increases the melee AP reduction of Demoralizing Shout by 20% and increases the daze duration of the baseline Piercing Howl by 1 sec.",
      "40% / 2 sec"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Improved Demoralizing Shout between auto-attacks.",
      "Creates a devastating synergy when you weave Improved Demoralizing Shout between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "Your Improved Demoralizing Shout leaves a lingering trail of fury in your wake."
  },
  {
    "id": "enrage",
    "name": "Enrage",
    "icon": "spell_shadow_unholyfrenzy",
    "maxPoints": 3,
    "row": 1,
    "col": 2,
    "desc": [
      "Gives you a 10% melee damage bonus for 12 seconds up to a maximum of 12 swings after being the victim of a critical strike.",
      "20%",
      "30%"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Acts as a foundational pillar for any brutal oriented build."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Enrage.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "A spectral projection of Varok Saurfang briefly mirrors your Enrage attack."
  },
  {
    "id": "blood_craze",
    "name": "Blood Craze",
    "icon": "spell_shadow_summonimp",
    "maxPoints": 3,
    "row": 1,
    "col": 3,
    "desc": [
      "Regenerates 2% of your total Health over 6 seconds after being the victim of a critical strike.",
      "4%",
      "6%"
    ],
    "statScaling": "Inherits 50% of your weapon's base damage as brutal power.",
    "loreOrigins": "An instinctual manifestation of fury, allowing you to crush your foes effortlessly.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Acts as a foundational pillar for any brutal oriented build."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Enhances your chest rune to pulse with brutal energy upon casting Blood Craze.",
    "devCommentary": "Initially, Blood Craze was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Blood Craze temporarily wreathes your character in brutal energy."
  },
  {
    "id": "dual_wield_spec",
    "name": "Dual Wield Specialization",
    "icon": "ability_dualwield",
    "maxPoints": 5,
    "row": 2,
    "col": 0,
    "desc": [
      "Increases the damage done by your offhand melee weapon by 5%.",
      "10%",
      "15%",
      "20%",
      "25%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Dual Wield Specialization between auto-attacks.",
      "Creates a devastating synergy when you weave Dual Wield Specialization between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "Initially, Dual Wield Specialization was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Dual Wield Specialization temporarily wreathes your character in brutal energy."
  },
  {
    "id": "death_wish",
    "name": "Death Wish",
    "icon": "spell_shadow_deathpact",
    "maxPoints": 1,
    "row": 2,
    "col": 1,
    "desc": [
      "When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%. Lasts 30 sec. 3 minute cooldown."
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Death Wish was perfected over centuries.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "The ground shatters as the brutal power of Death Wish courses through you."
  },
  {
    "id": "imp_execute",
    "name": "Improved Execute",
    "icon": "inv_sword_48",
    "maxPoints": 2,
    "row": 2,
    "col": 3,
    "desc": [
      "Reduces the Rage cost of your Execute ability by 2.",
      "5"
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Improved Execute was perfected over centuries.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "A community favorite that we brought back and modernized for Classic+.",
    "visualEffect": "Your Improved Execute leaves a lingering trail of fury in your wake."
  },
  {
    "id": "battle_trance",
    "name": "Battle Trance",
    "icon": "spell_nature_bloodlust",
    "maxPoints": 2,
    "row": 3,
    "col": 0,
    "desc": [
      "Your melee critical strikes increase your melee attack power by 5% for 10 seconds.",
      "10%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Battle Trance between auto-attacks.",
      "Creates a devastating synergy when you weave Battle Trance between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "We wanted Battle Trance to define the Fury playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Battle Trance."
  },
  {
    "id": "flurry",
    "name": "Flurry",
    "icon": "ability_ghoulfrenzy",
    "maxPoints": 5,
    "row": 3,
    "col": 2,
    "requires": {
      "id": "enrage",
      "points": 3
    },
    "desc": [
      "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
      "15%",
      "20%",
      "25%",
      "30%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Flurry.",
    "devCommentary": "Initially, Flurry was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "Casting Flurry temporarily wreathes your character in brutal energy."
  },
  {
    "id": "imp_slam",
    "name": "Improved Slam",
    "icon": "ability_warrior_decisivestrike",
    "maxPoints": 2,
    "row": 3,
    "col": 3,
    "desc": [
      "Reduces the cast time of your Slam ability by 0.5 seconds.",
      "1.0 seconds"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Improved Slam.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "Your Improved Slam leaves a lingering trail of fury in your wake."
  },
  {
    "id": "bloodthirst",
    "name": "Bloodthirst",
    "icon": "spell_nature_bloodlust",
    "maxPoints": 1,
    "row": 4,
    "col": 1,
    "requires": {
      "id": "death_wish",
      "points": 1
    },
    "desc": [
      "Instantly attacks the target causing damage equal to 45% of your attack power. In addition, the next 5 successful melee attacks will restore health. 6 second cooldown."
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Bloodthirst.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Bloodthirst."
  },
  {
    "id": "precision",
    "name": "Precision",
    "icon": "ability_marksmanship",
    "maxPoints": 3,
    "row": 4,
    "col": 2,
    "desc": [
      "Increases your chance to hit with melee weapons by 1%.",
      "2%",
      "3%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Precision.",
    "devCommentary": "A community favorite that we brought back and modernized for Classic+.",
    "visualEffect": "Casting Precision temporarily wreathes your character in brutal energy."
  },
  {
    "id": "furious_attacks",
    "name": "Furious Attacks",
    "icon": "ability_warrior_furiousresolve",
    "maxPoints": 2,
    "row": 4,
    "col": 0,
    "desc": [
      "Your normal melee attacks have a chance to reduce all healing done to the target by 25% for 10 seconds.",
      "50%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Pairs flawlessly with high critical strike rating for maximum fury output.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Furious Attacks.",
    "devCommentary": "Initially, Furious Attacks was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "The ground shatters as the brutal power of Furious Attacks courses through you."
  },
  {
    "id": "enraged_regeneration",
    "name": "Enraged Regeneration",
    "icon": "ability_warrior_focusedrage",
    "maxPoints": 2,
    "row": 4,
    "col": 3,
    "desc": [
      "Allows you to regenerate 10% of your total health over 10 seconds while Enraged.",
      "20%"
    ],
    "statScaling": "Gains a 15% bonus scaling from your primary brutal stats.",
    "loreOrigins": "A forbidden brutal art that utilizes fury to overwhelm enemies.",
    "synergies": [
      "Creates a devastating synergy when you weave Enraged Regeneration between auto-attacks.",
      "Creates a devastating synergy when you weave Enraged Regeneration between auto-attacks."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "Initially, Enraged Regeneration was too weak, so we gave it massive brutal scaling.",
    "visualEffect": "The ground shatters as the brutal power of Enraged Regeneration courses through you."
  },
  {
    "id": "bloodsurge",
    "name": "Bloodsurge",
    "icon": "ability_warrior_bloodsurge",
    "maxPoints": 2,
    "row": 5,
    "col": 0,
    "desc": [
      "Your Heroic Strike, Bloodthirst, and Whirlwind hits have a 10% chance to make your next Slam instant and cost no rage.",
      "20%"
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Bloodsurge was perfected over centuries.",
    "synergies": [
      "Provides unmatched utility when combined with other crush abilities.",
      "Dramatically increases the power spike of your brutal cooldowns."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Your glove rune now gains an additional 10% effectiveness passively.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "Your Bloodsurge leaves a lingering trail of fury in your wake."
  },
  {
    "id": "intensify_rage",
    "name": "Intensify Rage",
    "icon": "ability_warrior_endlessrage",
    "maxPoints": 2,
    "row": 5,
    "col": 2,
    "desc": [
      "Reduces the cooldown of your Bloodrage, Berserker Rage, Recklessness, and Death Wish abilities by 11%.",
      "22%"
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Intensify Rage was perfected over centuries.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "This serves as the ultimate high-risk, high-reward fury ability.",
    "visualEffect": "Your Intensify Rage leaves a lingering trail of fury in your wake."
  },
  {
    "id": "imp_berserker_stance",
    "name": "Improved Berserker Stance",
    "icon": "ability_warrior_innerrage",
    "maxPoints": 3,
    "row": 5,
    "col": 3,
    "desc": [
      "Increases Attack Power by 3% and reduces threat generated by 10% while in Berserker Stance.",
      "6% / 20%",
      "10% / 30%"
    ],
    "statScaling": "Scales directly with your total fury power rating.",
    "loreOrigins": "Originally devised in the gladiatorial arenas, the technique of Improved Berserker Stance was perfected over centuries.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Pairs flawlessly with high critical strike rating for maximum fury output."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Causes your helm rune to trigger a secondary fury effect.",
    "devCommentary": "We wanted Improved Berserker Stance to define the Fury playstyle at all levels.",
    "visualEffect": "A massive burst of fury erupts from the target upon the impact of Improved Berserker Stance."
  },
  {
    "id": "rampage",
    "name": "Rampage",
    "icon": "ability_warrior_rampage",
    "maxPoints": 1,
    "row": 6,
    "col": 1,
    "requires": {
      "id": "bloodthirst",
      "points": 1
    },
    "desc": [
      "Unleashes a devastating combo, instantly striking the target with both weapons for 100% weapon damage and increasing your melee AP by 10% for 15 sec. This attack cannot be dodged, parried, or blocked. 30 Rage, 30 sec cd."
    ],
    "statScaling": "Coefficient scales with both spell damage and fury mastery.",
    "loreOrigins": "Passed down by Varok Saurfang, this mastery of Rampage represents the pinnacle of the class.",
    "synergies": [
      "Dramatically increases the power spike of your brutal cooldowns.",
      "Provides unmatched utility when combined with other crush abilities."
    ],
    "recommendedBuilds": [
      "Deep Fury PvE",
      "Hybrid brutal PvP"
    ],
    "runeInteractions": "Modifies your bracer rune to synergize directly with Rampage.",
    "devCommentary": "Designed to smooth out the rotation of brutal specs in long encounters.",
    "visualEffect": "The ground shatters as the brutal power of Rampage courses through you."
  }
];

export const CHANGELOG: string[] = [
  "General Changes",
  "Design Philosophy: Warrior talent trees have been heavily compressed and modernized, bringing WotLK-tier fluidity to the Vanilla baseline. Point bloat has been slashed across all specs.",
  "Piercing Howl: This ability has been made baseline for all Warriors.",
  "Arms",
  "Identity: Master of tactical positioning, huge two-handed weapon bursts, and bleeds, now featuring greatly compressed weapon specializations.",
  "Core Foundation: Improved Rend, Tactical Mastery (moved to tier 1), Improved Charge grouped in Tier 1.",
  "Cross-Pollination: Iron Will, Improved Thunder Clap, Improved Overpower, Improved Heroic Strike organized in Tier 2.",
  "Sweeping Strikes: Moved down to serve as the 11-point anchor.",
  "Output: Deep Wounds, Impale, Two-Handed Weapon Specialization organized in Tier 3.",
  "Master of Arms: Consolidates all four previous weapon specializations into a single 5-point node in Tier 4.",
  "Mortal Strike: Positioned aggressively as the 21-point anchor.",
  "The Active Engine: Second Wind, Blood Frenzy organized in Tier 5 for PvP survival and physical damage scaling.",
  "Burst Mechanics: Sudden Death, Juggernaut organized in Tier 6.",
  "Bladestorm: Added as the 31-point capstone, providing massive AoE threat and immune-spin capability.",
  "Fury",
  "Identity: A bloodthirsty, dual-wielding berserker that scales furiously with critical strikes, given much better inherent sustain.",
  "Core Foundation: Booming Voice, Cruelty, Improved Demoralizing Shout grouped in Tier 1.",
  "Cross-Pollination: Unbridled Wrath, Improved Cleave, Blood Craze organized in Tier 2.",
  "Death Wish: Moved down to serve as the 11-point anchor.",
  "Output: Improved Execute, Enrage organized in Tier 3.",
  "Flurry: Kept as the defining Tier 4 output modifier.",
  "Bloodthirst: Positioned as the 21-point anchor.",
  "The Active Engine: Dual Wield Specialization, Precision organized in Tier 5.",
  "Burst Mechanics: Furious Attacks, Bloodsurge organized in Tier 6.",
  "Rampage: Added as the 31-point capstone mini-cooldown.",
  "Protection",
  "Identity: Transitions from a slow, rage-starved tank into an impenetrable wall of steel equipped with excellent mobility and passive reflection.",
  "Core Foundation: Improved Bloodrage, Shield Specialization, Improved Thunder Clap grouped in Tier 1.",
  "Cross-Pollination: Improved Revenge, Toughness, Last Stand organized in Tier 2.",
  "Concussion Blow: Moved down to serve as the 11-point anchor.",
  "Output: Shield Mastery, One-Handed Weapon Specialization, Improved Disarm organized in Tier 3.",
  "Shield Slam: Positioned as the 21-point anchor.",
  "The Active Engine: Focused Rage, Vitality organized in Tier 5 for sweeping stat bonuses.",
  "Mobility & Reaction: Warbringer, Devastate organized in Tier 6.",
  "Shockwave: Added as the 31-point capstone for massive AoE control and threat."
];
