import { Talent } from '../types/talents';

export const WARRIOR_ARMS_TALENTS: Talent[] = [
  // Tier 1
  { id: 'tactical_mastery', name: 'Tactical Mastery', icon: 'spell_nature_enchantarmor', maxPoints: 2, row: 0, col: 0, desc: ["You retain up to 15 of your Rage points when you change stances.", "30"] },
  { id: 'deflection', name: 'Deflection', icon: 'ability_parry', maxPoints: 5, row: 0, col: 1, desc: ["Increases your Parry chance by 1%.", "2%", "3%", "4%", "5%"] },
  { id: 'imp_rend', name: 'Improved Rend', icon: 'ability_gouge', maxPoints: 3, row: 0, col: 2, desc: ["Increases the bleed damage done by your Rend ability by 15% and increases its duration by 2 seconds.", "25% / 4 seconds", "35% / 6 seconds"] },

  // Tier 2
  { id: 'imp_charge', name: 'Improved Charge', icon: 'ability_warrior_charge', maxPoints: 2, row: 1, col: 0, desc: ["Increases the amount of rage generated by your Charge ability by 10.", "20"] },
  { id: 'imp_overpower', name: 'Improved Overpower', icon: 'inv_sword_05', maxPoints: 3, row: 1, col: 1, desc: ["Increases the critical strike chance of your Overpower ability by 17%.", "34%", "50%"] },
  { id: 'deep_wounds', name: 'Deep Wounds', icon: 'ability_backstab', maxPoints: 3, row: 1, col: 2, requires: { id: 'imp_rend', points: 3 }, desc: ["Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 seconds.", "40%", "60%"] },
  { id: 'imp_heroic_strike', name: 'Improved Heroic Strike', icon: 'ability_rogue_ambush', maxPoints: 2, row: 1, col: 3, desc: ["Reduces the cost of your Heroic Strike ability by 1 rage point.", "2 rage points"] },

  // Tier 3
  { id: 'two_handed_ws', name: 'Two-Handed Weapon Specialization', icon: 'inv_axe_09', maxPoints: 5, row: 2, col: 0, desc: ["Increases the damage you deal with two-handed melee weapons by 1%.", "2%", "3%", "4%", "5%"] },
  { id: 'sweeping_strikes', name: 'Sweeping Strikes', icon: 'ability_rogue_slicedice', maxPoints: 1, row: 2, col: 1, desc: ["Your next 5 melee attacks strike an additional nearby opponent. 30 second cooldown."] },
  { id: 'impale', name: 'Impale', icon: 'ability_searingarrow', maxPoints: 2, row: 2, col: 2, requires: { id: 'deep_wounds', points: 3 }, desc: ["Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.", "20%"] },

  // Tier 4
  { id: 'master_of_arms', name: 'Master of Arms', icon: 'inv_sword_27', maxPoints: 5, row: 3, col: 0, desc: ["Grants specialized bonuses based on your equipped melee weapon: Swords (1% chance for extra attack), Axes/Polearms (1% increased critical strike chance), Maces (ignore 3% armor, 1% stun chance).", "Swords (2%), Axes/Polearms (2%), Maces (6% armor, 2% stun).", "Swords (3%), Axes/Polearms (3%), Maces (9% armor, 3% stun).", "Swords (4%), Axes/Polearms (4%), Maces (12% armor, 4% stun).", "Swords (5%), Axes/Polearms (5%), Maces (15% armor, 5% stun)."] },
  { id: 'trauma', name: 'Trauma', icon: 'ability_warrior_trauma', maxPoints: 2, row: 3, col: 1, desc: ["Your melee critical strikes cause the target to take 15% additional damage from bleed effects.", "30%"] },
  { id: 'imp_hamstring', name: 'Improved Hamstring', icon: 'ability_shockwave', maxPoints: 2, row: 3, col: 2, desc: ["Gives your Hamstring ability a 7% chance to immobilize the target for 5 seconds.", "15%"] },

  // Tier 5
  { id: 'mortal_strike', name: 'Mortal Strike', icon: 'ability_warrior_punishingblow', maxPoints: 1, row: 4, col: 1, requires: { id: 'sweeping_strikes', points: 1 }, desc: ["A vicious strike that deals weapon damage plus X and wounds the target, reducing the effectiveness of any healing by 50% for 10 seconds. 6 second cooldown."] },
  { id: 'second_wind', name: 'Second Wind', icon: 'spell_nature_healingway', maxPoints: 2, row: 4, col: 2, desc: ["Whenever you are struck by a stun or immobilize effect, you generate 10 rage and 5% of your total health over 10 seconds.", "20 rage / 10% health"] },
  { id: 'blood_frenzy', name: 'Blood Frenzy', icon: 'ability_warrior_bloodfrenzy', maxPoints: 2, row: 4, col: 0, desc: ["Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 2%.", "4%"] },

  // Tier 6
  { id: 'strength_of_arms', name: 'Strength of Arms', icon: 'ability_warrior_strengthofarms', maxPoints: 2, row: 5, col: 0, desc: ["Increases your Strength and Stamina by 2% and reduces the cooldown of your Overpower by 1 second.", "4% / 2 seconds"] },
  { id: 'sudden_death', name: 'Sudden Death', icon: 'ability_warrior_improveddisciplines', maxPoints: 3, row: 5, col: 1, requires: { id: 'mortal_strike', points: 1 }, desc: ["Your melee hits have a 33% chance to allow the use of Execute regardless of the target's health state. In addition, you keep 10 rage after using Execute.", "6%", "9%"] },
  { id: 'juggernaut', name: 'Juggernaut', icon: 'ability_bullrush', maxPoints: 2, row: 5, col: 2, desc: ["You can now use Charge while in combat. Following a Charge, your next Mortal Strike or Slam has an additional 15% critical strike chance.", "30%"] },

  // Tier 7
  { id: 'bladestorm', name: 'Bladestorm', icon: 'ability_warrior_bladestorm', maxPoints: 1, row: 6, col: 1, requires: { id: 'sudden_death', points: 3 }, desc: ["Instantly Whirlwind up to 4 nearby targets and for the next 8 seconds you will perform a whirlwind attack every 1 second. While under the effects of Bladestorm, you can move but cannot perform any other abilities except Shouts, and you are immune to all movement impairing and loss of control effects. 1.5 minute cooldown."] }
];

export const WARRIOR_PROTECTION_TALENTS: Talent[] = [
  // Tier 1
  { id: 'imp_bloodrage', name: 'Improved Bloodrage', icon: 'ability_racial_bloodrage', maxPoints: 2, row: 0, col: 0, desc: ["Increases the instant Rage generated by your Bloodrage ability by 2.", "5"] },
  { id: 'toughness', name: 'Toughness', icon: 'spell_holy_devotion', maxPoints: 3, row: 0, col: 1, desc: ["Increases your armor value from items by 3%.", "6%", "10%"] },
  { id: 'shield_spec', name: 'Shield Specialization', icon: 'inv_shield_06', maxPoints: 5, row: 0, col: 2, desc: ["Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.", "2% / 40%", "3% / 60%", "4% / 80%", "5% / 100%"] },

  // Tier 2
  { id: 'iron_will', name: 'Iron Will', icon: 'spell_magic_magearmor', maxPoints: 3, row: 1, col: 0, desc: ["Increases your chance to resist Stun and Charm effects by 10%.", "20%", "30%"] },
  { id: 'imp_sunder_armor', name: 'Improved Sunder Armor', icon: 'ability_warrior_sunder', maxPoints: 3, row: 1, col: 1, desc: ["Reduces the rage cost of your Sunder Armor and Devastate abilities by 1.", "2", "3"] },
  { id: 'defiance', name: 'Defiance', icon: 'ability_warrior_defiance', maxPoints: 3, row: 1, col: 2, desc: ["Increases the threat generated by your attacks by 5% while in Defensive Stance.", "10%", "15%"] },
  { id: 'imp_shield_block', name: 'Improved Shield Block', icon: 'ability_defend', maxPoints: 2, row: 1, col: 3, requires: { id: 'shield_spec', points: 5 }, desc: ["Allows your Shield Block ability to block an additional attack and increases its duration by 1 second.", "2 seconds"] },

  // Tier 3
  { id: 'imp_revenge', name: 'Improved Revenge', icon: 'ability_warrior_revenge', maxPoints: 2, row: 2, col: 0, desc: ["Gives your Revenge ability a 25% chance to stun the target for 3 seconds.", "50%"] },
  { id: 'last_stand', name: 'Last Stand', icon: 'spell_holy_ashestoashes', maxPoints: 1, row: 2, col: 1, desc: ["When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds. After the effect expires, the hit points are lost. 3 minute cooldown."] },
  { id: 'shield_mastery', name: 'Shield Mastery', icon: 'ability_warrior_shieldguard', maxPoints: 3, row: 2, col: 2, requires: { id: 'shield_spec', points: 5 }, desc: ["Increases your block value by 10% and reduces the cooldown of your Shield Block ability by 1 second.", "20% / 2 seconds", "30% / 3 seconds"] },
  { id: 'gag_order', name: 'Gag Order', icon: 'ability_warrior_shieldbash', maxPoints: 2, row: 2, col: 3, desc: ["Gives your Shield Bash and Pummel abilities a 50% chance to silence the target for 3 seconds.", "100%"] },

  // Tier 4
  { id: 'one_handed_ws', name: 'One-Handed Weapon Specialization', icon: 'inv_sword_20', maxPoints: 5, row: 3, col: 0, desc: ["Increases the physical damage you deal when a one-handed melee weapon is equipped by 2%.", "4%", "6%", "8%", "10%"] },
  { id: 'imp_shield_wall', name: 'Improved Shield Wall', icon: 'ability_warrior_shieldwall', maxPoints: 2, row: 3, col: 1, desc: ["Reduces the cooldown of your Shield Wall ability by 60 seconds and increases its duration by 2 seconds.", "120 seconds / 4 seconds"] },
  { id: 'incite', name: 'Incite', icon: 'ability_warrior_incite', maxPoints: 3, row: 3, col: 2, desc: ["Increases the critical strike chance of your Heroic Strike, Cleave, and Thunder Clap abilities by 5%.", "10%", "15%"] },

  // Tier 5
  { id: 'imp_defensive_stance', name: 'Improved Defensive Stance', icon: 'ability_warrior_defensivestance', maxPoints: 2, row: 4, col: 0, desc: ["Reduces all spell damage taken while in Defensive Stance by 3%.", "6%"] },
  { id: 'concussion_blow', name: 'Concussion Blow', icon: 'ability_thunderbolt', maxPoints: 1, row: 4, col: 1, requires: { id: 'last_stand', points: 1 }, desc: ["Stuns the opponent for 5 seconds and deals damage based on your attack power. 30 second cooldown."] },
  { id: 'vitality', name: 'Vitality', icon: 'spell_nature_undyingstrength', maxPoints: 3, row: 4, col: 2, desc: ["Increases your total Stamina by 2% and your total Strength by 4%.", "4% / 8%", "6% / 12%"] },

  // Tier 6
  { id: 'damage_shield', name: 'Damage Shield', icon: 'inv_shield_05', maxPoints: 2, row: 5, col: 0, desc: ["Whenever you take damage from or block a melee attack, you cause physical damage equal to 10% of your Block Value.", "20%"] },
  { id: 'critical_block', name: 'Critical Block', icon: 'ability_warrior_criticalblock', maxPoints: 3, row: 5, col: 1, desc: ["Your successful blocks have a 20% chance to block double the normal amount.", "40%", "60%"] },
  { id: 'warbringer', name: 'Warbringer', icon: 'ability_warrior_warbringer', maxPoints: 1, row: 5, col: 2, desc: ["Your Charge, Intercept, and Intervene abilities are now usable while in combat and in any stance."] },

  // Tier 7
  { id: 'devastate', name: 'Devastate', icon: 'inv_sword_11', maxPoints: 1, row: 6, col: 1, requires: { id: 'critical_block', points: 3 }, desc: ["Sunder the target's armor causing the Sunder Armor effect. In addition, causes 50% of weapon damage plus X for each application of Sunder Armor on the target. The threat generated by this attack is increased by your attack power."] }
];

export const WARRIOR_FURY_TALENTS: Talent[] = [
  // Tier 1
  { id: 'cruelty', name: 'Cruelty', icon: 'ability_rogue_eviscerate', maxPoints: 5, row: 0, col: 1, desc: ["Increases your chance to get a critical strike with melee weapons by 1%.", "2%", "3%", "4%", "5%"] },
  { id: 'unbridled_wrath', name: 'Unbridled Wrath', icon: 'spell_nature_stoneclawtotem', maxPoints: 3, row: 0, col: 2, desc: ["Gives you a 15% chance to generate an additional Rage point when you deal melee damage with a weapon.", "30%", "45%"] },
  { id: 'imp_battle_shout', name: 'Improved Battle Shout', icon: 'ability_warrior_battleshout', maxPoints: 2, row: 0, col: 0, desc: ["Increases the melee attack power bonus of your Battle Shout by 13%.", "25%"] },

  // Tier 2
  { id: 'enrage', name: 'Enrage', icon: 'spell_shadow_unholyfrenzy', maxPoints: 3, row: 1, col: 1, requires: { id: 'cruelty', points: 5 }, desc: ["Gives you a 10% melee damage bonus for 12 seconds up to a maximum of 12 swings after being the victim of a critical strike.", "20%", "30%"] },
  { id: 'imp_cleave', name: 'Improved Cleave', icon: 'ability_warrior_cleave', maxPoints: 3, row: 1, col: 2, desc: ["Increases the bonus damage done by your Cleave by 40%.", "80%", "120%"] },
  { id: 'imp_demoralizing_shout', name: 'Improved Demoralizing Shout', icon: 'ability_warrior_warcry', maxPoints: 2, row: 1, col: 0, desc: ["Increases the melee AP reduction of Demoralizing Shout by 20% and increases the daze duration of the baseline Piercing Howl by 1 sec.", "40% / 2 sec"] },
  { id: 'blood_craze', name: 'Blood Craze', icon: 'spell_shadow_summonimp', maxPoints: 2, row: 1, col: 3, desc: ["Regenerates 3% of your total Health over 6 seconds after being the victim of a critical strike.", "6%"] },

  // Tier 3
  { id: 'imp_slam', name: 'Improved Slam', icon: 'ability_warrior_decisivestrike', maxPoints: 2, row: 2, col: 0, desc: ["Reduces the cast time of your Slam ability by 0.5 seconds.", "1.0 seconds"] },
  { id: 'death_wish', name: 'Death Wish', icon: 'spell_shadow_deathpact', maxPoints: 1, row: 2, col: 1, desc: ["When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%. Lasts 30 sec. 3 minute cooldown."] },
  { id: 'dual_wield_spec', name: 'Dual Wield Specialization', icon: 'ability_dualwield', maxPoints: 5, row: 2, col: 2, desc: ["Increases the damage done by your offhand melee weapon by 5%.", "10%", "15%", "20%", "25%"] },
  { id: 'imp_execute', name: 'Improved Execute', icon: 'inv_sword_48', maxPoints: 2, row: 2, col: 3, desc: ["Reduces the Rage cost of your Execute ability by 2.", "5"] },

  // Tier 4
  { id: 'flurry', name: 'Flurry', icon: 'ability_ghoulfrenzy', maxPoints: 5, row: 3, col: 0, requires: { id: 'enrage', points: 3 }, desc: ["Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.", "15%", "20%", "25%", "30%"] },
  { id: 'battle_trance', name: 'Battle Trance', icon: 'spell_nature_bloodlust', maxPoints: 2, row: 3, col: 2, desc: ["Your melee critical strikes increase your melee attack power by 5% for 10 seconds.", "10%"] },

  // Tier 5
  { id: 'bloodthirst', name: 'Bloodthirst', icon: 'spell_nature_bloodlust', maxPoints: 1, row: 4, col: 1, requires: { id: 'death_wish', points: 1 }, desc: ["Instantly attacks the target causing damage equal to 45% of your attack power. In addition, the next 5 successful melee attacks will restore health. 6 second cooldown."] },
  { id: 'precision', name: 'Precision', icon: 'ability_marksmanship', maxPoints: 3, row: 4, col: 2, desc: ["Increases your chance to hit with melee weapons by 1%.", "2%", "3%"] },
  { id: 'furious_attacks', name: 'Furious Attacks', icon: 'ability_warrior_furiousresolve', maxPoints: 2, row: 4, col: 0, desc: ["Your normal melee attacks have a chance to reduce all healing done to the target by 25% for 10 seconds.", "50%"] },

  // Tier 6
  { id: 'bloodsurge', name: 'Bloodsurge', icon: 'ability_warrior_bloodsurge', maxPoints: 2, row: 5, col: 0, desc: ["Your Heroic Strike, Bloodthirst, and Whirlwind hits have a 10% chance to make your next Slam instant and cost no rage.", "20%"] },
  { id: 'enraged_regeneration', name: 'Enraged Regeneration', icon: 'ability_warrior_enragedregeneration', maxPoints: 2, row: 5, col: 1, desc: ["Allows you to regenerate 10% of your total health over 10 seconds while Enraged.", "20%"] },
  { id: 'intensify_rage', name: 'Intensify Rage', icon: 'ability_warrior_endlessrage', maxPoints: 2, row: 5, col: 2, desc: ["Reduces the cooldown of your Bloodrage, Berserker Rage, Recklessness, and Death Wish abilities by 11%.", "22%"] },
  { id: 'imp_berserker_stance', name: 'Improved Berserker Stance', icon: 'ability_warrior_innerrage', maxPoints: 3, row: 5, col: 3, desc: ["Increases Attack Power by 3% and reduces threat generated by 10% while in Berserker Stance.", "6% / 20%", "10% / 30%"] },

  // Tier 7
  { id: 'rampage', name: 'Rampage', icon: 'ability_warrior_rampage', maxPoints: 1, row: 6, col: 1, requires: { id: 'bloodthirst', points: 1 }, desc: ["Unleashes a devastating combo, instantly striking the target with both weapons for 100% weapon damage and increasing your melee AP by 10% for 15 sec. This attack cannot be dodged, parried, or blocked. 30 Rage, 30 sec cd."] }
];

export const CHANGELOG: string[] = [
  "General Changes",
  "Design Philosophy: Warrior talent trees have been heavily compressed and modernized, bringing WotLK-tier fluidity to the Vanilla baseline. Point bloat has been slashed across all specs.",
  "Piercing Howl: This ability has been made baseline for all Warriors.",
  "Arms",
  "Identity: Master of tactical positioning, huge two-handed weapon bursts, and bleeds, now featuring greatly compressed weapon specializations.",
  "Core Foundation: Improved Rend, Tactical Mastery (moved to tier 1), Improved Charge grouped in Tier 1.",
  "Cross-Pollination: Iron Will, Improved Thunder Clap, Improved Overpower, Improved Heroic Strike organized in Tier 2.",
  "Sweeping Strikes: Moved down to serve as the 11-point anchor.",
  "Output: Deep Wounds, Impale, Two-Handed Weapon Specialization organized in Tier 3.",
  "Master of Arms: Consolidates all four previous weapon specializations into a single 5-point node in Tier 4.",
  "Mortal Strike: Positioned aggressively as the 21-point anchor.",
  "The Active Engine: Second Wind, Blood Frenzy organized in Tier 5 for PvP survival and physical damage scaling.",
  "Burst Mechanics: Sudden Death, Juggernaut organized in Tier 6.",
  "Bladestorm: Added as the 31-point capstone, providing massive AoE threat and immune-spin capability.",
  "Fury",
  "Identity: A bloodthirsty, dual-wielding berserker that scales furiously with critical strikes, given much better inherent sustain.",
  "Core Foundation: Booming Voice, Cruelty, Improved Demoralizing Shout grouped in Tier 1.",
  "Cross-Pollination: Unbridled Wrath, Improved Cleave, Blood Craze organized in Tier 2.",
  "Death Wish: Moved down to serve as the 11-point anchor.",
  "Output: Improved Execute, Enrage organized in Tier 3.",
  "Flurry: Kept as the defining Tier 4 output modifier.",
  "Bloodthirst: Positioned as the 21-point anchor.",
  "The Active Engine: Dual Wield Specialization, Precision organized in Tier 5.",
  "Burst Mechanics: Furious Attacks, Bloodsurge organized in Tier 6.",
  "Rampage: Added as the 31-point capstone mini-cooldown.",
  "Protection",
  "Identity: Transitions from a slow, rage-starved tank into an impenetrable wall of steel equipped with excellent mobility and passive reflection.",
  "Core Foundation: Improved Bloodrage, Shield Specialization, Improved Thunder Clap grouped in Tier 1.",
  "Cross-Pollination: Improved Revenge, Toughness, Last Stand organized in Tier 2.",
  "Concussion Blow: Moved down to serve as the 11-point anchor.",
  "Output: Shield Mastery, One-Handed Weapon Specialization, Improved Disarm organized in Tier 3.",
  "Shield Slam: Positioned as the 21-point anchor.",
  "The Active Engine: Focused Rage, Vitality organized in Tier 5 for sweeping stat bonuses.",
  "Mobility & Reaction: Warbringer, Devastate organized in Tier 6.",
  "Shockwave: Added as the 31-point capstone for massive AoE control and threat."
];
