// Auto-generated by generateWorld.cjs (POLISHED HANDCRAFTED CLASSIC+ EDITION)

export const REGIONS = {
  STARTING: 'Revamped Starting Zones',
  CAPITALS: 'Capital City Reclamations',
  EK: 'Eastern Kingdoms Expansion',
  KAL: 'Kalimdor Expansion',
  ISLES: 'The Uncharted Vanilla Isles'
};

export interface ZoneItem {
  id: string;
  name: string;
  level: string;
  hubs: string[];
  desc: string;
  description: string;
  lore: string;
  majorQuests?: string[];
  dungeonsAndRaids?: string[];
  rareSpawns?: string[];
  environmentalHazards?: string[];
}

export const zonesData: Record<string, ZoneItem[]> = {
  [REGIONS.STARTING]: [
  {
    "id": "NorthshireExpanded",
    "name": "Northshire Valley (Human)",
    "level": "1-10",
    "hubs": [
      "Northshire Abbey",
      "The Hidden Resistance Camp",
      "Echo Ridge Mine"
    ],
    "desc": "The iconic valley has been expanded. The Defias Brotherhood presence is not just a few thugs; it is a full-blown military occupation of the vineyards.",
    "lore": "The Defias have cut off the valley from Goldshire. Players must organize a militia, sabotage Defias siege engines, and escort Marshal McBride in a climatic push to reopen the southern pass.",
    "description": "The iconic valley has been expanded. The Defias Brotherhood presence is not just a few thugs; it is a full-blown military occupation of the vineyards.",
    "majorQuests": [
      "The Fate of Northshire Valley (Human)",
      "Defense of Northshire Abbey",
      "Secrets of The Hidden Resistance Camp"
    ],
    "dungeonsAndRaids": [
      "Northshire Valley (Human) Dungeon",
      "Northshire Valley (Human) Lair"
    ],
    "rareSpawns": [
      "Ancient Northshire Stalker",
      "Corrupted Vanguard of Northshire"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "EchoIsles",
    "name": "The Echo Isles (Troll)",
    "level": "1-10",
    "hubs": [
      "Vol'jin's Vanguard",
      "The Southern Atoll",
      "Sen'jin Encampment"
    ],
    "desc": "Trolls no longer share the Valley of Trials with Orcs. Players start directly on the Echo Isles, fighting to secure a permanent beachhead against Zalazane's dark voodoo magic.",
    "lore": "A desperate fight for survival. Players help Vol'jin train raptors, construct defensive totems, and push Zalazane's mind-controlled trolls back into the interior. The zone culminates in a massive level 10 event where the entire zone rallies to hold off a Sea Witch invasion.",
    "description": "Trolls no longer share the Valley of Trials with Orcs. Players start directly on the Echo Isles, fighting to secure a permanent beachhead against Zalazane's dark voodoo magic.",
    "majorQuests": [
      "The Fate of The Echo Isles (Troll)",
      "Defense of Vol'jin's Vanguard",
      "Secrets of The Southern Atoll"
    ],
    "dungeonsAndRaids": [
      "The Echo Isles (Troll) Dungeon",
      "The Echo Isles (Troll) Lair"
    ],
    "rareSpawns": [
      "Ancient The Stalker",
      "Corrupted Vanguard of The"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "NewTinkertown",
    "name": "Gnomeregan Surface (Gnome)",
    "level": "1-10",
    "hubs": [
      "Quarantine Zone 4",
      "The Scrap-Yard",
      "Mekkatorque's Command"
    ],
    "desc": "Gnomes begin in a heavily irradiated, quarantined camp right outside the sealed cog-doors of Gnomeregan.",
    "lore": "Pure technological survival. Players are tasked with venting radiation, saving irradiated survivors using experimental scrubbers, and testing the first prototypes of the Mechanostrider.",
    "description": "Gnomes begin in a heavily irradiated, quarantined camp right outside the sealed cog-doors of Gnomeregan.",
    "majorQuests": [
      "The Fate of Gnomeregan Surface (Gnome)",
      "Defense of Quarantine Zone 4",
      "Secrets of The Scrap-Yard"
    ],
    "dungeonsAndRaids": [
      "Gnomeregan Surface (Gnome) Dungeon",
      "Gnomeregan Surface (Gnome) Lair"
    ],
    "rareSpawns": [
      "Ancient Gnomeregan Stalker",
      "Corrupted Vanguard of Gnomeregan"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "ValleyOfTrials",
    "name": "Valley of Trials (Orc)",
    "level": "1-10",
    "hubs": [
      "The Proving Grounds",
      "Kolkar's Ruin",
      "Burning Blade Coven"
    ],
    "desc": "The harsh proving grounds are under direct assault by a massive Centaur warband seeking to wipe out the Orcs before they can establish Durotar.",
    "lore": "A brutal introduction to Horde life. Players hold the northern choke-point against waves of Centaur raiders in a continuous, dynamic zone event.",
    "description": "The harsh proving grounds are under direct assault by a massive Centaur warband seeking to wipe out the Orcs before they can establish Durotar.",
    "majorQuests": [
      "The Fate of Valley of Trials (Orc)",
      "Defense of The Proving Grounds",
      "Secrets of Kolkar's Ruin"
    ],
    "dungeonsAndRaids": [
      "Valley of Trials (Orc) Dungeon",
      "Valley of Trials (Orc) Lair"
    ],
    "rareSpawns": [
      "Ancient Valley Stalker",
      "Corrupted Vanguard of Valley"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "Deathknell",
    "name": "Deathknell (Undead)",
    "level": "1-10",
    "hubs": [
      "The Shadow Grave",
      "The Rotting Farm",
      "Night Web's Hollow"
    ],
    "desc": "A splinter faction of the Scourge has infiltrated the starting area, leading to a civil war among the freshly raised dead.",
    "lore": "Players awaken to utter chaos. You must prove your free will by actively resisting Lich King whispers (a unique debuff mechanic) while hunting down Scourge loyalists.",
    "description": "A splinter faction of the Scourge has infiltrated the starting area, leading to a civil war among the freshly raised dead.",
    "majorQuests": [
      "The Fate of Deathknell (Undead)",
      "Defense of The Shadow Grave",
      "Secrets of The Rotting Farm"
    ],
    "dungeonsAndRaids": [
      "Deathknell (Undead) Dungeon",
      "Deathknell (Undead) Lair"
    ],
    "rareSpawns": [
      "Ancient Deathknell Stalker",
      "Corrupted Vanguard of Deathknell"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "Shadowglen",
    "name": "Shadowglen (Night Elf)",
    "level": "1-10",
    "hubs": [
      "Aldrassil",
      "The Cleansing Pool",
      "Starbreeze Village"
    ],
    "desc": "Teldrassil is already failing. The Emerald Nightmare has seeped into the starting valley.",
    "lore": "A race against time. Players must use pure moonwell water to cleanse massive, pulsing nightmare nodes.",
    "description": "Teldrassil is already failing. The Emerald Nightmare has seeped into the starting valley.",
    "majorQuests": [
      "The Fate of Shadowglen (Night Elf)",
      "Defense of Aldrassil",
      "Secrets of The Cleansing Pool"
    ],
    "dungeonsAndRaids": [
      "Shadowglen (Night Elf) Dungeon",
      "Shadowglen (Night Elf) Lair"
    ],
    "rareSpawns": [
      "Ancient Shadowglen Stalker",
      "Corrupted Vanguard of Shadowglen"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "WildhammerPeak",
    "name": "Aerie Peak Heights (Wildhammer Dwarf)",
    "level": "1-10",
    "hubs": [
      "The Gryphon Roost",
      "Storm-Caller's Ridge",
      "The High Altar"
    ],
    "desc": "A starting experience for Wildhammer Dwarves high in the Hinterlands.",
    "lore": "Tame your first gryphon and defend the peak from Vilebranch Troll incursions.",
    "description": "A starting experience for Wildhammer Dwarves high in the Hinterlands.",
    "majorQuests": [
      "The Fate of Aerie Peak Heights (Wildhammer Dwarf)",
      "Defense of The Gryphon Roost",
      "Secrets of Storm-Caller's Ridge"
    ],
    "dungeonsAndRaids": [
      "Aerie Peak Heights (Wildhammer Dwarf) Dungeon",
      "Aerie Peak Heights (Wildhammer Dwarf) Lair"
    ],
    "rareSpawns": [
      "Ancient Aerie Stalker",
      "Corrupted Vanguard of Aerie"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "RevantuskCoast",
    "name": "Revantusk Shores (Forest Troll)",
    "level": "1-10",
    "hubs": [
      "Revantusk Village",
      "The Sunken Temple Beach",
      "Zentabra's Hut"
    ],
    "desc": "Forest trolls loyal to the Horde start on the rugged eastern coast of the Hinterlands.",
    "lore": "Reclaim ancient artifacts from the sea and battle murloc tribes to prove your worth to the Horde.",
    "description": "Forest trolls loyal to the Horde start on the rugged eastern coast of the Hinterlands.",
    "majorQuests": [
      "The Fate of Revantusk Shores (Forest Troll)",
      "Defense of Revantusk Village",
      "Secrets of The Sunken Temple Beach"
    ],
    "dungeonsAndRaids": [
      "Revantusk Shores (Forest Troll) Dungeon",
      "Revantusk Shores (Forest Troll) Lair"
    ],
    "rareSpawns": [
      "Ancient Revantusk Stalker",
      "Corrupted Vanguard of Revantusk"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  }
],
  [REGIONS.CAPITALS]: [
  {
    "id": "GnomereganReclamation",
    "name": "Operation: Gnomeregan",
    "level": "60 (World Event)",
    "hubs": [
      "Tinker's Command (Neutral)",
      "The Upper Cogway",
      "Irradiation Scrubbers"
    ],
    "desc": "A massive server-wide war effort to finally purge the radiation from Gnomeregan and reclaim it as a fully functional capital city.",
    "lore": "Both Alliance and Horde players participate in a server-wide event gathering copper, iron, and specialized engineering parts to build an atmospheric scrubber.",
    "description": "A massive server-wide war effort to finally purge the radiation from Gnomeregan and reclaim it as a fully functional capital city.",
    "majorQuests": [
      "The Fate of Operation: Gnomeregan",
      "Defense of Tinker's Command (Neutral)",
      "Secrets of The Upper Cogway"
    ],
    "dungeonsAndRaids": [
      "Operation: Gnomeregan Dungeon",
      "Operation: Gnomeregan Lair"
    ],
    "rareSpawns": [
      "Ancient Operation: Stalker",
      "Corrupted Vanguard of Operation:"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "ZalazanesFall",
    "name": "Zalazane's Fall",
    "level": "60 (World Event)",
    "hubs": [
      "Sen'jin Village (Command Post)",
      "The Voodoo Atoll",
      "The Dark Caverns"
    ],
    "desc": "The Horde rallies behind Vol'jin to launch a naval invasion of the inner Echo Isles, permanently removing Zalazane from power.",
    "lore": "Horde players participate in a 40-man open-world push across the islands, using troll bat-riders to bomb voodoo shields. Unlocks the inner Echo Isles as a sprawling troll capital.",
    "description": "The Horde rallies behind Vol'jin to launch a naval invasion of the inner Echo Isles, permanently removing Zalazane from power.",
    "majorQuests": [
      "The Fate of Zalazane's Fall",
      "Defense of Sen'jin Village (Command Post)",
      "Secrets of The Voodoo Atoll"
    ],
    "dungeonsAndRaids": [
      "Zalazane's Fall Dungeon",
      "Zalazane's Fall Lair"
    ],
    "rareSpawns": [
      "Ancient Zalazane's Stalker",
      "Corrupted Vanguard of Zalazane's"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "LordaeronSurface",
    "name": "Ruins of Lordaeron Reconstruction",
    "level": "60 (World Event)",
    "hubs": [
      "The Upper Courtyard",
      "Sylvanas' Vanguard",
      "The Blight Labs"
    ],
    "desc": "The Forsaken begin actively rebuilding the surface ruins above the Undercity, establishing it as a fortified citadel against the Scarlet Crusade.",
    "lore": "Players gather stone from the ruined walls and defend forsaken masons from constant Scarlet ambushes. Real buildings are constructed on the surface over time.",
    "description": "The Forsaken begin actively rebuilding the surface ruins above the Undercity, establishing it as a fortified citadel against the Scarlet Crusade.",
    "majorQuests": [
      "The Fate of Ruins of Lordaeron Reconstruction",
      "Defense of The Upper Courtyard",
      "Secrets of Sylvanas' Vanguard"
    ],
    "dungeonsAndRaids": [
      "Ruins of Lordaeron Reconstruction Dungeon",
      "Ruins of Lordaeron Reconstruction Lair"
    ],
    "rareSpawns": [
      "Ancient Ruins Stalker",
      "Corrupted Vanguard of Ruins"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "StromgardeRebuilt",
    "name": "Stromgarde Restoration",
    "level": "60 (World Event)",
    "hubs": [
      "Trollbane Hall",
      "The Syndicate Blockade",
      "Defenders Gate"
    ],
    "desc": "The Alliance pushes the Syndicate and Ogres out of the ruined city of Stromgarde in Arathi Highlands.",
    "lore": "A massive phased event where the Alliance secures the keep, repels Horde counter-attacks, and establishes a massive northern stronghold.",
    "description": "The Alliance pushes the Syndicate and Ogres out of the ruined city of Stromgarde in Arathi Highlands.",
    "majorQuests": [
      "The Fate of Stromgarde Restoration",
      "Defense of Trollbane Hall",
      "Secrets of The Syndicate Blockade"
    ],
    "dungeonsAndRaids": [
      "Stromgarde Restoration Dungeon",
      "Stromgarde Restoration Lair"
    ],
    "rareSpawns": [
      "Ancient Stromgarde Stalker",
      "Corrupted Vanguard of Stromgarde"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "GilneasCity",
    "name": "The Battle for Gilneas City",
    "level": "60 (World Event)",
    "hubs": [
      "Greymane Manor",
      "The Merchant Quarter",
      "The Military Ward"
    ],
    "desc": "The culmination of the Gilneas storyline. A three-way battle for the capital.",
    "lore": "The Forsaken attempt to plague the city while Genn Greymane tries to hold the line with his newly transformed army.",
    "description": "The culmination of the Gilneas storyline. A three-way battle for the capital.",
    "majorQuests": [
      "The Fate of The Battle for Gilneas City",
      "Defense of Greymane Manor",
      "Secrets of The Merchant Quarter"
    ],
    "dungeonsAndRaids": [
      "The Battle for Gilneas City Dungeon",
      "The Battle for Gilneas City Lair"
    ],
    "rareSpawns": [
      "Ancient The Stalker",
      "Corrupted Vanguard of The"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "MountHyjalSummit",
    "name": "Nordrassil Reborn",
    "level": "60 (World Event)",
    "hubs": [
      "The World Tree Roots",
      "Cenarion Encampment",
      "Archimonde's Remains"
    ],
    "desc": "Players help the Night Elves heal the World Tree after the cataclysmic events of the Third War.",
    "lore": "Gathering waters from the Well of Eternity and defending the tree from Twilight Hammer cultists seeking to reignite the dormant fel magic.",
    "description": "Players help the Night Elves heal the World Tree after the cataclysmic events of the Third War.",
    "majorQuests": [
      "The Fate of Nordrassil Reborn",
      "Defense of The World Tree Roots",
      "Secrets of Cenarion Encampment"
    ],
    "dungeonsAndRaids": [
      "Nordrassil Reborn Dungeon",
      "Nordrassil Reborn Lair"
    ],
    "rareSpawns": [
      "Ancient Nordrassil Stalker",
      "Corrupted Vanguard of Nordrassil"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  }
],
  [REGIONS.EK]: [
  {
    "id": "Gilneas",
    "name": "Gilneas (Beyond the Greymane Wall)",
    "level": "40-50",
    "hubs": [
      "Greymane City (Contested)",
      "Keel Harbor",
      "Tempest Watch",
      "The Blackwald"
    ],
    "desc": "The gates are breached, but the sea route is contested. The Worgen curse is rampant, and the Forsaken navy is bombarding the northern shores.",
    "lore": "Players must navigate a three-way war between human loyalists, feral worgen packs (the Bloodfang), and Sylvanas's vanguard.",
    "description": "The gates are breached, but the sea route is contested. The Worgen curse is rampant, and the Forsaken navy is bombarding the northern shores.",
    "majorQuests": [
      "The Fate of Gilneas (Beyond the Greymane Wall)",
      "Defense of Greymane City (Contested)",
      "Secrets of Keel Harbor"
    ],
    "dungeonsAndRaids": [
      "Gilneas (Beyond the Greymane Wall) Dungeon",
      "Gilneas (Beyond the Greymane Wall) Lair"
    ],
    "rareSpawns": [
      "Ancient Gilneas Stalker",
      "Corrupted Vanguard of Gilneas"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "Northeron",
    "name": "Northeron & Grim Batol Surface",
    "level": "50-55",
    "hubs": [
      "Kirthaven",
      "The Dragonmaw Gates",
      "Thundermar",
      "The Twilight Ridge"
    ],
    "desc": "The Wildhammer heartland east of the Wetlands. A rugged alpine zone focused on Gryphon mastery and the Dragonmaw clan.",
    "lore": "Players assist Falstad Wildhammer in uniting the scattered dwarf clans to prepare a siege on Grim Batol.",
    "description": "The Wildhammer heartland east of the Wetlands. A rugged alpine zone focused on Gryphon mastery and the Dragonmaw clan.",
    "majorQuests": [
      "The Fate of Northeron & Grim Batol Surface",
      "Defense of Kirthaven",
      "Secrets of The Dragonmaw Gates"
    ],
    "dungeonsAndRaids": [
      "Northeron & Grim Batol Surface Dungeon",
      "Northeron & Grim Batol Surface Lair"
    ],
    "rareSpawns": [
      "Ancient Northeron Stalker",
      "Corrupted Vanguard of Northeron"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "NorthEPL",
    "name": "The Northern Plaguelands (Quel'Thalas Border)",
    "level": "55-60",
    "hubs": [
      "Argent Forward Camp",
      "The Highborne Ruins",
      "Plague-wood Border",
      "The Thalassian Pass"
    ],
    "desc": "The scarred, impassable mountains north of Stratholme. A zone of pure horror where the Scourge has created massive flesh-stitcheries.",
    "lore": "Players finally see the physical border of Quel'Thalas. The High Elves provide quests to sabotage Scourge supply lines.",
    "description": "The scarred, impassable mountains north of Stratholme. A zone of pure horror where the Scourge has created massive flesh-stitcheries.",
    "majorQuests": [
      "The Fate of The Northern Plaguelands (Quel'Thalas Border)",
      "Defense of Argent Forward Camp",
      "Secrets of The Highborne Ruins"
    ],
    "dungeonsAndRaids": [
      "The Northern Plaguelands (Quel'Thalas Border) Dungeon",
      "The Northern Plaguelands (Quel'Thalas Border) Lair"
    ],
    "rareSpawns": [
      "Ancient The Stalker",
      "Corrupted Vanguard of The"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "Deadwind",
    "name": "Deadwind Pass (Expanded)",
    "level": "55-60",
    "hubs": [
      "Ariden's Camp (Neutral)",
      "The Vice",
      "Karazhan Cellars",
      "The Master's Cellar"
    ],
    "desc": "No longer just a travel hallway to Karazhan. Fully realized with an ogre settlement and a hidden warlock conclave.",
    "lore": "The zone has a passive debuff, 'Medivh's Paranoia', requiring players to craft specific torches via Alchemy to explore without taking massive shadow damage.",
    "description": "No longer just a travel hallway to Karazhan. Fully realized with an ogre settlement and a hidden warlock conclave.",
    "majorQuests": [
      "The Fate of Deadwind Pass (Expanded)",
      "Defense of Ariden's Camp (Neutral)",
      "Secrets of The Vice"
    ],
    "dungeonsAndRaids": [
      "Deadwind Pass (Expanded) Dungeon",
      "Deadwind Pass (Expanded) Lair"
    ],
    "rareSpawns": [
      "Ancient Deadwind Stalker",
      "Corrupted Vanguard of Deadwind"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "QuelthalasExterior",
    "name": "Quel'Thalas Exterior (The Dead Scar)",
    "level": "60",
    "hubs": [
      "Windrunner Spire",
      "The Ghostlands Border",
      "The Dead Scar Reach"
    ],
    "desc": "The burned out forests and scorched earth leading up to the Sunwell.",
    "lore": "Players fight remnants of the Scourge invasion from Warcraft 3. Features elite banshees and abominations.",
    "description": "The burned out forests and scorched earth leading up to the Sunwell.",
    "majorQuests": [
      "The Fate of Quel'Thalas Exterior (The Dead Scar)",
      "Defense of Windrunner Spire",
      "Secrets of The Ghostlands Border"
    ],
    "dungeonsAndRaids": [
      "Quel'Thalas Exterior (The Dead Scar) Dungeon",
      "Quel'Thalas Exterior (The Dead Scar) Lair"
    ],
    "rareSpawns": [
      "Ancient Quel'Thalas Stalker",
      "Corrupted Vanguard of Quel'Thalas"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "TirisfalGladesExpanded",
    "name": "Tirisfal Coast & Whispering Shore",
    "level": "10-20",
    "hubs": [
      "The Whispering Shore",
      "Agamand Mills Expanded",
      "The Forgotten Docks"
    ],
    "desc": "The forgotten northern coast of Tirisfal, infested with murlocs, naga, and submerged ruins.",
    "lore": "Uncover the dark secrets of what lies beneath the Whispering Shore, hinting at ancient Old God activity long before Ahn'Qiraj.",
    "description": "The forgotten northern coast of Tirisfal, infested with murlocs, naga, and submerged ruins.",
    "majorQuests": [
      "The Fate of Tirisfal Coast & Whispering Shore",
      "Defense of The Whispering Shore",
      "Secrets of Agamand Mills Expanded"
    ],
    "dungeonsAndRaids": [
      "Tirisfal Coast & Whispering Shore Dungeon",
      "Tirisfal Coast & Whispering Shore Lair"
    ],
    "rareSpawns": [
      "Ancient Tirisfal Stalker",
      "Corrupted Vanguard of Tirisfal"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "AlteracMountainsExpanded",
    "name": "Alterac Valleys & Peaks",
    "level": "35-45",
    "hubs": [
      "Crushridge Hold",
      "The Syndicate Stronghold",
      "Frostwolf Vanguard"
    ],
    "desc": "Expanded vertically to include massive Ogre fortresses and the Syndicate headquarters.",
    "lore": "Deepens the lore of the Perenolde family and their treachery. Neutral players can actually gain reputation with the Syndicate through dark deeds.",
    "description": "Expanded vertically to include massive Ogre fortresses and the Syndicate headquarters.",
    "majorQuests": [
      "The Fate of Alterac Valleys & Peaks",
      "Defense of Crushridge Hold",
      "Secrets of The Syndicate Stronghold"
    ],
    "dungeonsAndRaids": [
      "Alterac Valleys & Peaks Dungeon",
      "Alterac Valleys & Peaks Lair"
    ],
    "rareSpawns": [
      "Ancient Alterac Stalker",
      "Corrupted Vanguard of Alterac"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  }
],
  [REGIONS.KAL]: [
  {
    "id": "Uldum",
    "name": "Uldum (The Titan Vault)",
    "level": "55-60",
    "hubs": [
      "The Excavation",
      "Watcher's Rise",
      "The Obsidian Quarry",
      "The Halls of Origination"
    ],
    "desc": "The authentic Vanilla concept of Uldum: an austere, mechanical, subterranean desert zone. Pure, terrifying Titan geometry.",
    "lore": "Players breach the gates using the Discs of Norgannon. Inside, they find the Tol'vir fighting a losing war against the Qiraji.",
    "description": "The authentic Vanilla concept of Uldum: an austere, mechanical, subterranean desert zone. Pure, terrifying Titan geometry.",
    "majorQuests": [
      "The Fate of Uldum (The Titan Vault)",
      "Defense of The Excavation",
      "Secrets of Watcher's Rise"
    ],
    "dungeonsAndRaids": [
      "Uldum (The Titan Vault) Dungeon",
      "Uldum (The Titan Vault) Lair"
    ],
    "rareSpawns": [
      "Ancient Uldum Stalker",
      "Corrupted Vanguard of Uldum"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "Hyjal",
    "name": "Mount Hyjal",
    "level": "58-60",
    "hubs": [
      "Nordrassil Basecamp",
      "The Whispering Gorge",
      "Barrow Dens",
      "The Fel-Scarred Peak"
    ],
    "desc": "The summit of Kalimdor, scarred by Archimonde's death in WC3. The Emerald Nightmare bleeds into the waking world.",
    "lore": "The demons are mostly dead, but their fel-blood has corrupted the Barrow Dens. Players work with the Cenarion Circle to purge Doomguards and Nightmare stalkers.",
    "description": "The summit of Kalimdor, scarred by Archimonde's death in WC3. The Emerald Nightmare bleeds into the waking world.",
    "majorQuests": [
      "The Fate of Mount Hyjal",
      "Defense of Nordrassil Basecamp",
      "Secrets of The Whispering Gorge"
    ],
    "dungeonsAndRaids": [
      "Mount Hyjal Dungeon",
      "Mount Hyjal Lair"
    ],
    "rareSpawns": [
      "Ancient Mount Stalker",
      "Corrupted Vanguard of Mount"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "Azshara",
    "name": "Azshara (The Shattered Coast)",
    "level": "45-55",
    "hubs": [
      "Bilgewater Port",
      "Valormok (Expanded)",
      "Eldarath Ruins",
      "Timbermaw Vanguard"
    ],
    "desc": "Transformed from a barren cliffside into a bustling hub with a massive goblin port, Naga ruins, and the Blue Dragonflight.",
    "lore": "The Timbermaw War rages in the north. Azuregos now roams a much more dangerous, heavily populated elite region.",
    "description": "Transformed from a barren cliffside into a bustling hub with a massive goblin port, Naga ruins, and the Blue Dragonflight.",
    "majorQuests": [
      "The Fate of Azshara (The Shattered Coast)",
      "Defense of Bilgewater Port",
      "Secrets of Valormok (Expanded)"
    ],
    "dungeonsAndRaids": [
      "Azshara (The Shattered Coast) Dungeon",
      "Azshara (The Shattered Coast) Lair"
    ],
    "rareSpawns": [
      "Ancient Azshara Stalker",
      "Corrupted Vanguard of Azshara"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "Winterspring",
    "name": "Winterspring (Frostwhisper Gorge)",
    "level": "55-60",
    "hubs": [
      "Starfall Village",
      "Everlook (Expanded)",
      "Mazthoril Exterior",
      "Darkwhisper Pass"
    ],
    "desc": "The southern half is now a sprawling endgame zone leading up to the gates of Mount Hyjal.",
    "lore": "Features the Mazthoril Deeps dungeon. Darkwhisper Pass is transformed into an elite demon-farming zone.",
    "description": "The southern half is now a sprawling endgame zone leading up to the gates of Mount Hyjal.",
    "majorQuests": [
      "The Fate of Winterspring (Frostwhisper Gorge)",
      "Defense of Starfall Village",
      "Secrets of Everlook (Expanded)"
    ],
    "dungeonsAndRaids": [
      "Winterspring (Frostwhisper Gorge) Dungeon",
      "Winterspring (Frostwhisper Gorge) Lair"
    ],
    "rareSpawns": [
      "Ancient Winterspring Stalker",
      "Corrupted Vanguard of Winterspring"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "SilithusExpanded",
    "name": "Silithus (The Hive Wars)",
    "level": "55-60",
    "hubs": [
      "Cenarion Hold",
      "Valor's Rest",
      "Bronzebeard Encampment",
      "The Twilight Basecamp"
    ],
    "desc": "Expanded with massive underground hive networks that act as non-instanced micro-dungeons.",
    "lore": "Players can now fully explore the depths of Hive'Ashi, Zora, and Regal without entering the AQ instances.",
    "description": "Expanded with massive underground hive networks that act as non-instanced micro-dungeons.",
    "majorQuests": [
      "The Fate of Silithus (The Hive Wars)",
      "Defense of Cenarion Hold",
      "Secrets of Valor's Rest"
    ],
    "dungeonsAndRaids": [
      "Silithus (The Hive Wars) Dungeon",
      "Silithus (The Hive Wars) Lair"
    ],
    "rareSpawns": [
      "Ancient Silithus Stalker",
      "Corrupted Vanguard of Silithus"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "MoongladeExpanded",
    "name": "Moonglade Depths",
    "level": "50-60",
    "hubs": [
      "The Emerald Dream Portal",
      "Shrine of Remulos",
      "The Great Barrow"
    ],
    "desc": "The serene Moonglade is under attack from within the Emerald Dream.",
    "lore": "Phased combat events where Druids and their allies must defend the barrow dens from Nightmare incursions.",
    "description": "The serene Moonglade is under attack from within the Emerald Dream.",
    "majorQuests": [
      "The Fate of Moonglade Depths",
      "Defense of The Emerald Dream Portal",
      "Secrets of Shrine of Remulos"
    ],
    "dungeonsAndRaids": [
      "Moonglade Depths Dungeon",
      "Moonglade Depths Lair"
    ],
    "rareSpawns": [
      "Ancient Moonglade Stalker",
      "Corrupted Vanguard of Moonglade"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  }
],
  [REGIONS.ISLES]: [
  {
    "id": "Gillijim",
    "name": "Gillijim's Isle",
    "level": "50-55",
    "hubs": [
      "Booty Bay Forward Post",
      "Bloodsail Anchorage",
      "The Tiki Atoll",
      "The Cursed Cove"
    ],
    "desc": "A massive island off the coast of Stranglethorn, restored directly from the Vanilla Alpha files.",
    "lore": "A lush tropical warzone where the Bloodsail Buccaneers and the Steamwheedle Cartel fight a proxy war. Features the Gillijim Naval Battleground.",
    "description": "A massive island off the coast of Stranglethorn, restored directly from the Vanilla Alpha files.",
    "majorQuests": [
      "The Fate of Gillijim's Isle",
      "Defense of Booty Bay Forward Post",
      "Secrets of Bloodsail Anchorage"
    ],
    "dungeonsAndRaids": [
      "Gillijim's Isle Dungeon",
      "Gillijim's Isle Lair"
    ],
    "rareSpawns": [
      "Ancient Gillijim's Stalker",
      "Corrupted Vanguard of Gillijim's"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "Lapidis",
    "name": "Isle of Doctor Lapidis",
    "level": "50-55",
    "hubs": [
      "The Lapidis Estate",
      "The Vats",
      "The Mutated Shore"
    ],
    "desc": "A terrifying island filled with biological experiments gone wrong, restored from early Alpha map data.",
    "lore": "Doctor Lapidis has been creating massive chimaera-murloc hybrids. Players must infiltrate his mansion to steal his research notes.",
    "description": "A terrifying island filled with biological experiments gone wrong, restored from early Alpha map data.",
    "majorQuests": [
      "The Fate of Isle of Doctor Lapidis",
      "Defense of The Lapidis Estate",
      "Secrets of The Vats"
    ],
    "dungeonsAndRaids": [
      "Isle of Doctor Lapidis Dungeon",
      "Isle of Doctor Lapidis Lair"
    ],
    "rareSpawns": [
      "Ancient Isle Stalker",
      "Corrupted Vanguard of Isle"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "DragonIsles",
    "name": "The Dragon Isles (Vanilla Concept)",
    "level": "60",
    "hubs": [
      "The Shattered Beachhead",
      "The Old God Temple",
      "The Feral Roost"
    ],
    "desc": "A small, ominous archipelago north of Lordaeron featuring an ancient pre-Titan Old God temple and feral, devolved proto-dragons.",
    "lore": "An elite endgame zone. Players must construct a seaworthy vessel via a server-wide effort to explore its forgotten shores.",
    "description": "A small, ominous archipelago north of Lordaeron featuring an ancient pre-Titan Old God temple and feral, devolved proto-dragons.",
    "majorQuests": [
      "The Fate of The Dragon Isles (Vanilla Concept)",
      "Defense of The Shattered Beachhead",
      "Secrets of The Old God Temple"
    ],
    "dungeonsAndRaids": [
      "The Dragon Isles (Vanilla Concept) Dungeon",
      "The Dragon Isles (Vanilla Concept) Lair"
    ],
    "rareSpawns": [
      "Ancient The Stalker",
      "Corrupted Vanguard of The"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "TelAbim",
    "name": "Tel Abim",
    "level": "55-60",
    "hubs": [
      "Shipwreck Cove",
      "The Primate Ridge",
      "The Plantations"
    ],
    "desc": "The legendary south sea island of bananas. A dense tropical jungle island far south of Kalimdor.",
    "lore": "Ruled by territorial primate packs and ancient titan machinery buried deep within the jungle caldera.",
    "description": "The legendary south sea island of bananas. A dense tropical jungle island far south of Kalimdor.",
    "majorQuests": [
      "The Fate of Tel Abim",
      "Defense of Shipwreck Cove",
      "Secrets of The Primate Ridge"
    ],
    "dungeonsAndRaids": [
      "Tel Abim Dungeon",
      "Tel Abim Lair"
    ],
    "rareSpawns": [
      "Ancient Tel Stalker",
      "Corrupted Vanguard of Tel"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  },
  {
    "id": "PlunderIsle",
    "name": "Plunder Isle",
    "level": "50-60",
    "hubs": [
      "Bloodsail Hold",
      "The Pirate King's Court",
      "Smuggler's Run"
    ],
    "desc": "The true headquarters of the Bloodsail Buccaneers, located far south in the Great Sea.",
    "lore": "A sprawling pirate haven where outlaws rule. Players can earn infamy, battle naval privateers, and participate in high-seas heists.",
    "description": "The true headquarters of the Bloodsail Buccaneers, located far south in the Great Sea.",
    "majorQuests": [
      "The Fate of Plunder Isle",
      "Defense of Bloodsail Hold",
      "Secrets of The Pirate King's Court"
    ],
    "dungeonsAndRaids": [
      "Plunder Isle Dungeon",
      "Plunder Isle Lair"
    ],
    "rareSpawns": [
      "Ancient Plunder Stalker",
      "Corrupted Vanguard of Plunder"
    ],
    "environmentalHazards": [
      "Dense Fog reducing visibility",
      "Wilderness beasts stalking low-health targets"
    ]
  }
]
};

export const worldZonesData = zonesData;
